require("heatshrink").decompress(
  atob(
    "mEwwcBkmSpIC/yEACJ5bCBZGf/IFDgVJCJH/AAPkAoMgiQCDCIeTCAX//gRLz4RD//yCJvyv///w1MAoNPCoJcBLJRcFPpgCBn5uCUJoRCNwQRO/4RNQAYLFwBOCKAaSFCJR9CCIcnCgoCDCIikBn4CBCI6zBCIgCCCIzsEAAPPJQwRHQAxZDhL+E/MnUgoRFEQfJAoXkUJARFFIKwIF4RlDyf5CJibJcw4RILITUFTZARILIQ1JaggRSNBLmGCKSeJfA4RKcwY1NCILyDARbyLag4gMCIZ3LcwoRRX5YCDepIRI+QRPn6MOAWg=",
  ),
);
