// Generated by http://www.espruino.com/Image+Converter
// 48x48, 4 bit color, palette, transparent at index 0
// Icon shows a timer with radial visualization

require("heatshrink").decompress(atob("AH4A/AH4A/nkB/AEAD/k8nAH8/AHwA/mgA+AH81AHs0AHkEAH0UAH4UAH4UAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAHAUAH4UAH4UAH0UAH0EAHs0AHwA+mgA/AH88gH4A/AH4A/AA=="))
