// GB({t:"notify",id:1679479178,src:"Gadgetbridge",subject:"Test",body:"Test",sender:"Test",tel:"Test"})
var xxl = {
// private:
    msg: [],
    drawTimeout: undefined,
    xpos : 0,
    loopCount : 0,
    txt:'',
    wtot:0,
    fontStr:undefined,
    fontStr2:undefined,
        
    
    setFont:function(){
        if(xxl.fontStr === undefined){
            xxl.fontStr = E.toString(
                require('heatshrink').decompress(atob(
                'AH4A0j///kAgP/BAgAB4IIy/w+FPu/gBGRZ/LPoAM/AINgPwBAM/wAIF///BAsBBA9/BAwGBBAsDBA4YC/4/Dh4QDR4oQFBAfwBA38MQoIBMQQIE8IIGjh0DPvQHDPo/+PuEYNYQAFBCIAjSwPgg51DS4X4g6PDS4QIC4AIE/gIEAgIID8AITAYSZBXAIIGCQIIoOQIIDIYR/BKAoIPPoIIDQwngn4IEUIIIDUISzB8ByBWYYAja4QIFWYRECAAQ7BL4YACj4IB+AIXG4IIUPoQIEgYIHj4IDGod/BAxvBBAxvBBARrDBgJ9FZ4P4BATOB/+DP4wdCZoYACn7NH/4iDEogiQ/jPHR4pRCZwpsCHg1//gtBH4YiCn//KIYiCv7+Ej4NBA4IIED4IICUIZfBBAwDBCYLFDjwCBBAMPBAUYBA4ACBCI1FBBx/GBBLPGTQK1GAEjZHfgI1DAoPgX4JHDagQCBLIYFB/xQBYogFBcAIIGa4yNDn4IGAgIIDegYIFh4IHgYIHLAOABA/AEYxtBBAhEBQoIIEIwPP/AIG452BBAuD/4IGgP/z6PFdQPfBARFBWAI3BBAQXB8AeCZw4IGCgIISwAIHGAIIMKoQIHg4IHABheBCwwI1AG70CIQkDA4TGECAYSEv4IE/DCDAAf+W4IIFcQMPBA3AFYPwGIU/FoM/DoLsE+F/CAYSCBAPAegv4v5nFgf4EQgkC/gII/iDGBCQsRTYZHELJL6Fj/4n42FPoKPBCQYFCUJCzIb4rhDA4oyCdJD7IZQQABYIoAqvAHGgP4BA/8mDHHDY7ZI/rQGgF/BAyFBDQwIBPIzFFBAjqFDRZjHHw7OBBA/9MQ50HQxCYIVREAhDPaY5II/BB0P/4ABBHSG/BDQAcgJ/B4AIZEY5KGBAIZFBARksABwzIBH4I/AHsB/4I/ADVwA40D+AIGj4IH/4IGg4IHn4IGKAP/8AIEh4IBDIt//7jFgYQB4BEF//+IgwzGIgP/wBEG/hENFQJEGA4JEFFQREFFQJEOBAREFBAJEFBAREFBATQHIgoACIgoAvYQRuFQwQABMwblCAAKJDVIQACBDygDn4I/NcqYIVRC8E/DpmNYgIofcYIZAGrOB4AEBn6CCcAIIC/4ICeQIIBCoIIGAYIICMQIIBAYIIGv4IGgJ0BBAYDBHAIIGCgPfBAoiBaYYDBEQP8BAoiB+AIFn43BBAixDBA38BA/wBAhwBNgYIFJghfCEQIIEJwPgBAoAaEYIfBn5JBGoYICHATBEn/+BATBDP4IIWwPwBAuAgY8Bn4I5a4S2DBDbXCAAKPDUIP/37aDgEDBwIdB/DWcABo9DAAcDBA8fBA9/BA0BMIhtEBAzeBBAx1BvwHEPwP8BAp7B8AIFDIOABAiPCgAIEHgLWBBAgiB4AIHAYIIFV4N/a4vgBA+ABA0cQwQIEiAIHTAYIQI4oIeACyGBSAM//gIHbAYIEQwgINSgIITwEPZ4KvCBGDrBn4IFJIJHGBBZ0DwEHBCEDA4KhDh4nBBAP4bDwAQIof/dIZgDI4oIHZwRiGBDR9B+CzBBHP/wZQHBDCPBwKYHBAzwBwF/dNBrBBBcDBA8fBA7FFLoYIGLQIIFMoIIGn4IGgJ9FBAL9CXwIIDUARLEw4HBRwgYC//ABA38OgoIB8AIHQww7EBAiZGj4qFBAQ7EAEyeB/xKFg5ZB35tEYIIACUIgIDWYgIawEDHgM/BAZJBBGY+INcSYIVRC8E/DtqfZ//8E/I4ZQC/E/LIZiCBAJrG/gIEPoQICwAIUAYI8BAgQDDvgIya4gIUdIjyIBAahCfYqzCP4Trxn7pB8AI/AE0HTwMBUYIuCBC7hCBAjGDBAhaDBAg+H/BjfgYhHgZEDGwwIP/wIGh4IRNIgACj+/BCKeCeQmfBA8fBBHABAt/h4IGvwIJYYYAC/0HBA38BBPwA4kB/kDBA34BBLGFAwLxGBBPwFwLEFBA4AbNZQI/BH4I/BE4Aig/wgP8BAkDBBH4gP4BBoGBBQIIH+AIF/gIGNYQIIOg3+BA9+h4II4AIFv4IHn8fBBGABA2fBA0f34IIUQ0f/4IGh4II/wIPg4IIYgoIKgYIIYgoARgZOQBBEfBCE/BBWAgKRDn4GCwIIEgAIt/A+F///TAoIIeAP/+AIWh4IB8CzFBAOAZywA2v5RBAAPABAQHDMoadBAAZ3CBAqbCOgQIYT4bRBBD0H//8BArQCBAr0CwIIEPwXBBCxhCBAv8gEHBB18BDM+gEPLIo+IBFgDBg/ABBDACBDY0C/4IVgIIMwAICgAIDA4cAfQTHBAFcPA4xdBBA1/BA0fKI0HLQ5jHMQQIEh4HDZoQpDOgoILwAIG8EABAooCBAv+BA47CFg/AHyAIFeQnwCQ6GFT4IIGDgaqNUYbOPDgL/dABBhEGoYI2OQKoBNYYI/wAICn50mh4HD/wICg4GB3///j3E/wdB/DymACJHCAAJHDLJBrEBBCPeYAbOGBFeAAgTyFBIM/KAoIYTAIICR4YIIeQIICeXIAIcEj7/BDs/BAbNBBAx0ih4HD/wICg4ID/gICgIID+D/zABpiFRYQI2wEDQgLKDBH4ISToYILV4oIHa/7XfgP4N4wI/BCLgBZJjSnAAkHUAf8BAUPBAf+dI4II/4IeOAgIXvgIHMAIINUIIIBn5HEgBQHBDCYBBASPDBBEDBAb9FAHjgkBDIABgKEHBH4IFR/4A/AAyG/AF9/fooIC/gIH/wIHKA4IagE/BF7OoQwYIETAYIEVQ4AxOlAIVAAXgJI0HRoZSFBA1//4bFgagHh67FDIYAB4AHCgIGB3//+AZE/0Ha43wCgQIEEAImBBAYWCDwIIDIgRKBBAZWDBAhuEAYUcQAgDCiD7/fdoABn4I/BELF/BC3AHw/8BAsDC4ISGv4SHg4SBwASH/AIFh///x3GBBEPBCAaHH4IIGKI5jIn4QPQwIqGBAPga/YA/AA591BALNFgEPb40AgIXBwBRH/AIFeYRkGn//+AIFg79HgF/IKaP4AHypCAAKiDT4IACR4aVBAASrDQ0j5Dn4I/NcqYIBBC8E/D74LIqCCBGwDBnxHFBG9+Qw7MDBCbpCBBH8BAkHeA8BBAPweWI1CIApHCLYpZCBBX/PooIUeQoABn4IHAgYIg8AIHVoQIFPwRQFOoQIaR4s+VQ8eBAMDXgkOZY8CfdzXXBE68B/hHFBCawCBAv/4AIHc4QIFDYgIDDYhQEDYYIEDYZrL/l/BAb7C/ADBBAT7C+D2BBAT7CHgN/ZRAIHgb7mHwQ0BOgZZC4EfWoYIC8EfPowIBPo3wBC+AgfwgE/BHP/P4RQFBCMBBAqPBBASPDeQMABAr3Cv//WYYAaj4IIwAI9QgSPGBGh99cDZhD/AIH/gIH/yYmAAk/BH5rlTBoIIXgYAjj4IIcob7F8AIH/+ABA5XDLIvwBA//4AICgJ0HgEHfZEPBA7DBBA8Av4IHGALfHBAxKCA4g/DA4cDI47gMSQYIDawgIDHY6EDBAbvGj6oFBAQYFAAMQcA8edJArGdJhHHLJP//jpIeYbfEDgjfDdJ4JCKgwJBBBw4CfIwIGHw9/cCZqDBAajFBALPGBAOAVRAIIDYo1DFoiXEH44mGMYYvFBBCHCUI0DBA8/KZJSIdJb7IVRh0EQxaiFBAPAJoyLEAAUcA4wAOgYaHh4sDVogIDLwSiBBAZfCQAJQEUIxZDQw34SQSgE/wLCagoABO4gpBSAwhCQAyZHL4IIGfAIaGXpA+HeIRABDYZiEDYYIB8BcCQwxABBAf8TA6qCJQK8LZwgNDiCBEdpYREAAceBA8fV4jpGRwyoGBAK6GBAKfFVIYuFRgQuGCQQuFfggSHBAoSDEorOBBArzCBAoQCBAjeBBAzUBDAoQCLIprIBALqCBArqCBAqqHUAwIBWQz7FABE/AY0AGAYIDLoIIGIQgIDO4IIFTIQIFh4IHWYoIBYoRHFHgP8BAoZB+AIFfYQIEHgP+NYpWBSIIIEKwK8BBAhEDBArWCBArFCBAq0CBAjfDBAjODBAj5DXAgArNQIAF/AI1QoYACgII2Vt4AFeIYAE/zFIfYYIEKQ6bBBBHgBAs//52Gg4SBwAbHJQ0f/5KGgYSBJQ1/JQ8PJQ8BJXIbGJQIIGJQLDHn4IHg7VIBBEQf6wAEQI0B/AI1TgIAFBGyZbAG0B4AIGg4IHn4IGgP/BA0HBA8/BAwZBBAwZB/4ZHcQwQB8AIHJwy1IIo8A/x7HCJAjJDY5hHLIQbGh5RHPpCPIDYSzPgF/BA8PBA7pIAGEfwAI/BH4I/BH4IvAH4ABoAIHsAIHuAIHvgIHvwIHv4IIQA9/8AIGn4IHh4IHg4IHgIIHMZMgW34Ar/4AB/iHEBAX+BAcDBAX/UQgIMaYYISXoUfBD0DBAZZEBA5QbBETn3HwoI1XhQIMfbzOfI4cDBA8BA4X+Vg/8cWn4KA4+EMQZQEBBhrEh4IR4ADBn4IxdIQIFIgICCBBZrBBBR9ETAIIKcAoIBg/wdOg+EgLXHeQZrGBBeABCqzCj4IjLIgIGHgY+EBGoA3HoX4dKAIEdJryW8EPwDOGBGhFBwZQHBAJiGBByPCwaPEUIQIFWYWDWYgARLIIIgj67DOgc/BA9/BCAHEBCv8I44IjADhPCYojXC//+GIbpCBAr7CAAIIfAYU/BD0DBBc+HxH/BDXABCDzCBArSic65GFBGq8EAAjADBFI+HBCMDBCEBBA52EBAgAz/xiHBGoAgdyg+F/4IR4AIZNgIIF/zp3IoizDBGoALh4PHn7UH//4bgwrBBAsfXQYADv4IB+AHDgK7HEQP4KAoIB4E/BAxRBBAv8EwQIEGQV/BAhECj4IEAYUDBAcEIYaPOdP7pZAFTCBAAQI5gfgI4zyDBBsPBDQ1HKCMHBCEDBA8BCKEHPqB0bBBDOZPsYAsI4mABHEDcBAIsKDQIQa4gIDgAIIAFl/GgPwA4ZHD/gIDLIf+QxAIeh6zCn4IE4ADBj4IxHw5rjTBCqIeQa8EAGpZE/6CCBGsDAYTFEg4IMwAIeHoYIVcAbpIBAjpDeQjpDeQoA1Hw5QIMRB9EBBChWa8UDBAZZEBA4+E/4NCBGoA1YrYIigP4I40D+AIHRQ7pDBD4AS//8gZTEgZgBgf8BA/+VQ2D/4IVh4II4EPwEfBFH+G4RHEBDJ6BMgJ9EBBEA/0B/71HAC7yZHYIACHwYIEKAYIENYYIOwAITI4k/BA8fBDwAjaoIAB/gIHcAgIDfYgINLIgIQAAZrIBDZvHBAhQaBEbObfYTXGFIwIBbwg+EDgpHDDgj7MCQsfMRF/NZAIIgZTJBAoQBBAw1Hn6zT/BiHPo/ABAwYEBAazHDArOVBBDOhSwQSKUIrYCXgzYBBAy1BBAwbBBAotCBAg/DBAjFL/zFXUQwIKDRAsJTAsBTBBiIgEPTBCGHTBKqHXg7OHI5BZIdBAIC+B0GDAgIDJo0HUA0AggHGAAodDgySDKAgECh4IEFgU/BAn4R40H/y1COguAWgIIF+E/BAgXB/v/DoK5EPw6yC4B+GDIobCJIT7FCIwjIGo5HDZw3wfYprCEoJ9GZAqPCfwKhNWY7FIa5DpIfZBEBBBCOGBAJOCD4YICPgIIG//gBA/+HQjnBAAMPIYgIDWogcCn6+FY5AcCCJCHEIAYHDWIJICBAbVBAAJ3DDAbgGfYwICEIiPFBAoYEfYgIGMwwASDQd/BAacCNoIIGdgoICR4IIGP4IIFSAQIFNoQIFEQO/BAt//0/BAnBVAIIF4//8AIF76YBBAqpCBAzLBBA3gBA67BBAqzCBAruCBAoiBBAoALDgQINgIII/gIPgZSCAAhkDAAKwBAAvAn4IG8DcBAAvwBAasBBAQNDz4DC/AIDGwIIF/j8CBAJVGN4IIjSg/wX54AKPgwzBBGoAjQxC8seRBoDg4IHz4IH74DC+F/Q43wn4IG8EfBA3AIYUP/+AJgsD/yBGgKwHBBKcHUpAIJAEV/MIyoBBB8DBEfgIwwIJ+AIYVJC7IgDWHQwIIHn4IHj5iGBBMPBDIjHWbiPHBBB9IAH4A/AD8P/kAgP///ABAcfA4IIygEHBAgA2IoX4A4cDBARKBBA3+BAZWCAAIIVh4IGXAPgAgM/GwQI1KAQCDBDqPBBAKPEGwIIBUIkAv4IB+DgogLeBn4IQIIJPDYozWEBAbWEBAcfBEeAKAwI2/4IRgAIIAAIIDR4IIGUIIIGgYIHAG0MewWABAceJYXABAZMCg/gBAd/awXwBBk/BAQaEeYYsESAIABHwiQBBA4gBaQIIEEAII8I5BZHNZB9IR5CqSDYP3DQjXIdJAArHoMB+H4OYnABA/4BA//BBHhBA57BBBsDBAP4BAiqDBAoSCAAISHBArhDNwq+CEhAjMGpBaCI4kBA4P8OiwIB+IIHwKzPYo7XIiD/dABqDCwCRC8AI2AH8Ag/+gF+BAjZB4F/wAIDK4Pgv/AAwZfCv5hCv4IC+AIMA4QIH/ED+EHBAnwBAMDBBf4gIIdGoYIDYggII//BLYYIRR4QIFUIQMBBAaoCUoIPEVQXAVgL/3ACk/KwgI/Pv4I/AH8B////AIEh4IB/4IEv4IC4AIDA4X/8AiFEgsDBA8HEAU//g0DAgUH/wID+AnCBAgxDBAcfIYd/BAaqDn4IMLQXAAgIICKIXwBA/4BAhaBBDJRB/gIySAIIG/kPI4wIQgYIKR4ozBh6hFXiLXHdJD7J/gDBg4IDWQIkBn4MCgDWCXoQICgIIHfQQABHIZDBBARLDGwIICA4YkDJQQAcLIIzFGgZFER4I0HBCMeAQIIpI7QIRAF8EBA8OBA8fwAIGv7PFAALPGgEBMY7rB/gIFdYP+Gg35/4IFn/g/4/Fn/Av4IGwABBBAouBBAs8IAIIFnEAgYIFmCGBOo0fQw40GQxZ9Ggf//CGP/Z9H+J9HQxJ9IbA0+QxJ9HbIIIFkACBOo4Ahj6XHBH4I/BHv//AIyAFUB/5qGh48Hn///wIFv///4IFvwTBBAohBh+ABAnwgEHBAvggEDBB3n//zBC/mhwjG80PwYsY/gIGKAMTNY41GOhF4Qw9/TA6zBVQ0fXg8HZw8A/4rFAH8fBH4I/BGQA/ACEH//4BAsP//8NY3//wIZ/6PHn4I8I5AIJNZ6PIUJEB//gcWl8gfwBAt+BH4IOVYPzBHaG/BDQAYh4gBQo3wYg/wCYQIFAIIIGv4IFj0A/4IGgf+BA0P/DEH+AIH4AIHLI0P/wIGg5rHQyXgh/AGooIB8AIHI4wIQj0HwAIXOgKhGBChZFh4IHAH4ARkAIHMA8BBA8HBA7FBBA0/BA9/BBGABA5GHvwIHvAIHuAIHsCr/AFcH/4ADU4QI1e4jcHBEh4Hnx9IDQYI1AHsDIgPwBAkPBAP8BA/+UooIK/4I+AAXABGwAsMX4A2g/8BH4A/AH4ARvgIiW48PBEf4BA/wBA/AUf4ARjgIHjwIQj///55FBEYAag4jBXAsPBAPgI759CBFJHUMQprIPoWAUL4AKkACBFwswgEBBAs8gEDBAs+KgIIFn5mBBA3An4IG8BkGn/xBA0P/f/fo/8BAsD//4MYyrGAAN/4AIGIwy/CA40wgiGGnB9HQwMHQx+APo/Av6GOj/5Po0P//+Qx0BPpH/8CGPawwABhwHGgCGBAE8BIg8DBA8HBAa9DXAgEDXAhkDcwi9DBAi0Dn//AoKaBCoYICgarDBAcP/AIGj6rDBAarEBAbpGMALgGMALgGMoLgHn7gIFYxgEGhhgEfQg0I4EDGwp9CBAg0CPohgDv4IEGgX/BAhgBgf9BAiVBg/xBAgrC8IIDMAU/wIIDGgcBBAZgCvgIESoV/X4KVFBAwCCBAl8BA94BA9wQAbGHBCMABBAAegfABA0HBAcBPIIIFg4ICh4DCAggIEj4ECj7SEBAU+aQqzCRgOAaQQIFaQQIFaQQIFaQQIFGgagEGgZ3EFYYADh/4BAw0EMAiSHGwI0GMAajEGiBgEGhZgJGhBgJjg4BGgq/BZQhgBngMBGgt8IIJgFvDXEMAV4JQkfMAN4gYIDMAV4g/vf4t4h4IDvwCBvk/54ICHYIUB/+PBAVwBAZiDsBkC/xrEBAX8BA0f/AIGg/gBAxnCBA4AnhgyHjwIIh0PSIIADn0eg4IFngIDgYLCBAgUDBAkfBA8/BAcfBATKCGoM/BALpEn7CBwEDf4IID/+Af4QIEGgPwXIf3BAL/CVwXz/0ADgLCD4f+gIKBAAcB/EHGgbMEFYbyE8AIGGggkDMAYADgY0FIARgDAAZgEGgnAgY2FPoQIEGgUfBAhgCv4IESoX/BAgXBgf9BAhgBg/xBAgrC8IIDMAU/wIIDGgcBBAZgCvwIESoV/aIQ0CfIQIFAQQIEvgIHvAIHuCADYw4IaAEcf/71Gn5aBPQK2EBBXAegoIWh7GBAIMPBAkffoMHBEQsIBAcHHgIDBKAwIdR4oICWgw5DcVQ+GgZHCKQjgD8DyH+BXDBAaUBgIHCBAX+DAYID/8PA4YgC/+PA4QWBAAN/54HCvw6DBAWABAcPBAJTBBAcH54oCBAcBCII6BBAcAp4zCBAhHC/AIHI4gIEawoIDZwieBCQ8fBA4cDBAocCYowcBBAwcBBA8HBA4ARDQ7aBBAzaBBAqACBAh1DBAl/BAx8DBAcHTA6zMBAjXBeYLpGeYL7FFAQIDh4RBBAs/BAISBBAf/BAP/8AIEx4+G/5HH/yUBAAX4BAICBCQZ0CJoKfCBAfgWIYID4CqKUYbOPDgL7moD7GgJRCKAkDBAL7Fg4IBfYsf4D7Gn/HfY1/XgSzFBBA7CfYn8BAL7F/EPfYwRCBAv+BAL7GeQT7FHw5QIn/BfY0P4D7GQwT7FUIT7Ffgb73OoYiENgUfA4TqBBAV/RQYIGdQQICWIMHSAoIBQoYIDQgbiBa4QIDUAQIE/IID/gIB/0BBAd8BAKFBBAd+n6rCBAc+n46BBAk/DQP4BAkfGoXhBAZQEBBD7D/6MBAAXwOgb7DCQSSDBAn8VIYIDDoQcCFob7EBA8DBA8Ajz6YgE8fY5NCF4cB/4IGMYIIFfYQIEQ4YIER4YIDfYngBASNCUAYIJHYX+gYIGwAIGFAIIGboIaH8AIHcYI+MBBLxD//AOgYSDPoifBBAzxCVR6jCBATOIAAt8fbMHXoQAEYwYADaQIIFLQQIENgYIBn6BBPwYIBYgKQEBAP/8YHDMQX/+YIDwAIGz4IC+AIC8EfBArDBBAooCCIw6BBAwzBBAY1D/wIHI5J8DNYKMBAASTCPoISFgywCDYqpEWY4IIDgLOHn4IHgIIHABBiCFgoIHn4IHPoZGFBAxiBBAyYEDIiOCDIv4Lwp7HDJTrCDIoIFDIQIFGYQIEDIXABAgZB/0ABAkf//wBA7qBBAoZBCI4ADPoQI2wEDLQIEBBH4IUgIIHUwYECh4IHAFkHVIbqDh4IDewS8FBAITBYooIeIYcfj4IR/AIQVwQIF8ClFn8f4BHCBIM/I4J0DBDCYBBASYDBBEDBAZXBAG58DAAnAeYhMC+AIH/AIH/gIH/wIH/+PBA/PBA1/5/AgLdCBAMfBA8HBA8DBA8ABBEPBFqeCBBgAEh66IAEy8HBFtPBA7OQh7yQv4IH/4IIYo/+BA/8BA/4BA/ga4/ABA7ZFcE9ABA/PVQhDBUIIIGg4IHUIIIGn4IHVQIIGVQIIHR4iCCUIoICUIoRLEZH/x4IHdIgICLIIIGNYIIGh4IHR4LXDBAUBBA7qBcFX+BBF/VIYOCBGsAvx6DAgIIk/wIuHQgIKWAl8YpX4BA/8a6H/wAIH56qDBwV/BA8fBA8HBA8DBA8ABBEPBA4A/AA5QIMQ8BQyCYIn4IHXhDOJeSH4BA8H4AIGj4IHn4IH/4IIx5QHR4/8BA/4CKH+BA41JI49/NaEPBA/+R44Ibv5PDYQYIrGpBijAAMB+AIGgYIXj7WEBHJHDAgIInAgwINn4IDwAIHOkUPA4blDg4ID/jnDBAbZHAHc/LQ0/BA9/BA//BDi+DAAP4UQP4BAsDVAgABTgIbBS4l8VgSyDgF+KYX/8AICnzIDXgb2DFwJBCj7kEIIQ7DIIJrU/wIQ/gIHXhAA+wEBI4aGC4DFCKAnwXYIADa4SxBAAarB/gIH/4IIx4IH5/AY4YIBn4IHj4IHg4IHgYIHgAIIh4IRKAwIbTA4IJXgn8fnA+ILKKPjXhDpQfZEfBA9/BA//BBGPBA3+KA/8BA/4BA/wBA/ATA+AgYHD/y8H/D74oL7GgPHLI0DBA68BOgy8BBA0/BA7FBBAzFJh4IGXgIIGXgIRPcALyPHxBQIMREPBA6GIUJEA4b7/AA0HHwfgA4M/h5HGv8fBAf8BAU/MQ3/BDP4n5DDvwIK/gIHvgIHvwIHnwIHn4IHj4IHMTX+BBCYH/gIH4C8E+D63/zyE4BZHI4RrF/AICv5iGBDa3CRgTAFBGI+INciYIBBC8E8DrnoABCAAgxBGYsB+ABBBAkD/ABBBAkH/kHBAsDLYIIFgP/j4jFgH/35pGSAPABAqHBwAIFj//MQ0P/wIGJAIRPEZA1II5BZHNZB9IR5KhBDQqzCQwwGBHwwAqgf/AAX5G4UPBAZ/DBBCfBBBijCBAq6EBA6RC/+fBAs//gECBAS0B8AIFDIOABAoZBD4YDBDIQIFDIQIFDIQIFLKE/BA9/BBn+BA44CgFjBAf4eeAAReYhRC4AIEMYXgBAh1C+AIFVwP4BA/+BA//BBACBXIYFBv/ABA0/BA8PBA8HBA8BBA8AoAIHAAgIDKA4IhWY4IIXgQA/I5AIE/xiQTDzFIa47pIfZEPBA8/BA//BBBBEBAZQH/wIH/AIH+AIH8CYH4ChNXgYA+p5HH54ID/wHBgYIEMQUHBArFCBA8/BA9/BA7OJJggICIIQIF/AIQDRAsIHxBQIMRB0IQxCYIVQoIDXhAA9/1/I4fgBA/wBA65CBApiCBDZEEQxAIvHxBrkTBoIIXgQAkhAIHh4IIHQ8PSg8P//ABA5fCBAv/BBAuGRogSGFwlACQQABwAIBBoISCBAUDCwQIEh4ICj4IDj4IBgIREv4IBCAQICHQMDGopfBn48EZwIQCLIn8NY/4BAP+NIngBAPwBAnABAIqDAAOAh6gGMYgAEhz/dAAZ6DaAgI1BIJ8Bn5IFBGqqBv6HHbArpCBC8HBAP8BA7rFgIIB+DjhADDFERQJGDBAsDBA5hCBEPgIwwIch/8g60DBAM//8HYwYIBv//w//BB/HKApXBBB/8h/Aj4IM/4ITXgwII/AIFa4P4VoSHDv/gBAwdDQwYACDoKYDAFz6CGohFBAAJHDsAIDLIdwMAQIEvAIHvwIEQwV/BBGH8AEBWYd/44IGn/nBA0fBAg1Cg4IHgfjBAU/NYfnKA0Ak5HGeYQIqAGzpPBAiGEcA4IOPprXGgFnBA7pHgbgHh4IHj7pHv7pHv/HI41/w4IGvxZHvgIHvAIHuAIHoDo1sDpH8bpGgIIDQwcHR46qBBA0fBAiYDBBHHa4yqBBAyqBBAyqBcAwRFa4eDdI7gEeRAsCLJBrFBAUDBA8BBA8ABBEgb9UB4AIGh/AdI0f4LpGj/Da46PHn4IEMQQIJg6hHa44IJeQ8PBA8H4bpGBBJHHMQpZMBCOHOh4Asn4wHn+BHoX4BAeDdIxZEBBDpEx4IYZ4PABoQIeg4ILnxQdBEjtvAA1/a4oABI40GgIIDJgU/4YIGv/jBAalC/4II+YII+DSF+IIH+AIR+IIDI4XxBA4+KLJ5rIPooICgEDBCAA2HYN//gHDcAIIBeQhQBBALyDBAb7EgEHBAahCBAXBBB/ggPwj4IFgYIQAIIIQ4AIFWYYIDXghrFBAyGBAAKPGAAKPGDQw1EBAnwh+An5QFBAJZGBFZFBwbFGBCh0GBAqGCwaGEgAICTAgAtv42B/DOSvgIKa4mABCJtCWYIDBj+PBDRbCBB3wBA/AI4eAAQTXEBB59BBASPFBAyhBBALpFv4IBWYgArsEAWQQ1DuDpHvDgDBAd+ZwhXDBBGHcAgIC44IGn/n8EPwEfBAUfBA8HBA8DBA8ABBEnBA7pBBA5FBwbgGBASQDBCKPCwbgEUIQIFWYWDdOA1DdIhHDcAhZDBArgHBByYGBAyzHs4IGgLpQh4IHj4IHv4II47pGv+Ha41+cA98BA94dI9wdI9AdOsgdI/hcA0B8YIGVQLgGVQIIGVQLgGn4IHVQKzHw4IGVQIIGVQIRPv4IIGpBHCdIhQDa4hrDBAkHBA6PDcAihDBAtgdNU/LoQIGdI0/KwIAB/gIHKAc/w7gGBCWPBAyZB4CxBn4IHj4ImHwI1GI4ZTBLIwIXR4WHR4gIDUIizCwfwa6l+BA9/BBHABA/vXg4IHh4IHgYIHgIIHgFvcBAIHAGsnHweABAVnBA0B84IGg4IHh4IHn4IHv4IIHIbOMcBEP8AIGj4IHv4II44+Hw4IGv0HBA18BA4RIEZA1JLKBrIn6PHBCIkBHwYIvn+PBA5ZaADbGC/CsFBAP+AwUQBBF8n5ZFjF4BA0c/AIGj3wBA0fBAJnCBCosBBA3+BAyyB34IFOQQIII4oIIawgIEz4IHDYaPDj8BBA0eHYKzHAFUH4AIGh/HLIeAKAQIQn4IRTIgILj8D8BHFj+HBA0PBBHHBA0HBCBib4YIQwIIGjkABAwAsoEAv40B+AICsEBHoX8BAVwgYIC/wICvDFEBAV+BA9/BBGHBA/PWYU/BAU/9/AXAS8DBA8HBA8BBA8ABBEvBA8PHwwtBKAwIbTA5RBVQwABBAS8DAFzyGI5JZIQ0azIt7XPgb7Qj4IHv4II54+Gv+HKA1/LI98BA94BA9wTA9geX0geQ9hI40B8ZZGgfnNY0PBA8fBA8/BA68BWY+PYo8PBA18BCAaIFhI+HKBBiIg4IHQxCYIVRC8BeWcH4DyGj/BI40f4ZZGn/HcA4IRg4IGn0PWY7OHj4IIa48PBBHPBA0HBA4RBHw5raw4IHwaYGn0BeQ8AeWc/wDyGn+BI4xZINZIIax6zGXoLFGBFg+INciYIVRGAeVkB/AI/BC0P8P4v4I6Q34IaAEd////+FAGgYHBAAPABAUDBA8HBCo0DBBEPCwJABBApABz4IFg/+j4IFj/4BA1/BQIIE4YqBBAvP/gIGPYIIFLKQIHj4IL/wIHIAIACjAICddYANsBrDHwdwBAZZDvB9HvgIHv4IIw4IDwAIC44IH8CKDBAUfBA8HBA8DBAhjDBBFgAYU/dKIsCBFoA1dI4IEdIaGOTD0ga4zOFBAUBeRoDCh4IHn4IDdId/85QGv+HI41/KA9+BA98BA9wBA9gBA9AcFlnGgXwBAZ0D/gHCgIIDdIcHQw8PBA8fTBAIETAfAWYYIDIQbXDvwIHvgRNGoYMCBAo1Dnw5DI45ZFBARrFBAUDBA6PEBAahEBAknQwwAsUoYIFx49C/AIHeQYIEeQYIELIYIaIYoIrdIhZiBDa8HADcH4AIHZYYIE//gBA5FCg4MCBAT6BBA3/wAIH/gIDgF/BIQIEgYICh4ICkEAh4IBj5VCBYU/BIIIBgYICgIIDEwYbCSoMfBAItDBAM/BAIHCPAV/4AqCKIIICw68DHoV/MQZ1BAAN8BAaODvAICTIlwBAIYDAANgBAKzHWQ0AgjxhMAYACPQgIyZ4k/JAYIDj59Hj7NBBDo9DBDRQEBA8BA4X+Vg/8aUIAFh5MDAAU/x4yGBAKvDBApXCh/ABAnwBA58BBA/8BAeAPoYIEQ4YICKQYIBj4IEgF/BIIIFTYRnFDYQIEFoZiCBYK0FBAM/BAX4BAWHKAY0CMQgQCBAjWEBAZNEBAQYDBAjFHWQoAJA='
            )));
            xxl.fontStr2 = atob("Cg8VJBouIQwTExcdDBcMHBwRGBoaGhwVHBsMDB4eHhkyHB0bHhkYHB4PGBwWJR4cGxwdGhYdGiwbGhcWHBYkIh4aGhkaGhAaGg0NGg0nGhsaGhEYEBoXJxkZFRQOFCYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKDxkcIxwOHh4yEyMhAB4eHB4PDx4bJRAeChIjLjAxGRwcHBwcHCobGRkZGQ8PDw8eHhwcHBwcGx0dHR0dGhwiGhoaGhoaKBkaGhoaDQ0NDRsaGxsbGxseGxoaGhoZGhk=");
        }
        
        // Actual height 70 (69 - 0)
        g.setFontCustom(xxl.fontStr, 32, xxl.fontStr2, 72|65536);
    },
    
//public:
    show: function(theMessage){
        // console.log("msg = ");
        // console.log(theMessage);
        xxl.msg = theMessage;
        xxl.txt = xxl.msg.subject + ': ' + xxl.msg.body;
        xxl.setFont();
        xxl.wtot = g.stringMetrics(xxl.txt).width;
        xxl.xpos = 2 * g.getWidth();

        Bangle.loadWidgets();

        Bangle.on('touch', function (b, xy) {
            xxl.stop();
        });
        setWatch(xxl.stop, BTN1);
        Bangle.buzz(500,1);
        
        xxl.draw();
    },
//private:
    // schedule a draw for the next 30 FPS
    queueDraw: function() {
        if (xxl.drawTimeout) { return; } // clearTimeout(xxl.drawTimeout); }
            xxl.drawTimeout = setTimeout(function () {
            xxl.drawTimeout = undefined;
            xxl.draw();
        }, 32 - (Date.now() % 32));
    },

    
    stop:function() {
        // console.log("stop");
        if (xxl.drawTimeout) { clearTimeout(xxl.drawTimeout); }
        xxl.drawTimeout = undefined;
        g.reset();
        g.setBgColor('#ffff00');
        g.clear();
                           
        // Bangle.setLCDPower(0); // light off
        // Bangle.setLocked(true); // disable touch

        setTimeout(load, 100);
    },

    draw: function() {
        Bangle.setLCDPower(1); // light on
        Bangle.setLocked(false); // keep the touch input active
        g.setBgColor(0, 0, 0);
        g.setColor(1, 1, 1);
        g.clear();

        // g.setFontLECO1976Regular42();
        // g.setFont('6x8:5x9');
        xxl.setFont();
        g.setFontAlign(-1, -1);


        var gw = g.getWidth();
        // var text = xxl.msg.subject + ': ' + xxl.msg.body;
        // var wtot = g.stringMetrics(text).width;

        g.setBgColor('#000000');

        g.setColor('#ffffff');
        wh = 24; // widgets height
        h = g.getHeight() - wh;
        g.drawString(xxl.txt, xxl.xpos, wh);// widgets height
        g.drawString(xxl.txt, xxl.xpos - gw - 32, h / 2 + wh);

        g.reset();
        // widget redraw
        Bangle.drawWidgets();
                                            
        xxl.xpos -= 32;
        if (xxl.xpos < -xxl.wtot - gw * 2) {
            ++xxl.loopCount;
            if (xxl.loopCount > 2) {
                xxl.stop();
                return;
            }
            xxl.xpos = 3 * gw;
        }

        xxl.queueDraw();
    }
};


// for IDE
// var exports={};

exports.listener = function (type, msg) {
    // msg = {t:"add",id:int, src,title,subject,body,sender,tel, important:bool, new:bool}
    if (!msg) return;
    if (type === 'text' && msg.t !== 'remove') {
        msg.handled = true; // don't do anything else with the message
        xxl.show(msg);
    }
};

// debug
// var mymsg = {t:'notify', id:1231, src:'Gadgetbridge', new:true, handled:false, subject:'SMS', body:'Hello World. This is a long message. Can you read it?'};
// exports.listener('text', mymsg);





