require("heatshrink").decompress(atob("/4Ac+4CB8EAj4FC+AFK/AFH+YFE/YFB/gFB+IFHEYXwg41DAoPD7AFCh0AAoZoBAoovCAoMIAodAjF8AoXMvgFC/HP/k8AoXHAof/+f83gFC+H8hAFC/F8jALDjkcOIXwhgpCBYMPMoRdBh/MAocAnAFC4AFDCgMAFIX+AoILCAoRfCCIMDAoqPCDoQABL4IFGhgFIDQJYBAo7/VAAI="))
}
