const storage = require('Storage');
const locale = require("locale");



// add modifiied 4x5 numeric font
(function(graphics) {
  graphics.prototype.setFont4x5NumPretty = function() {
    this.setFontCustom(atob("IQAQDJgH4/An4QXr0Fa/BwnwdrcH63BCHwfr8Ha/"),45,atob("AwIEBAQEBAQEBAQEBA=="),5);
  };
})(Graphics);


// timeout used to update every minute
var drawTimeout;

// schedule a draw for the next minute
function queueDraw() {
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = setTimeout(function() {
    drawTimeout = undefined;
    draw();
  },60000-(Date.now()%60000));
}

// only draw the first time
function drawBg() {
  var bgImg = require("heatshrink").decompress(atob("2GwwkGIf4A/AH4A/AH4A/AHcRAAMiAYQALB4MQKv8AiWIACeBLH8RIgUiACBYCK/0YxERNqYWBWHsCTAVVC6UBWHyXDqFVAAVQDCQA6SwcM5gAEBoUF5hMCAgKwFK/Y9BwBHCAAqzBgAEB4pmD4BxEkBX8SoMFrhXFqEFK4VQK/5XHHoZWEVIQICAgRX/V45ICAAYODAoRfBK4TBBK/5XIUYi0CMYhlDK/4FCTwKuFK4a8FK/5XFI4VQK48FKwgOCK/4EBUQRPBK468E4ALCK/4FCrnFqqgCAQRfEKwNVDQZX/I4PAgpSCUwJTCW4pWEK/5XC5hWBgr8CfoRXDBQQIBK/5XFAAyvFhhX/K4yqEAAa1BK4i4EK/5XJ4pWCV/5XMUAYACBwhXDgBoBK/5XL5ivHAoRX/K5hTDK4kMK/5XI4tVqpYDgEFK4gFBK/5XHJYVcK4azEWoVQK/5XEhhGEqtQqCoBK4oAFK/4GDrj5EK4RiDAwRX/K45JFKAKuErheFK/5XJhnMWwgMBV/5XJVAhXFWoxX/K4JIBqChBAgRXGWoxX/K4JIBAAhNBKIoJBDQpX/JIYADVIy4BK/5XIWAhSCK4gMECgRX/IQauFK5PFV/5XGAAxXEABBX/gEFqAICqvMAoJXDgpnDqoABK/5XCJwL9FiBXDjgMCgoMDK/5XDJwJXDBAwMGK/5XBTwPFgBJCAgJTDBgxX/K4ZHCqBNBK4wMCLQJkDK/5XCe4fAUQRXEBgpX/K5CnCK4qtDBgZX/K4RGCJQlcK4YICVgKv/K4Q9DKAdcJQNM5lQBhIZFAHEowIRPgsFZJQA4jA+XjGCK/iWBWCAAEgWIkJW7WAZATiOIY66wpACqu+TQhW/WK0RACMQKn4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4AiiMSiIAGjGIAC4hHAD8hkUhiJWGiRMYAGuCLAsaBIMiACR2BB5wkUAw8SBo0SAYTcCK4coAwoA/ABMRWIMQAoMCxEhIfVQAokFBxsSxEgAgMYLgYZB5gAHDQNcoocDqoKB4tc4ouFrnMoIkEqoMFABY7MAAXACAUBKYIDBlGBFhpKBBYJ2CFgyAEA4RREggOEKxhHDhhXPgEIK4WIRIZLCqoAFK4imCFgavBFo5WECYRXDTxXAI4gKELg4oEgOCiBXIeIokBKYI4CCAZeCK461ECYYIGABAgCVwqJCMAiuEK6wfCH4KjCEgJhB4ozDJo5XHNwzVF4BXEJ4iuHK4JUBK6YMBKIYCBPgoAFgtUqpXDgtVLQTFGGQZRCMoRaBFQbYJK6xUCIQZdCqoAEVg4CFD4YAEIga6EWQRXCCoZEGK4kgK6CQEE4SKDIJBsEqoEBSQwAGKIIqDK4gsCcA6vLTQo4CQooGBK4tE4lMHISyDMgoJBJQhvIK4wuDHQgAEgRXDwBXFAA4cDEYR6BK4idELAr9EDoQqJe4YECFQISBAYINEAA0IVgWIwIJDggqIZYhQDI4NQAwInFA4PFaoVUqtEohnCK5q9CCYIEBK4auIgEoKYUYwQyCAFkFBprSEABkSxEgAgMBxGCK9wAfiJRBVQcoAwMRAH4ALjGIxERLwawBAH4APkK3FgMiAHRHDCRytEAH4A/AF8BiUhXAIAKkMSZQgADBIMSiUQEooLBD44bDAYYmCkIICFIYbEGooSBBgIyFgOIADeCEgh7BEjgAPiJXhwIiEjBWsLApXBxOZAC+YxCuEKwWpEbAAR1AuBGwRXbxGCVwweVzQXYcwRXTiUiABEhEIMSVq+IlGKWK6wBK6cv/4AJK4KuR1EiAoeYxnM2RxDzReQWAOAK8IgQ1EoCIsr5gABOQmowUoER2IwJXV+cRiMSiUikUhiMfK6OSJo2r3hXC4QbElgIBEZuYxBXV+UZzOhjOoxEQgEPK4MCIogAIwREB5Y6EJgQAC3ALGkWKK5sQV6rMGK6OIUY+YKwioGxYHB5cqK54ARn/zAwkgK6GawRJClA6FKwvC1INEXgXCWJRXdiBXQwQ/Db4xiDUoJMGzG8BZJXfwJWBK52iHocpBIeILgOaxhXC5AKECAYMCkRxGK4wNIABEv+YaEK5+YVoXMlAJGGoJXC5YFB1DAB1IbH4RXgFQKvBK6D5EdgealZDCxOSBoWJ1BdCNQgcIK6GRzOqAAOZjKvGxGBKwRXMSQinCAAKjBTgeI3gDBzADBMQYTCMofM5BLGK5k//4AELARXCDIRXOzRWEdQmoJoamBAgYTEIIeaCYgrGK5hWFK4sZxGCKwZXLUgnM3RiEIYgAI3AfExhiIK5/ymcjmcv/65D+eoxEgK52YVwnMFguSLBe4JYy7FK6XxiIABj5XDV4JXBiBXOwRKE4WpFYqcEAA0qCQuSBopNEK52qAAJXGxGBKwhXJzQ1FRwo4ClZWIkQSHYYotEK4gAGwX/+QFCl//lAEBn5XBkJXORo0oIg2Z1BWH5CWHzMsB4nLB4ZXLJoJXFBIfzwUQK5w0F5mKIg+ZkZXGNJGZxgQF3RXIfoOoAYOI0P/+IICj//1GK1Uv+auGK5GYK4ycIYA/L1IRIxbAGK44rH//6AgRXBAgRXBVwxXIIo3MlJFIYI24CBOiNIxPCK5vxK4iAB1JXBKwxXIVwyvKewxoKzAjGlRXVjJXBn5XPGQ5XLTwpXKaY/CK5/6AgWv/4VCn/yK5wyHcYZGNCBR8IeIKvRK4eIV6CbFK84TBK6gUBK6GMGRJGOB5LUI5m5K536AgUf/+aCgMvK58sGQ8pK57zBABGcEg/IK4uK1QVDzWp//5AwWfV4OIwJXPzBXIV6BXKahBXGAA//+QECl//AYMgK6AxH5kqK54PJahJXXiBXZGQJXOYBRXI5epK4mJzTMC1QDB//xBAOqz5XBwMAK5+oK5HCK7J8J5kpK4oYG//6AgRXCkBXQ0QxIRQJHICgpXU3JXN/IECj//kRNBK5+LGRJHJxiaFK6fJK6chK6MsGROKI5AUFlBnOK6+f/8QK6IxJ5nIIw+aI4oPPV7JNCK7XM1L2HYgxXHyQjKK53xOoUvK6ZCGGYpHOHo+CK7P6AYOoK8HLWA28B40oXwzTLK4uK1QAE1KvBjWpxGPK6eMGhcqI5siSwquL5kpK4gAH//yAgUfK8HIxRWDkQPIWAmLEJfM3JXQwRXU0Q1M4UoE4O8B5QOClggMV42J1TJEzP/+OpxGBJARXRyQ2N4YONACOJK4pWFK4WoxEgK4cBl/yiBXMzZIfABvCK6GCiBIBgMRa4OIwURLIpXFzBXt5GpK52IwJIB+cYKwRZDLAhX04QwBK4eKK4/yBoMAgc4VYUv+URlBjBLAZXFzKvuK4qvI+SjCVoMiJoMv+YDBiS8CK5GMK9kpK5epK4UhgANBkamCK4cBWIIJCK42iK9hQBK4pSBV4yuDn6lCK4ZiCWARXGyRWr4RPBK4gAGwJXBUgWDJAJXGMYRnBK42Y3hXrF4RXKxH/+KjCj5XJBgJXIzOMK9UqK6MIwRICK48AlEhK5GkK9WJK4wHCAAZXDjGBK5YNBK5GYK1PCFwZXJBQJXCUIJXF+RXFxBXIzOMK9G4K5uowRXCxEgV5ZRBiBXIySuoJwZXKxGBK6SvJzUrV1RXKBIRXRwRXJzOCV1RXK1CbBK4UowJXLhBXLzG8K8koFgpXIxGBK4cYK5gNBK5QhBV0kpK5oICK4mCK7OaliuoK4oAEeQJXDIYMfK5MBlGAK5eZ1BWh5D7EK5auBK4YMBkZXJiQUCK5eZxhXg3QpGK576BxBXJxGBAYJXMzCugFJBXDXYRCDK4kRxGDK45iBNYRXMEwMsKznLJIRXMAwMhK4fwAgUoxERK4XyMIZrDK5uZxZWb4UoE5BXG1CaDV4kAgZYBkMRV4MBiWICYhXOLDhWJK46aEV4sP+ZYBxEjmQECkATDK5+akStYExZXFAoRXEV4ZIBgJTCAAOCiISDK4upLBcsVsJXHIgJDE//zmYABn5IBgMRV4JVFK4jQDABeClZVTxQjMzBRBK4eBK4oAFBIUv+ZWGK6eZ1BYQ5eyER0YK4YABiBDEmZUCV4JSDK5kAlGIGhuZzTgBKpfCwSsNEAapBK4RcBABxXNgWI1I3OAAOIkUi3hVFkUoKp4ABzCpCK4UhK7sBWCAAE1ToCAAOqDKTPCGoQbBLgJXcgESEQJYTAC5WBKIZXBLgRXQmYAGn5XDgMYTQgApkI0DlEgK6P/ABIPDgKxCK1wABkK0CAB0jVw4ACCIsRiUiAE8hiJPQAH4ALA=="));
  g.reset();
  g.drawImage(bgImg,0,0);
}

function square(x,y,w,e) {
  g.setColor("#000").fillRect(x,y,x+w,y+w);
  g.setColor("#fff").fillRect(x+e,y+e,x+w-e,y+w-e);
}

function draw() {
  var d = new Date();
  var h = d.getHours(), m = d.getMinutes();
  h = ("0"+h).substr(-2);
  m = ("0"+m).substr(-2);

  g.reset();
  g.setBgColor(0,0,0);  //set background to black
  g.clearRect(65,15,172,50);       // clear number area

  g.setFont("4x5NumPretty",7);

// Draw outlined time
drawOutlinedText(h,65,15);
drawOutlinedText(m,120,15);



  // queue draw in one minute
  queueDraw();
}

g.clear();
drawBg();

// handle switch display on by pressing BTN1
Bangle.on('lcdPower',on=>{
  if (on) {
    draw(); // draw immediately, queue redraw
  } else { // stop draw timer
    if (drawTimeout) clearTimeout(drawTimeout);
    drawTimeout = undefined;
  }
});

Bangle.setUI("clock");  // Show launcher when middle button pressed

Bangle.loadWidgets();
require("widget_utils").swipeOn();

function drawOutlinedText(txt, x, y) {
  // 8-direction outline offsets
  const offsets = [
    [-1,0],[1,0],[0,-1],[0,1],
    [-1,-1],[1,-1],[-1,1],[1,1]
  ];

  // Outline color (white = strongest contrast on Bangle LCD)
  g.setColor("#00FFF0");

  offsets.forEach(o => {
    g.drawString(txt, x + o[0], y + o[1]);
  });

  // Main fill color (bright red)
  g.setColor("#ff3030");
  g.drawString(txt, x, y);
}



draw();
