/*
 * Includes
 */
const locale = require('locale');
const storage = require('Storage');

/*
 * Statics
 */
const SETTINGS_FILE = "bwclk.setting.json";
const TIMER_IDX = "bwclk";
const W = g.getWidth();
const H = g.getHeight();

/*
 * Settings
 */
let settings = {
  fullscreen: false,
  showLock: true,
  hideColon: false,
  showInfo: 0,
};

let saved_settings = storage.readJSON(SETTINGS_FILE, 1) || settings;
for (const key in saved_settings) {
  settings[key] = saved_settings[key]
}


/*
 * Assets
 */

// Manrope font
Graphics.prototype.setLargeFont = function(scale) {
  // Actual height 48 (49 - 2)
  this.setFontCustom(
    E.toString(require('heatshrink').decompress(atob('AFcH+AHFh/gA4sf4AHFn+AA4t/E43+AwsB/gHFgf4PH4AMgJ9Ngf/Pot//6bF/59F///PokfA4J9DEgIABEwYkB/7DDEgIlFCoRMDEgQsEDoRLEEgpoBA4JhGOIsHZ40PdwwA/L4SjHNAgGCP4cHA4wWDA4aVCA4gGDA4SNBe4IiBA4MPHYRBBEwScCA4d/EQUBaoRKDA4UBLQYECgb+EAgMHYYcHa4MPHoLBCBgMfYgcfBgM/PIc/BgN/A4YECIIQEDHwkDHwQHDGwQHENQUHA4d/QIQnCRIJJCSgYTCA4hqCA4hqCA4hiCA4ZCEA4RFBGYbrFAHxDGSohdDcgagFAAjPCEzicDToU/A4jPCAwbQCBwgrBgIHEFYKrDWoa7DaggA/AC0PAYV+AYSBCgKpCg4DDVIUfAYZ9BToIDDPoKVBAYfARoQDDXgMPFwTIBdYSYCv4LCv7zCXgYKCXAK8CHoUPXgY9Cn/vEYMPEwX/z46Bj4mBgf+n77CDwX4v54EIIIzCOgX/4I+CAQI9BHYQCCQ4I7CRASDBHYQHCv/Aj4+BGYIeBGAI+Bj/8AIIRBQIZjCRIiWBXgYHCPQgHBBgJ6DA4IEBPQaKBGYQ+BbgiCCAGZFDIIUBaAZBCgYHCQAQTBA4SACUwS8DDYQHBQAbVCQAYwBA4SABgYEBPoQCBFgU/CQWACgRDCHwKVCIYX+aYRDCHwMPAgY+Cn4EDHwX/AgY+B8bEFj/HA4RGCn+f94MBv45Cv+fA4J6C//+j5gBGIMBFoJWBQoRMB8E//4DBHIJcBv4HBEwJUCA4ImCj5MBA4KZCPYQHBZgRBCE4LICvwaCXAYA5PgQAEMIQAEUwQADQAJlCAARlBWYIACT4JtDAAMPA4IWESgg8CAwI+EEoPhHwYlCgY+DEoP4g4+DEoPAh4+CEoReBHwUfLYU/CwgMBXARqBHYQCCGoIjBgI+CgZSCHwcHAYY+Ch4lBJ4IbCjhACPwqUBPwqFCPwhQBIQZ+DOAKVFXooHCXop9DFAi8EFAT0GPoYAygwFEgOATISLDwBWDTQc/A4L6CTQKkCVQX+BYIHBDwX+BYIHBVQX8B4KqD+/wA4aBBj/AgK8CQIIJBA4a/BBIMBAgL/BAgUDYgL/BAII7BAQXgAII7BAQXAYQQxBYARrCMwQ0BAgV/HwYECHwgEBgY+EA4MPGwI8BA4UfGwI8BgYHBPofAQYOHPoeAR4QmBHwQHCEwI+CA4RVBHwQHCaggnBDwQHEHoIAEEQIA6v5NFfgSECBwZtEf4IHFOYQHEj4HGDwYHCDwPgv/jA4UHXQS8E/ED/AHDZ4MPSYKlCv+AYwIHDDwL7EgL7DAgTzCEwIpCeYTZBg4CBeYIJBAgICBFgIJBAgICBeYIEDHII0BAgg+EgI5CMocHGwJBCA4MfGwMD/h/BwF/PoQHC451CJIMDSgIjBA4PAA4QmBA4IhBA4JVBgEMA4bUDV4QeCAAf/HoIAENIIApOoIAEW4QAEW4QAEW4QAEWQRSFNIcDfYQMDny8DO4Q7BAQQjCewh+EHwcPToQ+Dv//ewkHUoI+En68DeIS0EHwMf/46CeYYlCHwQ0BKIY+BGgJ4Dh/nGgZZCAwKPEHYLpFDoKuFGgj4JgY0EHwQ0EYhIA6MAkf+BRBLIa5BQAJSCBgP4R4iVB/YHERoIACA4QGDE4SFBAoV/A4MH/ggBWIL7C8EfVoL4DwBHBFYIHBfYIRBAgT7CDgQEBgP4BgUBEIMDDgIMBgYMBg/gBgS5Ch/ABgUPFIMf4EHA4IEBHwUPCgJGCIIM/CgLgCAQJlBFIQFB44HBEIUBQYc/EIIHDAAIuBA4oeBRoSfBLAIHC/gHBEwIXC+AHBZghHBDwQADj4WCAHEPAwpWBKYYOCLwIHELYJUBghlDA4UcQogHBvgeDD4K0DDwIHBWgQeB4CyBh68CUAMf8DeCdIYHDdIfAfYjxCAgj2BAgbHCvwJCIIYCBBIMDHIX4BgUHFwMD+AMCA4Q0BAgg5CHwxICAQY5BdgQHBEgMDIYV/DgR1CA4PwP4KvDRgIACEYIHFWggABMQQHEZwd/Dwq1DHoTFEdooA/ACrBBcAZmC8DTCAATGBaYR+DwDTCRwbYDAASLBCIIGCFgQRBAG4='))),
    46,
    atob("EhooGyUkJiUnISYnFQ=="),
    63+(scale<<8)+(1<<16)
  );
  return this;
};

Graphics.prototype.setXLargeFont = function(scale) {
  // Actual height 53 (55 - 3)
  this.setFontCustom(
    E.toString(require('heatshrink').decompress(atob('AHM/8AIG/+AA4sD/wQGh/4EWQA/AC8YA40HNA0BRY8/RY0P/6LFgf//4iFA4IiFj4HBEQkHCAQiDHIIZGv4HCFQY5BDAo5CAAIpDDAfACA3wLYv//hsFKYxcCMgoiBOooiBQwwiBS40AHIgA/ACS/DLYjYCBAjQEBAYQDBAgHDUAbyDZQi3CegoHEVQQZFagUfW4Y0DaAgECaIJSEFYMPbIYNDv5ACGAIrBCgJ1EFYILCAAQWCj4zDGgILCegcDEQRNDHIIiCHgZ2BEQShFIqUDFYidCh5ODg4NCn40DAgd/AYR5BDILZEAAIMDAAYVCh7aHdYhKDbQg4Dv7rGBAihFCAwIDCAgA/AB3/eoa7GAAk/dgbVGDJrvCDK67DDIjaGdYpbCdYonCcQjjDEVUBEQ4A/AEMcAYV/NAUHcYUDawd/cYUPRYSmBBgaLBToP8BgYiBSgIiCj4iCg//EQSuDW4IMDVwYiCBgIiBBgrRDCATeBaIYqCv70DCgT4CEQMfIgQZBBoRnDv/3EQIvBDIffEQMHFwReBRYUfOgX/+IiDKIeHEQRRECwUHKwIuB8AiDIoJEBCwZFCv/4HIZaBIgPAEQS2CUYQiCD4SABEQcfOwIZBEQaHBO4RcEAAI/BEQQgBSIQiDTIRZBEQZuBVYQiDHoKWCEQQICFQIiDBAQeCEQQA/AANwA40BLIJ5BO4JWCBAUPAYR5En7RBUIQECN4SYCQQIiEh6CCEQk/BoQiBgYeCBoTrCAgT0CCgIfCFYQiBg4IBGgIiDj6rBg4rCBYLRDFYIiBbYIfBLgQiBIQYiD4JCCLgf/bQIWDBYV/EQV/BYXz/5FBgIiD5//IowZBD4M/NAX/BIPgDIJoC//5GgKUDn//4f/8KLE/wTBAAI8BEQPwj4HBVwYmBDgIZDN4QZCGYKJCHQP/JoSgCBATrCh5dBKITVDG4gICAAbvDAH5SCL4QADK4J5CCAiTCCAp1BCAqCDCAgiGCAIiFCAQiFeoIiFg6/FCAgiECAXnEQgQB/kfEQYQC4F/EQYQCgIiDfoIQBg4iDCAUAEQZUCcgIiDDIIQBEQhuBBoIiENoYiFDwQiECAQiFwEBPQQNCAQKDDEYMDDoMfRh4iGUwqvEESBiBaQ5oEbgr0FNAo+EEIwA+oAHGgJoFRAMHe4L0CAALNBBAT0BfwScDCAXweAL0DWgUPQYQiDwF/QYQiC/zTB+C0FBAL0CEQYIBGgMPCgIxBg4rCJIKsCh5IBBwTPCj4WBgYLBZ4V/MAIiBBQQrBEQYtCBYQiCO4QLFCwgiDIQIiGIoMHEQpFBn5FFD4JoENwRoGDgSUCAoKfBw//DgIiCT4auCFwN/T4RRET4TaCEQKoCDIQiCGgK/DAAQICdYQACHoIqCBAoQFEwIhFAH4AFQIROEj4IGXwIIGNwIACbgIhEBAiRCVwoqDTogHEW4QZFXgIZB/z9Cv49CF4MPBwI0Ca4LlB8ATCJoP4AoINDfQPAg7PBg4cBBwUfD4MfFYILCCwgOCf4QLEwEPCwILCgJaBn4WBBYQxCIQQiD+EDCYI5CBYRQBIo4fBMQIuBC4N/NAv8AoIcBSgU/FYIIBZIYrCW4hOCXIQZCgYUBv7jEh4uBZAscewZ8CgEgUYT0EEoQIBA4gICFQQIEHYQA+KQzdDAArdCAArpCEScHaIQiEvwiGe4QiFUwQiEbgIiFYIL0DEQTkBEQrJEEQc/cYYiCg4HBDIQiCfoRoEHQLaDEQQHBbQYiBCAT8Dn/BCAoXBJYP/OgZKC/6OEEARLCEQZLEEQZLEEQjKFEQI6EEQZLDEQbsGEQLjGYYYA/JIxzEg/AfgJSDAoPgfgiDC8COFAoPnaQj6CAAR+CW4TCFA4i6CDIqhCDIfwHoYHCYIN/GgKuBJ4JDBFYUf/C5CBYIZBv/Ag4ZBg4rBBYQTBAQIcBg4FBn5UBAQUfFwIfCEQeAgYfBAQUBFAKbCAQQiCGwIiE+A2BwBFNwE/AoM/EQJoIWwKCCh4cBFYKUERYV/W46uHFYIZGaJA0B/glBGYT0JIITiEMIJvCFQQAEHYQA/ABBlEOIhdGQAIRFSgQIBgQICn4IB8EAjiBCUYglCbQYeBEoQZCTwM/CYIZD/gEBUwIzBJ4UHYAU/EwIrBh4rCAoIXCn4rBCgUDAQN/FYMfBYIXBCYJnCBYXggf8HgQLCwEPEQQuBgJOECwILDCwgiLHIUHBYJFGD4IxBgYWCn4rBBwJoFDIYNBCgPADgKHBRYfDBQN/GAIrBToTLDVwYACDILiCWAb8DAAYzBYAjTCAAI9BAARNCBAoqCBAgQDFgbYCAH4AufgQACf4T8CAAT/CfgQACBwITCAAYOBCYQioh4iEAHQA=='))),
    46,
    atob("FR4uHyopKyksJSssGA=="),
    70+(scale<<8)+(1<<16)
  );
};

Graphics.prototype.setMediumFont = function(scale) {
  // Actual height 41 (42 - 2)
  this.setFontCustom(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAA/AAAAAAAA/AAAAAAAA/AAAAAAAA/AAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAB/AAAAAAAP/AAAAAAD//AAAAAA///AAAAAP///AAAAB///8AAAAf///AAAAH///wAAAB///+AAAAH///gAAAAH//4AAAAAH/+AAAAAAH/wAAAAAAH8AAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///8AAAAH////AAAAP////wAAAf////4AAA/////8AAB/////+AAD/gAAH+AAD+AAAD/AAH8AAAB/AAH4AAAA/gAH4AAAAfgAH4AAAAfgAPwAAAAfgAPwAAAAfgAPwAAAAfgAHwAAAAfgAH4AAAAfgAH4AAAA/gAH8AAAA/AAD+AAAD/AAD/gAAH/AAB/////+AAB/////8AAA/////4AAAf////wAAAH////gAAAB///+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAfwAAAAAAA/gAAAAAAA/AAAAAAAB/AAAAAAAD+AAAAAAAD8AAAAAAAH8AAAAAAAH//////AAH//////AAH//////AAH//////AAH//////AAH//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAA/AAAP4AAB/AAAf4AAD/AAA/4AAD/AAB/4AAH/AAD/4AAP/AAH/AAAf/AAH8AAA//AAH4AAB//AAP4AAD//AAPwAAH+/AAPwAAP8/AAPwAAf4/AAPwAA/4/AAPwAA/w/AAPwAB/g/AAPwAD/A/AAP4AH+A/AAH8AP8A/AAH/A/4A/AAD///wA/AAD///gA/AAB///AA/AAA//+AA/AAAP/8AA/AAAD/wAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAH4AAAHwAAH4AAAH4AAH4AAAH8AAH4AAAP+AAH4AAAH+AAH4A4AB/AAH4A+AA/AAH4B/AA/gAH4D/AAfgAH4H+AAfgAH4P+AAfgAH4f+AAfgAH4/+AAfgAH5/+AAfgAH5//AAfgAH7+/AA/gAH/8/gB/AAH/4f4H/AAH/wf//+AAH/gP//8AAH/AH//8AAH+AD//wAAH8AB//gAAD4AAf+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAD/AAAAAAAP/AAAAAAB//AAAAAAH//AAAAAAf//AAAAAB///AAAAAH///AAAAAf/8/AAAAB//w/AAAAH/+A/AAAA//4A/AAAD//gA/AAAH/+AA/AAAH/4AA/AAAH/gAA/AAAH+AAA/AAAHwAAA/AAAHAAf///AAEAAf///AAAAAf///AAAAAf///AAAAAf///AAAAAf///AAAAAAA/AAAAAAAA/AAAAAAAA/AAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAP/AHgAAH///AP4AAH///gP8AAH///gP8AAH///gP+AAH///gD/AAH/A/AB/AAH4A/AA/gAH4A+AAfgAH4B+AAfgAH4B+AAfgAH4B8AAfgAH4B8AAfgAH4B+AAfgAH4B+AAfgAH4B+AA/gAH4B/AA/AAH4A/gD/AAH4A/4H+AAH4Af//+AAH4AP//8AAH4AP//4AAHwAD//wAAAAAB//AAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///8AAAAD////AAAAP////wAAAf////4AAA/////8AAB/////+AAD/gP4H+AAD/AfgD/AAH8A/AB/AAH8A/AA/gAH4B+AAfgAH4B+AAfgAPwB8AAfgAPwB8AAfgAPwB+AAfgAPwB+AAfgAH4B+AAfgAH4B/AA/gAH8B/AB/AAH+A/wD/AAD+A/8P+AAB8Af//+AAB4AP//8AAAwAH//4AAAAAD//gAAAAAA//AAAAAAAP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAPwAAAAAAAPwAAAAAAAPwAAAAAAAPwAAAAHAAPwAAAA/AAPwAAAD/AAPwAAAf/AAPwAAB//AAPwAAP//AAPwAA//8AAPwAH//wAAPwAf/+AAAPwB//4AAAPwP//AAAAPw//8AAAAP3//gAAAAP//+AAAAAP//wAAAAAP//AAAAAAP/4AAAAAAP/gAAAAAAP+AAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAAH+A//gAAAf/h//4AAA//z//8AAB/////+AAD/////+AAD///+H/AAH+H/4B/AAH8B/wA/gAH4A/gAfgAH4A/gAfgAPwA/AAfgAPwA/AAfgAPwA/AAfgAPwA/AAfgAH4A/gAfgAH4A/gAfgAH8B/wA/gAH/H/4B/AAD///+H/AAD/////+AAB/////+AAA//z//8AAAf/h//4AAAH+A//gAAAAAAH+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAAAAD/8AAAAAAP/+AAAAAAf//AAcAAA///gA8AAB///wB+AAD/x/4B/AAD+AP4B/AAH8AH8A/gAH4AH8A/gAH4AD8AfgAP4AD8AfgAPwAB8AfgAPwAB8AfgAPwAB8AfgAPwAB8AfgAH4AD8AfgAH4AD4A/gAH8AH4B/AAD+APwD/AAD/g/wP+AAB/////+AAA/////8AAAf////4AAAP////wAAAH////AAAAA///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8APwAAAAD8APwAAAAD8APwAAAAD8APwAAAAD8APwAAAAD8APwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="), 46, atob("DxcjFyAfISAiHCAiEg=="), 54+(scale<<8)+(1<<16));
  return this;
};

Graphics.prototype.setSmallFont = function(scale) {
  // Actual height 28 (27 - 0)
  this.setFontCustom(
    atob('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/+MB//5wH//DAAAAAAAAAAAAAAAAAAAB8AAAHwAAAfAAAAAAAAAAAAAfAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAACDAAAYMAABgwAAGDPAAYP8ABv/AAH/gAH/sAB/gwAHmDBAAYN8ABh/wAH/4AB/8AB/8wAH+DAAcYMAABgwAAGDAAAYAAABgAAAAAAAAAAAAAAAAACAMAB/A8AP8B4A44DgHBgHAcHAcPgMA++AwD74DgPBwOBwHAYHAPBw4AeD/gA4H8AAgPAAAAAAAAAAAfgAAD/AHAcOA8Bg4HgGBg8AYGHgBw48ADnHgAP48AAPHgAAA8AAAHjAAA8/AAHn+AA84cAHjAwA4MDAHAwMA4DhwHAH+AIAPwAAAeAAAAAAAAAAAAA8AAcP8AH9/4A//DgHD4HAcHgcBgPAwGAcDAYA4MBwBxwHADnAOAH4AYD/gAAP8AAA/4AAABwAAACAAAAAB8AAAHwAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/gAH//wD+AP4fAAH3wAAHcAAAEgAAAAAAAAAAAAAgAAAHAAABfAAAcfAAHwfwH8Af//AAP/gAAAAAAAAAAAAAAAAAAAAAAAAcAAAAzAAADeAAAPwAAH8AAAf4AAAPwAAAzAAAHAAAAIAAAAAAAAAAAAAAMAAAAwAAADAAAAMAAAAwAAADAAAH/8AAf/wAADAAAAMAAAAwAAADAAAAMAAAAwAAAAAAAAAAAAAAHIAAAdgAAB+AAAAAAAAAAAAAAAAAAAAAwAAADAAAAMAAAAwAAADAAAAMAAAAwAAADAAAAMAAAAAAAAAAAAAAAAAAAAAAABwAAAHAAAAcAAAAAAAAAAAAAAAAAAAAAAPAAAP8AAP/AAP/AAP/AAB/AAAHgAAAAAAAAAAAAAAAAAAAAAAP/+AB//8APAB4A4ADgHAAHAYAAMBgAAwGAADAcAAcBwABwDwAeAH//wAP/+AAAAAAAAAAAAAAAAgAAAHAAAA4AAAHAAAAf//8B///wH///AAAAAAAAAAAAAAAAAAAACAAwA8AHAHwA8A4AHwHAA7AcAHMBgA8wGAHjAcA8MBwHgwDg8DAP/gMAP8AwAPADAAAAAAAAAAAAAYAYABwBgAHgGBgHAYOAcBh4AwGPgDAZ2AMBuYBwHxwOAeD/4BwH/AGAHwAAAAAAAAAAAABwAAAfAAAH8AAB+wAA/jAAPwMAD8AwAfADABwAMAAAAwAAD/8AAP/wAAAwAAADAAAAAAAAAAAAAAAAAAEAH/w4Af/D4B8cDgGDgHAYMAcBgwAwGDADAYOAcBg4BwGBwOAYH/wBgH+AAAPgAAAAAAAAAAAAAAAB//AAf//ADw8+AOHA4Bw4BwHDAHAYMAMBgwAwHDgHAcOAcA4cDgDg/8AAB/gAAB4AAAAAAAAAABgAAAGAAAAYAAMBgADwGAB/AYAfgBgP4AGH8AAZ/AAB/gAAH4AAAcAAAAAAAAAAAAAAAEAAPD+AD/f8AP/g4Bw8BwHDwHAYGAMBgYAwHBgDAcPAcA5+DgD//+AH5/wAAB8AAAAAAAAAAAAAAAA/gAAH/AwA8eDgDAcHAcBwcBgDAwGAMDAYAwMBwHBwHAYHAODh4Af//AA//4AAf8AAAAAAAAAAAAAAAAAAAAABwcAAHBwAAYDAAAAAAAAAAAAAAAAAAAAAAAAADgByAOAH4AwAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAB4AAAPwAABzgAAOHAABwOAAOAcAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMYAAAxgAADGAAAMYAAAxgAADGAAAMYAAAxgAADGAAAMYAAAxgAADGAAAMYAAAxgAADGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAIAA4BwABwOAADhwAAHOAAAPwAAAeAAAAwAAAAAAAAAAAAAAAAAAAAAAAAABgAAAeAAAD4AAAcAAABwAAAGAPnAYB+cBgPAAHA4AAePAAA/4AAB/AAAAAAAAAAAAAAAAAAAAAAAH8AAD/8AAfj4ADgBwAcADgDgAHAMD4MBwfw4HDjhgYMGGBgwYYGDBhgYOOGBw/w4DD/jgMAOMA4AYABwBgADwOAAH/wAAH+AAAAAAAAAAAAAAEAAADwAAB/AAA/wAAf4AAP9gAH+GAB/AYAHgBgAfAGAB/gYAA/xgAAf+AAAP8AAAH+AAAD8AAABwAAAAAAAAAAAAAAH///Af//8BgMAwGAwDAYDAMBgMAwGAwDAYDAMBgMAwHBwHAePgcA//DwB/P+AAgfwAAAYAAAAAAA/+AAH/8AB+D8APAB4A4ADgHAAHAcAAcBgAAwGAADAYAAMBgAAwHAAHAcAAcA4ADgDwAeAHwHwAPAeAAMBgAAAAAAAAAAAAAAAf//8B///wGAADAYAAMBgAAwGAADAYAAMBgAAwGAADAcAAcBwABwDgAOAHgDwAP/+AAf/wAAP4AAAAAAAAAAAAAAAB///wH///AYDAMBgMAwGAwDAYDAMBgMAwGAwDAYDAMBgMAwGAwDAYAAMBgAAwAAAAAAAAAAAAAAH///Af//8BgGAAGAYAAYBgABgGAAGAYAAYBgABgGAAGAYAAYAAABgAAAAAAAAA/8AAH/8AB+D8APABwA4ADgHAAHAcAAcBgAAwGAADAYAAMBgAAwHAYHAcBgcA4GDgDwYeAHh/wAGH8AAAfAAAAAAAAAAAAAAAAf//8B///wAAYAAABgAAAGAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAYAAABgAB///wH///AAAAAAAAAAAAAAAAAAAB///wH///Af//8AAAAAAAAAAAABgAAAHgAAAOAAAAcAAAAwAAADAAAAMAAABwH//+Af//wB//+AAAAAAAAAAAAAAAAAAAAf//8B///wAAwAAAHgAAA/AAAHOAAA4eAAHA8AA4B4AHADwB4AHgHAAPAYAAcBAAAQAAAAAAAAAAAAAAH///Af//8B///wAAADAAAAMAAAAwAAADAAAAMAAAAwAAADAAAAMAAAAwAAAAAAAAAB///wH///APwAAAPwAAAPwAAAHwAAAH4AAAH4AAAH4AAADwAAA/AAAPwAAD8AAA/AAAPgAAH4AAB+AAAf//8B///wH///AAAAAAAAAAAAAAAAAAAB///wH///AfAAAAeAAAA+AAAA+AAAA8AAAB8AAAB4AAAD4AAADwAAAHwAAAHgH///Af//8AAAAAAAAAAAAAAAD/4AAf/wAH4PwA8AHgDgAOAcAAcBwABwGAADAYAAMBgAAwGAADAcAAcBwABwDgAOAPAB4AfAfAA//4AA/+AAAfAAAAAAAAAAAB///wH///AYAwABgDAAGAMAAYAwABgDAAGAMAAYAwABwHAAHAcAAPHgAAf8AAA/gAAAAAAAAAAAAP/gAB//AAfg/ADwAeAOAA4BwABwHAAHAYAAMBgAAwGAADAYAAMBwAJwHAB3AOAD4A8AHgB8B+AD//8AD/4wAB8AAAAAAAAAAAH///Af//8BgDAAGAMAAYAwABgDAAGAMAAYAwABgDgAHAfgAcB/gA8efgB/wfAD+AcAAAAQAAAAAAAAAACAMAB+A8AP8D4A44DgHBgHAcHAcBgcAwGAwDAYDgMBwOAwHAYHAOBwcA8HjgB4P8ADgfgAAAYAGAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAf//8B///wH///AYAAABgAAAGAAAAYAAABgAAAGAAAAYAAAAAAAAAAAAAf//AB//+AAAA8AAAA4AAABwAAAHAAAAMAAAAwAAADAAAAcAAABwAAAOAAAB4B///AH//4Af/+AAAAAAAAAAAYAAAB8AAAH+AAAD/AAAB/gAAA/wAAAf4AAAPwAAAPAAAD8AAB/gAA/wAAf4AAP8AAH+AAAfAAABgAAAEAAAAfAAAB/gAAB/4AAAf8AAAH/AAAD/AAAB8AAB/wAB/4AA/4AA/4AAH8AAAfgAAB/4AAAf8AAAH/AAAD/wAAA/AAAH8AAH/gAD/gAD/wAB/wAAHwAAAYAAAAAAAQGAADAcAA8B8AHgB8B8AB4PAAD74AAD+AAAHwAAA/gAAPvgAB4PAAfAfAHwAeAcAA8BgAAwAAABAQAAABwAAAHwAAAHwAAAPwAAAPgAAAPgAAAP/wAB//AAfAAAH4AAA+AAAPgAAB4AAAGAAAAQAAAAAAAAGAABAYAAcBgADwGAA/AYAPsBgB8wGAfDAYHwMBg+AwGPgDAb4AMB+AAwHwADAcAAMBAAAwAAAAAAAAAAAAAAAAAAAAAAAD/////////wAAADAAAAMAAAAAAAAAAAAAAAAAAAAAAB4AAAH+AAAH/gAAB/4AAAf+AAAH8AAADwAAAAAAAAAAAAAAAAAAAwAAADAAAAMAAAA//////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAADgAAAcAAADgAAAcAAADgAAAcAAAA4AAABwAAADgAAAHAAAAOAAAAQAAAAAAAAAAAAAAAAAAAAGAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAYAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfAADj+AAee8ADxxwAOGDAAwYMADDgwAMODAAwwcADjDgAHt8AAf/8AAf/wAAAAAAAAAAAAAAAAAAAf//8B///wAHgeAAYAYADgBwAMADAAwAMADAAwAOAHAA4AcAB4HgAD/8AAH/gAADwAAAAAAAAAAAAH8AAB/4AAP/4ABwDgAOAHAA4AcADAAwAMADAAwAMADgBwAPAPAAeB4AA4HAABAAAAAAAAAP8AAB/4AAf/4ABwDgAOAHAA4AMADAAwAMADAAwAMADgBwAHAOAf//4B///wH///AAAAAAAAAAAAAAAAB+AAAf+AAD/8AAcw4ADjBwAOMHAAwwMADDAwAMMDAA4wcADjDwAHseAAPxwAAfGAAAAAAAAAAADAAAAMAAAH//8A///wH///AYwAABjAAAGMAAAYwAAAAAAAAB/gAAP/AwD//HgOAcOBwA4cHABhwYAGDBgAYMGABhwcAOHA4Bw8D///gf//8B///AAAAAAAAAAAAAAAAAAAH///Af//8AB8AAAGAAAA4AAADAAAAMAAAAwAAADgAAAPAAAAfgAAA//wAA//AAAAAAAAAAAAAAAAAAABz//wHP//AY//8AAAAAAAAAAAAAAMAAAAwAAAP5////n///gAAAAAAAAAAAAAAAAAAf//8B///wAAGAAAA8AAAH4AAB5wAAPDgAB4HAAPAOAA4AcACAAwAAABAAAAAAAAAAH///Af//8B///wAAAAAAAAAAAAAAAAAAAA//8AD//wAHgAAA4AAADAAAAMAAAAwAAADgAAAPAAAAf/8AA//wAHAAAA4AAADAAAAMAAAAwAAADgAAAPAAAAf/8AA//wAAAAAAAAAAAAAAAAAAAA//8AD//wAHwAAAYAAADgAAAMAAAAwAAADAAAAOAAAA8AAAB+AAAD//AAD/8AAAAAAAAAAAAAAAAH4AAB/4AAP/wABwDgAOAHAA4AcADAAwAMADAAwAMADgBwAOAHAAeB4AA//AAB/4AAA8AAAAAAAAAAAAAAAAH///wf///A8DwADADAAcAOABgAYAGABgAYAGABwA4AHADgAPA8AAf/gAA/8AAAeAAAAAAAAAAAAB/gAAP/AAD//AAOAcABwA4AHABgAYAGABgAYAGABgAcAOAA4BwAD///wf///B///8AAAAAAAAAAAAAAAAAAAP//AA//8AB8AAAOAAAA4AAADAAAAMAAAAwAAAAAAAABgYAAPh4AB/HgAOcHAAwwcADDgwAMGDAAwYMADhwwAOHHAAeP4AA4fgABA4AAAAAADAAAAMAAAAwAAA//+AD//+AP//8ADABwAMADAAwAMADAAwAAAAAAAAAAD/gAAP/4AA//4AAAHgAAAHAAAAcAAAAwAAADAAAAMAAABwAAAOAA//wAD//wAP//AAAAAAAAAAAIAAAA4AAAD8AAAD+AAAB/AAAA/gAAAfAAAB8AAA/wAAf4AAP8AAD+AAAPAAAAgAAACAAAAPAAAA/wAAA/4AAAP8AAAH8AAAHwAAH+AAD/AAD/AAAPgAAA/gAAA/wAAAf4AAAH8AAAHwAAH/AAD/gAD/gAAPwAAAwAAAAAAQAMADAA4AcAB4HgADw8AAHvgAAH4AAAPAAAD+AAAeeAADw8AA8A8ADgBwAMADAAAAAAEAAAAcAAAB+AAAB+AAAB/ADAA/h8AAf/wAAf4AAH8AAD+AAB/AAA/wAAH4AAAcAAAAAAAAAAAQAMADAAwA8ADAHwAMA/AAwPMADB4wAMODAAzwMADeAwAPgDAA8AMADgAwAIAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAP///9//////8P/wAAADAAAAMAAAAAAAAAAAAAAAAAAf//8B///wH///AAAAAAAAAAAAAAAwAAADAAAAOAAAA//5/9////wAH4AAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAB4AAAPgAAA4AAABwAAAHAAAAcAAAA4AAADgAAAOAAAB4AAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAGAAABwAAAOAAABwAAAHAAAAcAAAA4AAABwAAABgAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAOAB4B4ADwPAAHh4AAPPAAAf4AAA/AAAB4AAAPwAAB/gAAPPAAB4eAAPA8AB4B4AHADgAIAEAAAAAAADAAAAMAAAAwAAADAAAAMAAAAwAAHDDgA8MPADww8AGDBgAAMAAAAwAAADAAAAMAAAAwAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADH//gOf/+Ax//wAAAAAAAAAAAAAAAAAAAD+AAA/+AAH/8AA8A4ADgBwAMAHAHwAPgfAA+AcADAAwAcADgDgAHgeAAOBwAAQAAAAAAAAAwDAADAMAAMBwA///AH//8A///wHAwDAcDAMBgMAwGAwDAcDAMA4AAwB4ADADAAMAAAAAAAAAADDhgAe/vAA//4AB4PAAGAMAA4A4ADABgAMAGAAwAYADABgAOAOAAcBwAB4PAAP/+AB7+8ADBBgAAAAAEAAAAcAAAB8BmAB8GYAD8ZgAD9mAAD+YAAD/8AAf/wAH+YAA+ZgAPhmAD4GYAeAAABgAAAEAAAAAAAAAAAAAH/x/8f/H/x/8f/AAAAAAAAAAAAAAAAHAAB9+HAP/8eBz5w8GHDBwYcODBhwYMGDBgwcOHHA848cDx//gDH98AAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AAP/4AB8HwAPAHgB4AOAHH8cA4/44DnBzgM4DuAzAGYDMAZgMwBmA7gM4DnBzgGMGcAcABwA4AOAB4DwAD/+AAH/wAAD4AAAAAAAE4AAA/wAADbAAANsAAA2wAAD/AAAH8AAAAAAAAAAAAAAAAAAIAAADwAAAfgAADjgAA8HAADGMAAA8AAAH8AAB44AAOBwAAwDAAAAAAAAAAAAAAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAYAAABgAAAGAAAAfgAAB+AAAAAAAAAAAAAAAAAAAAA/AAAP/AABwOAAGAYAAz8wADPzAAMkMAAyYwADP7AAOYcAAcDgAA88AAB/gAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+AAAP8AABw4AAGBgAAYGAABgYAAHDgAAOcAAA/wAAA8AAAAAAAAAAAAAAAAAADBgAAMGAAAwYAADBgAAMGAAAwYAA/5gAD/mAAP+YAADBgAAMGAAAwYAADBgAAMGAAAAAAAAAAAAAAAAwMAAHBwAA4HAADA8AAMGwAAw7AADnMAAH4wAAPDAAAAAAAAAAAAgEAADAYAAMwwAA3DAADcMAAPwwAA5/AADD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///8H///wAB8AAAA4AAADgAAAGAAAAYAAABgAAAOAAABwAAAeAAf/+AB//4AAAAAAAAAAAAAAAAAAAA/gAAH/AAA/+AAH/8AAf/wAB//AAH/8AAf///x////H///8AAAAB////H///8f///wAAAAAAAAAAAAAAACAAAAcAAABwAAAGAAAAAAAAAAAAAAAAAAAAAAAAAEAAAMwAAB7AAAH8AAADgAAAAAAAAAAAAAAAAAACAAAAYAAADAAAAP/wAA//AAAAAAAAAAAAAAAAAAAAAAPAAAD+AAAMMAAAwwAADDAAAOcAAAfgAAA8AAAAAAAAAAAAAAAAADAMAAOBwAAeOAAAfwAAA8AAAxjAADwcAADngAAH4AAAPAAAAIAAAAAAAAAAAAAAAAQAAADAAAAYAAAB//AgH/8PAAAB4AAAOAAADwAAAeAAADgAAA8AAAHgAAA4AAAPAAABwBwAeAfADwPsAcD4wBgeDAABgMAAAP8AAA/wAAAMAAAAAAAAAAAAAAAAAAAAQAAADAAAAcAAAB//AgH/8PAAAB4AAAOAAADwAAAeAAADgAAA8AAAHgAAA4AAAPAAABwAAAeGAwDw4HAcHA8BgYHwABgbAAGDMAAcYwAA/DAAB4MAAAAAAAAAAIBgABgHAAGMMAAZwYABvBgAH8ODAefwcBw+HgAAA8AAAHAAAB4AAAPAAADwAAAeAAADgAAA8AAAHgHAA4D8APA+wB4PjACB4MAAGAwAAA/wAAB/AAAAwAAAAAAAAAAAAAPAAAD+AAAf8AADg4AAcDgOPgGA58AYDngBgAAAOAAAB4AAAfAAAB4AAAAAAAAAAAABAAAA8AAAfwAAP8AAH+AAD/YAB/hgAfwGAB4AYAHwBgAf4GAAP8YAAH/gAAD/AAAB/gAAA/AAAAcAAAAAAAABAAAA8AAAfwAAP8AAH+AAD/YAB/hgAfwGAB4AYAHwBgAf4GAAP8YAAH/gAAD/AAAB/gAAA/AAAAcAAAAAAAABAAAA8AAAfwAAP8AAH+AAD/YAB/hgAfwGAB4AYAHwBgAf4GAAP8YAAH/gAAD/AAAB/gAAA/AAAAcAAAAAAAABAAAA8AAAfwAAP8AAH+AAD/YAB/hgAfwGAB4AYAHwBgAf4GAAP8YAAH/gAAD/AAAB/gAAA/AAAAcAAAAAAAABAAAA8AAAfwAAP8AAH+AAD/YAB/hgAfwGAB4AYAHwBgAf4GAAP8YAAH/gAAD/AAAB/gAAA/AAAAcAAAAAAAAAAAAAAcAAAPwAAH+AAD/AAB/sHw/wwfP4DDG8AMMb4AwfP8DA4H+MAAD/wAAB/gAAA/wAAAfAAAAMAAAAAAABAAAA8AAAfwAAP8AAH+AAD/YAB/hgAfwGAB4AYAGABgAYAGAB///wH///Af//8BgMAwGAwDAYDAMBgMAwGAwDAYDAMBgMAwGAwDAYDAMBgAAwGAADAAAAAAAAAAAf/AAD/+AA/B+AHgA8AcABwDgADgOAAOAwAAYPAAB88AAH7wAAZ/gADjOAAOAcABwB4APAD4D4AHgPAAGAwAAAAAAAAAAAAAAAH///Af//8BgMAwGAwDAYDAMBgMAwGAwDAYDAMBgMAwGAwDAYDAMBgAAwGAADAAAAAAAAAAAAAAAf//8B///wGAwDAYDAMBgMAwGAwDAYDAMBgMAwGAwDAYDAMBgMAwGAADAYAAMAAAAAAAAAAAAAAB///wH///AYDAMBgMAwGAwDAYDAMBgMAwGAwDAYDAMBgMAwGAwDAYAAMBgAAwAAAAAAAAAAAAAAH///Af//8BgMAwGAwDAYDAMBgMAwGAwDAYDAMBgMAwGAwDAYDAMBgAAwGAADAAAAAAAAAAAAAAAf//8B///wH///AAAAAAAAAAAAAAAAAAAB///wH///Af//8AAAAAAAAAAAAAAAAAAAH///Af//8B///wAAAAAAAAAAAAAAAAAAAf//8B///wH///AAAAAAAAAAAAYAAABgAB///wH///AYBgMBgGAwGAYDAYBgMBgGAwGAADAYAAMBwABwHAAHAPAB4AfAfAA//4AA/+AAAfAAAAAAAAAAAAAAAAH///Af//8B8AAAB4AAAD4AAAD4AAADwAAAHwAAAHgAAAPgAAAPAAAAfAAAAeAf//8B///wAAAAAAAAAAAAAAAP/gAB//AAfg/ADwAeAOAA4BwABwHAAHAYAAMBgAAwGAADAYAAMBwABwHAAHAOAA4A8AHgB8B8AD//gAD/4AAB8AAAAAAAD/4AAf/wAH4PwA8AHgDgAOAcAAcBwABwGAADAYAAMBgAAwGAADAcAAcBwABwDgAOAPAB4AfAfAA//4AA/+AAAfAAAAAAAA/+AAH/8AB+D8APAB4A4ADgHAAHAcAAcBgAAwGAADAYAAMBgAAwHAAHAcAAcA4ADgDwAeAHwHwAP/+AAP/gAAHwAAAAAAAP/gAB//AAfg/ADwAeAOAA4BwABwHAAHAYAAMBgAAwGAADAYAAMBwABwHAAHAOAA4A8AHgB8B8AD//gAD/4AAB8AAAAAAAD/4AAf/wAH4PwA8AHgDgAOAcAAcBwABwGAADAYAAMBgAAwGAADAcAAcBwABwDgAOAPAB4AfAfAA//4AA/+AAAfAAAAAAAAAAAADgYAAHHgAAO8AAAfgAAA8AAAHwAAA/gAAHHAAA4OAABAQAAAAAAAAAAAAAAAAP/jAB//8Afg/gDwA+AOAH4BwA9wHAHnAYA8MBgHAwGA4DAYHAMBw4BwHPAHAP4A4A/AHgB8B8AP//gBz/4ACB8AAAAAAAAAAAH//wAf//gAAAPAAAAOAAAAcAAABwAAADAAAAMAAAAwAAAHAAAAcAAADgAAAeAf//wB//+AH//gAAAAAAAAAAAAAAAAAAAB//8AH//4AAADwAAADgAAAHAAAAcAAAAwAAADAAAAMAAABwAAAHAAAA4AAAHgH//8Af//gB//4AAAAAAAAAAAAAAAAAAAAf//AB//+AAAA8AAAA4AAABwAAAHAAAAMAAAAwAAADAAAAcAAABwAAAOAAAB4B///AH//4Af/+AAAAAAAAAAAAAAAAAAAAH//wAf//gAAAPAAAAOAAAAcAAABwAAADAAAAMAAAAwAAAHAAAAcAAADgAAAeAf//wB//+AH//gAAAAAAAAAAEAAAAcAAAB8AAAB8AAAD8AAAD4AAAD4AAAD/8AAf/wAHwAAB+AAAPgAAD4AAAeAAABgAAAEAAAAAAAAAAAAAH///Af//8AGAMAAYAwABgDAAGAMAAYAwABgDAAGAMAAcBwAA4OAAD/4AAH/AAAHwAAAAAAAAAAAAAAAAf//wD///APAAABwAAAGAAHAYDAMBgcAwHBwDAePgcA/+BwB/ceAAg/4AAB+AAAAAAAAAAAAAAAAAA+AAHH8AA894AHjjggcMGDhgwYPmHBgGYcGABhg4AHGHAAPb4AA//4AA//gAAAAAAAAAAAAAAAAD4AAcfwADz3gAeOOABwwYAGDBgGYcGD5hwYOGGDggcYcAA9vgAD//gAD/+AAAAAAAAAAAAAAAAAPgABx/AAPPeAZ444DnDBgcYMGDhhwYOGHBgcYYOA5xhwBj2+AAP/+AAP/4AAAAAAAAAAAAAAAAB8AAOP4AB57wHPHHAY4YMBjBgwGMODAcw4MAzDBwDOMOAce3wBB//wAB//AAAAAAAAAAAAAAAAAHwAA4/gAHnvAY8ccBzhgwGMGDAAw4MADDgwGMMHAc4w4Bx7fAAH//AAH/8AAAAAAAAAAAAAAAAAHwAA4/gAHnvAA8ccHzhgw/MGDDGw4MMbDgw/MMHB44w4AB7fAAH//AAH/8AAAAAAAAAAAAAAAAB8AAOP4AB47wAHHHAA4YMADBgwAMGDAAwYcADBhwAOGOAAebwAA/+AAD/8AAfb4ABxjgAOGHAAwYMADBgwAMGDAA4YcADhhwAHmOAAP5wAAPmAAAAAAAAAAAAP4AAD/wAAf/wADgHAAcAOABwA4MGAB8wYAH/BgAZ4HADgAeAeAA8DwABwOAACAAAAAAAAAD8AAA/8AAH/4AA5hwAHGDgwcYODxhgYDmGBgAYYGABxg4AHGHgAPY8AAfjgAA+MAAAAAAAAAAAAPwAAD/wAAf/gADmHAAcYOABxg4AGGBgOYYGDxhgYMHGDgAcYeAA9jwAB+OAAD4wAAAAAAAAAAAA/AAAP/AAB/+ACOYcA5xg4HHGDg4YYGDhhgYHGGBgOcYOAZxh4AD2PAAH44AAPjAAAAAAAAAAAAH4AAB/4AAP/wBhzDgHOMHAY4wcADDAwAMMDAAwwMBzjBwHOMPAAex4AA/HAAB8YAAAAAAAAAAOAAAA+f/+AZ//4AH//gAAAAAAAAAAAAAAAAAAAJ//4Hn//g+f/+DAAAAAAAAAMAAABwAAAOP//Aw//8Dj//wHAAAAMAAABwAAAGAAAAA//8AD//wAP//AcAAABwAAAAAAAAAA/gAAP/gAB+/AAHAcAA4A4DDABgNMAGA+wAYDzABgPOAOB+YAwG/4PAA//4AA//AAAAAAAAAAAAAAAAP//AA//8Bx8AAHGAAAY4AABjAAAHMAAAMwAAAzgAAHPAAAYfgAAA//wAA//AAAAAAAAAAAAAAAAA/AAAP/AAB/+AAOAcABwA4OHADg+YAGA5gAYAGABgAcAOABwA4ADwPAAH/4AAP/AAAHgAAAAAAAAAAAAPwAAD/wAAf/gADgHAAcAOABwA4BGABgeYAGDxgAYMHADgAcAOAA8DwAB/+AAD/wAAB4AAAAAAAAAAAAD8AAA/8AAH/4AI4BwDnADgccAODhgAYOGABgcYAGA5wA4BnADgAPA8AAf/gAA/8AAAeAAAAAAAAAAAAB+AAAf+AAD/8AccA4BzgBwGOAHAYwAMBzAAwDMADAM4AcBzgBwGHgeAAP/wAAf+AAAPAAAAAAAAAAAAAfgAAH/gAA//AGHAOAc4AcBjgBwAMADAAwAMADAAwHOAHAc4AcAB4HgAD/8AAH/gAADwAAAAAAAAAAAAMAAAAwAAADAAAAMAAAAwAAADAAADtwAAO3AAADAAAAMAAAAwAAADAAAAMAAAAAAAAAAAAAH5wAB//AAP/4ABwHgAOA/AA4PcADB4wAMODAAxwMADuBwAPwHAAfB4AB//AAP/4AAY8AAAAAAAAAAAAf8AAB//AAH//AAAA8AAAA4MAADg+AAGA4AAYAAABgAAAOAAABwAH/+AAf/+AB//4AAAAAAAAAAAAAAAH/AAAf/wAB//wAAAPAAAAOAAAA4BgABg+AAGDwAAYIAADgAAAcAB//gAH//gAf/+AAAAAAAAAAAAAAAB/wAAH/8AAf/8AIADwDgADgcAAODgAAYOAABgcAAGA4AA4BgAHAAf/4AB//4AH//gAAAAAAAAAAAAAAA/4AAD/+AAP/+AYAB4BwABwGAAHAAAAMAAAAwGAADAcAAcBwADgAP/8AA//8AD//wAAAAAAAAAABAAAAHAAAAfgAAAfgAAAfwAAAP4cIAH/zgAH++AB/DAA/gAAfwAAP8AAB+AAAHAAAAAAAAAAAAAAAAA/////////wPA8AAwAwAHADgAYAGABgAYAGABgAcAOABwA4ADwPAAH/4AAP/AAAHgAAAAAABAAAAHAAAAfgAAwfgADgfwA+AP4fAAH/8AAH+AAB/A4A/gDgfwAMP8AAB+AAAHAAAAAAAA=='),
    32,
    atob("BgkLGhAZEgYMDAwQBwwHCxELEA8REBEOEBEICREVEQ8ZEhEUExAOFBMHDREOGBMUERQSEREUERoREBELCwsTEg4QEQ8REAoREQcHDgcYEREREQoPCxEOFQ8PDwwHDBMcCgoAAAAAAAAAAAAAACERESEAAAAAAAAAAAAAAAAhIQAGCQ8QEhAHDw4WCQ8RABEODRELCw4REgYLCQoPGxobDxISEhISEhoUEBAQEAcHBwcTExQUFBQUDhQUFBQUEBEREBAQEBAQGg8QEBAQBwcHBxAREREREREPEREREREPEQ8="),
    28+(scale<<8)+(1<<16)
  );
};

function imgLock(){
  return {
    width : 16, height : 16, bpp : 1,
    transparent : 0,
    buffer : E.toArrayBuffer(atob("A8AH4A5wDDAYGBgYP/w//D/8Pnw+fD58Pnw//D/8P/w="))
  }
}

function imgSteps(){
  return {
    width : 24, height : 24, bpp : 1,
    transparent : 1,
    buffer : require("heatshrink").decompress(atob("/H///wv4CBn4CD8ACCj4IBj8f+Eeh/wjgCBngCCg/4nEH//4h/+jEP/gRBAQX+jkf/wgB//8GwP4FoICDHgICCBwIA=="))
  }
}

function imgBattery(){
  return {
    width : 24, height : 24, bpp : 1,
    transparent : 1,
    buffer : require("heatshrink").decompress(atob("/4AN4EAg4TBgd///9oEAAQv8ARQRDDQQgCEwQ4OA"))
  }
}

function imgBpm() {
  return {
    width : 24, height : 24, bpp : 1,
    transparent : 1,
    buffer : require("heatshrink").decompress(atob("/4AOn4CD/wCCjgCCv/8jF/wGYgOA5MB//BC4PDAQnjAQPnAQgANA"))
  }
}

function imgTemperature() {
  return {
    width : 24, height : 24, bpp : 1,
    transparent : 1,
    buffer : require("heatshrink").decompress(atob("//D///wICBjACBngCNkgCP/0kv/+s1//nDn/8wICEBAIOC/08v//IYJECA=="))
  }
}

function imgWind () {
  return {
    width : 24, height : 24, bpp : 1,
    transparent : 1,
    buffer : require("heatshrink").decompress(atob("/0f//8h///Pn//zAQXzwf/88B//mvGAh18gEevn/DIICB/PwgEBAQMHBAIADFwM/wEAGAP/54CD84CE+eP//wIQU/A=="))
  }
}

function imgTimer() {
  return {
    width : 24, height : 24, bpp : 1,
    transparent : 1,
    buffer : require("heatshrink").decompress(atob("/+B/4CD84CEBAPygFP+F+h/x/+P+fz5/n+HnAQNn5/wuYCBmYCC5kAAQfOgFz80As/ngHn+fD54mC/F+j/+gF/HAQA=="))
  }
}

function imgCharging() {
  return {
    width : 24, height : 24, bpp : 1,
    transparent : 1,
    buffer : require("heatshrink").decompress(atob("//+v///k///4AQPwBANgBoMxBoMb/P+h/w/kH8H4gfB+EBwfggHH4EAt4CBn4CBj4CBh4FCCIO/8EB//Agf/wEH/8Gh//x////fAQIA="))
  }
}

function imgWatch() {
  return {
    width : 24, height : 24, bpp : 1,
    transparent : 1,
    buffer : require("heatshrink").decompress(atob("/8B//+ARANB/l4//5/1/+f/n/n5+fAQnf9/P44CC8/n7/n+YOB/+fDQQgCEwQsCHBBEC"))
  }
}


/*
 * INFO ENTRIES
 * List of [Data, Icon, left/right, Function to execute]
 */
var infoArray = [
  function(){ return [ null, null, "left", null ] },
  function(){ return [ "Bangle", imgWatch(), "right", null ] },
  function(){ return [ E.getBattery() + "%", imgBattery(), "left", null ] },
  function(){ return [ getSteps(), imgSteps(), "left", null ] },
  function(){ return [ Math.round(Bangle.getHealthStatus("last").bpm) + " bpm", imgBpm(), "left", null] },
  function(){ return [ getWeather().temp, imgTemperature(), "left", null ] },
  function(){ return [ getWeather().wind, imgWind(), "left", null ] },
];

/*
 * We append the HomeAssistant integrations if HomeAssistant is available
 */
try{
  var triggers = require("ha.lib.js").getTriggers();
  triggers.forEach(trigger => {
    infoArray.push(function(){
      return [trigger.display, trigger.getIcon(), "left", function(){
        var ha = require("ha.lib.js");
        ha.sendTrigger("TRIGGER_BW");
        ha.sendTrigger(trigger.trigger);
      }]
    });
  })
} catch(ex){
  // Nothing to do if HomeAssistant is not available...
}
const NUM_INFO=infoArray.length;


function getInfoEntry(){
  if(isAlarmEnabled()){
    return [getAlarmMinutes() + " min.", imgTimer(), "left", null]
  } else if(Bangle.isCharging()){
    return [E.getBattery() + "%", imgCharging(), "left", null]
  } else{
    // In case the user removes HomeAssistant entries, showInfo
    // could be larger than infoArray.length...
    settings.showInfo = settings.showInfo % infoArray.length;
    return infoArray[settings.showInfo]();
  }
}


/*
 * Helper
 */
function getSteps() {
  var steps = 0;
  try{
      if (WIDGETS.wpedom !== undefined) {
          steps = WIDGETS.wpedom.getSteps();
      } else if (WIDGETS.activepedom !== undefined) {
          steps = WIDGETS.activepedom.getSteps();
      } else {
        steps = Bangle.getHealthStatus("day").steps;
      }
  } catch(ex) {
      // In case we failed, we can only show 0 steps.
  }

  steps = Math.round(steps/100) / 10; // This ensures that we do not show e.g. 15.0k and 15k instead
  return steps + "k";
}


function getWeather(){
  var weatherJson;

  try {
    weatherJson = storage.readJSON('weather.json');
    var weather = weatherJson.weather;

    // Temperature
    weather.temp = locale.temp(weather.temp-273.15);

    // Humidity
    weather.hum = weather.hum + "%";

    // Wind
    const wind = locale.speed(weather.wind).match(/^(\D*\d*)(.*)$/);
    weather.wind = Math.round(wind[1]) + " km/h";

    return weather

  } catch(ex) {
    // Return default
  }

  return {
    temp: "? °C",
    hum: "-",
    txt: "-",
    wind: "? km/h",
    wdir: "-",
    wrose: "-"
  };
}

function isAlarmEnabled(){
  try{
    var alarm = require('sched');
    var alarmObj = alarm.getAlarm(TIMER_IDX);
    if(alarmObj===undefined || !alarmObj.on){
      return false;
    }

    return true;

  } catch(ex){ }
  return false;
}

function getAlarmMinutes(){
  if(!isAlarmEnabled()){
    return -1;
  }

  var alarm = require('sched');
  var alarmObj =  alarm.getAlarm(TIMER_IDX);
  return Math.round(alarm.getTimeToAlarm(alarmObj)/(60*1000));
}

function increaseAlarm(){
  try{
    var minutes = isAlarmEnabled() ? getAlarmMinutes() : 0;
    var alarm = require('sched')
    alarm.setAlarm(TIMER_IDX, {
      timer : (minutes+5)*60*1000,
    });
    alarm.reload();
  } catch(ex){ }
}

function decreaseAlarm(){
  try{
    var minutes = getAlarmMinutes();
    minutes -= 5;

    var alarm = require('sched')
    alarm.setAlarm(TIMER_IDX, undefined);

    if(minutes > 0){
      alarm.setAlarm(TIMER_IDX, {
        timer : minutes*60*1000,
      });
    }

    alarm.reload();
  } catch(ex){ }
}


/*
 * DRAW functions
 */

function draw() {
  // Queue draw again
  queueDraw();

  // Draw clock
  drawDate();
  drawTime();
  drawLock();
  drawWidgets();
}


function drawDate(){
    // Draw background
    var y = H/5*2;
    g.reset().clearRect(0,0,W,W);

    // Draw date
    y = parseInt(y/2);
    y += settings.fullscreen ? 2 : 15;
    var date = new Date();
    var dateStr = date.getDate();
    dateStr = ("0" + dateStr).substr(-2);
    g.setMediumFont();  // Needed to compute the width correctly
    var dateW = g.stringWidth(dateStr);

    g.setSmallFont();
    var dayStr = locale.dow(date, true);
    var monthStr = locale.month(date, 1);
    var dayW = Math.max(g.stringWidth(dayStr), g.stringWidth(monthStr));
    var fullDateW = dateW + 10 + dayW;

    g.setFontAlign(-1,0);
    g.setMediumFont();
    g.setColor(g.theme.fg);
    g.drawString(dateStr, W/2 - fullDateW / 2, y+1);

    g.setSmallFont();
    g.drawString(dayStr, W/2 - fullDateW/2 + 10 + dateW, y-12);
    g.drawString(monthStr, W/2 - fullDateW/2 + 10 + dateW, y+11);
}


function drawTime(){
  // Draw background
  var y = H/5*2 + (settings.fullscreen ? 0 : 8);
  g.setColor(g.theme.fg);
  g.fillRect(0,y,W,H);
  var date = new Date();

  // Draw time
  g.setColor(g.theme.bg);
  g.setFontAlign(0,0);

  var hours = String(date.getHours());
  var minutes = date.getMinutes();
  minutes = minutes < 10 ? String("0") + minutes : minutes;
  var colon = settings.hideColon ? "" : ":";
  var timeStr = hours + colon + minutes;

  // Set y coordinates correctly
  y += parseInt((H - y)/2) + 5;

  var infoEntry = getInfoEntry();
  var infoStr = infoEntry[0];
  var infoImg = infoEntry[1];
  var printImgLeft = infoEntry[2] == "left";

  // Show large or small time depending on info entry
  if(infoStr == null){
    if(settings.hideColon){
      g.setXLargeFont();
    } else {
      g.setLargeFont();
    }
  } else {
    y -= 15;
    g.setMediumFont();
  }
  g.drawString(timeStr, W/2, y);

  // Draw info if set
  if(infoStr == null){
    return;
  }

  y += 35;
  g.setFontAlign(0,0);
  g.setSmallFont();
  var imgWidth = 0;
  if(infoImg !== undefined){
    imgWidth = 26.0;
    var strWidth = g.stringWidth(infoStr);
    var scale = imgWidth / infoImg.width;
    g.drawImage(
      infoImg,
      W/2 + (printImgLeft ? -strWidth/2-2 : strWidth/2+2) - parseInt(imgWidth/2),
      y - parseInt(imgWidth/2),
      { scale: scale }
    );
  }
  g.drawString(infoStr, printImgLeft ? W/2 + imgWidth/2 + 2 : W/2 - imgWidth/2 - 2, y+3);
}


function drawLock(){
  if(settings.showLock && Bangle.isLocked()){
    g.setColor(g.theme.fg);
    g.drawImage(imgLock(), W-16, 2);
  }
}


function drawWidgets(){
  if(settings.fullscreen){
    for (let wd of WIDGETS) {wd.draw=()=>{};wd.area="";}
  } else {
    Bangle.drawWidgets();
  }
}



/*
 * Draw timeout
 */
// timeout used to update every minute
var drawTimeout;

// schedule a draw for the next minute
function queueDraw() {
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = setTimeout(function() {
    drawTimeout = undefined;
    draw();
  }, 60000 - (Date.now() % 60000));
}


// Stop updates when LCD is off, restart when on
Bangle.on('lcdPower',on=>{
  if (on) {
    draw(); // draw immediately, queue redraw
  } else { // stop draw timer
    if (drawTimeout) clearTimeout(drawTimeout);
    drawTimeout = undefined;
  }
});

Bangle.on('lock', function(isLocked) {
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = undefined;
  draw();
});

Bangle.on('charging',function(charging) {
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = undefined;
  draw();
});

Bangle.on('touch', function(btn, e){
  var left = parseInt(g.getWidth() * 0.3);
  var right = g.getWidth() - left;
  var upper = parseInt(g.getHeight() * 0.3);
  var lower = g.getHeight() - upper;

  var is_left = e.x < left;
  var is_right = e.x > right;
  var is_upper = e.y < upper;
  var is_lower = e.y > lower;
  var is_center = !is_upper && !is_lower && !is_left && !is_right;

  if(is_upper){
    Bangle.buzz(40, 0.6);
    increaseAlarm();
    drawTime();
  }

  if(is_lower){
    Bangle.buzz(40, 0.6);
    decreaseAlarm();
    drawTime();
  }

  if(is_right){
    Bangle.buzz(40, 0.6);
    settings.showInfo = (settings.showInfo+1) % NUM_INFO;
    drawTime();
  }

  if(is_left){
    Bangle.buzz(40, 0.6);
    settings.showInfo = settings.showInfo-1;
    settings.showInfo = settings.showInfo < 0 ? NUM_INFO-1 : settings.showInfo;
    drawTime();
  }

  if(is_center){
    var infoEntry = getInfoEntry();
    var fun = infoEntry[3];
    if(fun != null){
      Bangle.buzz(80, 0.6).then(()=>{
        try{
          fun();
          setTimeout(()=>{
            Bangle.buzz(80, 0.6);
          }, 250);
        } catch(ex){
          // In case it fails, we simply ignore it.
        }
      }
      );
    }
  }
});


E.on("kill", function(){
  try{
    storage.write(SETTINGS_FILE, settings);
  } catch(ex){
    // If this fails, we still kill the app...
  }
});


/*
 * Draw clock the first time
 */
// The upper part is inverse i.e. light if dark and dark if light theme
// is enabled. In order to draw the widgets correctly, we invert the
// dark/light theme as well as the colors.
g.setTheme({bg:g.theme.fg,fg:g.theme.bg, dark:!g.theme.dark}).clear();

// Load widgets and draw clock the first time
Bangle.loadWidgets();
draw();

// Show launcher when middle button pressed
Bangle.setUI("clock");
