/* 

Based on LECO 1976 with a small variation on really small numbers (removed serifs for better legibility)

Usage:

```
require("FontLECO1976Regular.js").add14(Graphics);
g.setFontLECO1976Regular14();
g.drawString("0123456789");
```
*/
exports.add42 = function (graphics) {
  graphics.prototype.setFontLECO1976Regular42 = function (scale) {
    // Actual height 42 (41 - 0)
    g.setFontCustom(
      atob(
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAA/AAAAAAAAH/AAAAAAAA//AAAAAAAP//AAAAAAB///AAAAAAP///AAAAAB////AAAAAf////AAAAD////4AAAAf////AAAAH////4AAAA////+AAAAA////wAAAAA///+AAAAAA///gAAAAAA//8AAAAAAA//gAAAAAAA/4AAAAAAAA/AAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAH/AAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//h////AAA//h////AAA//h////AAA//h////AAA//h////AAA//h////AAA//h////AAA//h////AAA//h////AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA////gD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4AAAH/AAA/4B/gH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////wAAAAA////wAAAAA////wAAAAA////wAAAAA////wAAAAA////wAAAAA////wAAAAA////wAAAAA////wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////x//AAA////x//AAA////x//AAA////x//AAA////x//AAA////x//AAA////x//AAA////x//AAA////x//AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B////AAA/4B////AAA/4B////AAA/4B////AAA/4B////AAA/4B////AAA/4B////AAA/4B////AAA/wB////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B////AAA/4B////AAA/4B////AAA/4B////AAA/4B////AAA/4B////AAA/4B////AAA/4B////AAA/wB////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAAAA//gAAAAAAA//gAAAAAAA//gAAAAAAA//gAAAAAAA//gAAAAAAA//gAAAAAAA//gAAAAAAA//gAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA////wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA/4B/wH/AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAA///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAH/AAAAP+AAH/AAAAP+AAH/AAAAP+AAH/AAAAP+AAH/AAAAP+AAH/AAAAP+AAH/AAAAP+AAH/AAAAH+AAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      ),
      46,
      atob("ERkmHyYmJiYmJCYmEQ=="),
      60 + (scale << 8) + (1 << 16)
    );
  };
};

exports.add20 = function (graphics) {
  graphics.prototype.setFontLECO1976Regular20 = function (scale) {
    // Actual height 20 (19 - 0)
    g.setFontCustom(
      atob(
        "AAAAAAAAAAAAAAAAAAAAAAAP/cD/3A/9wAAAAAAAAAAPwAD8AA/AAAAAD8AA/AAPwAAAAAAAAAAAAc4A//wP/8D//AHOABzgAc4A//wP/8D//AHOAAAAAAAAH+OB/jgf44/OP/zj/84//OPxz/gc/4HP+AAAAAAAAAAP8AD/BAwwwMM8D/fA//AAPgAHgAHwAD/8B//A8wwMMMCD/AA/wAP8AAAAAAAP/8D//A//wOccDnHA5xwOccDn/A5/wOf8AHAABwAAAAD8AA/AAPwAAAAAAAAAAAAA8AB/4D//z/D//AP+AAcAAAAAAMAAP4Af/w/3//4P/wAfgAAAAAAAZgAH4AA8AA/wAP8AA8AAfgAGYAAAAAAAAAAAAHAABwAAcAAf4AH+AB/gAHAABwAAcAAAAAAAAAAfgAH4AB+AAAAAAAAAAAcAAHAABwAAcAAHAABwAAAAAAAAABwAAcAAHAAAAAAAAADAAHwAf8A/+A/8APwADgAAAAAAAAD//A//wP/8DgHA4BwOAcDgHA//wP/8D//AAAAAAAAAAA4BwOAcDgHA//wP/8D//AABwAAcAAHAAAAPP8Dz/A8/wOOcDjnA45wOOcD/nA/5wP+cAAAAAAAAAADgHA5xwOccDnHA5xwOccDnHA//wP/8D//AAAAAAAAAAA/wAP8AD/AABwAAcAAHAABwAP/8D//A//wAAAAAAAAAAP98D/fA/3wOccDnHA5xwOccDn/A5/wOf8AAAAAAAAAAD//A//wP/8DnHA5xwOccDnHA5/wOf8Dn/AAAAAAADwAA8AAPAADgAA4AAOAADgAA//wP/8D//AAAAAAAAAAA//wP/8D//A5xwOccDnHA5xwP/8D//A//wAAAAAAAAAAP8cD/HA/xwOccDnHA5xwOccD//A//wP/8AAAAAAAAAAAcHAHBwBwcAAAAAAAAAAAcH4HB+BwfgAAAAAAAMAAHgAB4AA/AAPwAH+ABzgA88AOHAAAAAAAAHOABzgAc4AHOABzgAc4AHOABzgAYYAAAAAAAA4cAPPABzgAf4AD8AA/AAHgAB4AAMAAAAA8AAPAADwAA49wOPcDj3A44AP+AD/gA/4AAAAAAAAAAAP//j//4//+OADjv+47/uO/7juO4//uP/7j/+4AAAAAAAAAA//wP/8D//A5wAOcADnAA5wAP/8D//A//wAAAAAAAAAAP/8D//A//wOccDnHA5xwOccD//A//wP38AAAAAAAAAAD//A//wP/8DgHA4BwOAcDgHA4BwOAcDgHAAAAAAAAAAA//wP/8D//A4BwOAcDgHA8DwP/8B/+AP/AAAAAAAAAAAP/8D//A//wOccDnHA5xwOccDnHA5xwOAcAAAAAAAAAAD//A//wP/8DnAA5wAOcADnAA5wAOcADgAAAAAAAAD//A//wP/8DgHA5xwOccDnHA5/wOf8Dn/AAAAAAAAAAA//wP/8D//ABwAAcAAHAABwAP/8D//A//wAAAAAAAAAAP/8D//A//wAAAAAAAAAAOAcDgHA4BwOAcDgHA4BwP/8D//A//wAAAAAAAAAAP/8D//A//wA8AAfAAPwAP8AD3/A5/wMf8AAAAAAAAAAD//A//wP/8AAHAABwAAcAAHAABwAAcAAAA//wP/8D//A/wAB/gAD/AAPwAB8AD/AD/AH+AD//A//wP/8AAAAAAAAAAD//A//wP/8D+AAP4AA/AAD8AAPwP/8D//A//wAAAAAAA//wP/8D//A4BwOAcDgHA4BwP/8D//A//wAAAAAAAAAAP/8D//A//wOcADnAA5wAOcAD/AA/wAP8AAAAAAAAP/8D//A//wOAcDgHA4BwOAcD//4//+P//gAA4AAOAAAD//A//wP/8DjwA4+AOPwDj/A/7wP+cD/jAAAAAAAAAAA/xwP8cD/HA5xwOccDnHA5xwOf8Dn/A5/wAAAAAAAwAAOAADgAA4AAP/8D//A//wOAADgAA4AAOAAAAAA//wP/8D//AABwAAcAAHAABwP/8D//A//wAAAAAAA4AAPwAD/gAP/AAf8AA/AAfwA/8B/4A/wAPgADAAAAAAPAAD/AA//AB/8AB/AAfwB/8D/8A/wAP+AD/+AD/wAD8AD/Af/wP/gD+AA4AAMAMDgHA+HwPz8A/8AH+AB/gA/8A/PwPh8DgHAwAwAAAAAAA/wAP8AD/AAB/wAf8AH/AB/wP8AD/AA/wAAAAAAAAAAAOf8Dn/A5/wOccDnHA5xwOccD/HA/xwP8cAAAAAAAAAAD//////////gAH4AB+AAcAAAwAAPgAD/gAf/AA/8AA/AABwAAADgAH4AB+AAf/////////8AAAAAA="
      ),
      32,
      atob(
        "BgYKDQ0SDQYICAsLBggGCA0KDQ0NDQ0MDQ0GBgoLCg0ODQ0NDQ0MDQ0GDA0KEQ0NDA0NDQsNDRINDQ0ICAg="
      ),
      20 + (scale << 8) + (1 << 16)
    );
  };
};

exports.add14 = function (graphics) {
  graphics.prototype.setFontLECO1976Regular14 = function (scale) {
    // Actual height 14 (13 - 0)
    this.setFontCustom(
      atob(
        "AAAAAAAAAAAD+w/sAAAAA8APAAAA8APAAAAMwP/D/wMwDMD/w/8DMAAAAAD8w/M8z/M/zPM/DPwAAAAPwD8QzcP/D/AHgD/D/wzMI/APwAAAAD/w/8MzDMwzMM/DPwDAAADwA8AAAAAAD8H/74f4BwAAAA4B/z8/8D8AAAAAeAPwD8AeAHgAAAAAAAAYAGAH4B+AGABgAAAAAAHgB4AAAAAYAGABgAYAAAAAABgAYAAAAQA8D/D+A8AAAAAA/8P/DAwwMMDD/w/8AAAAAwMMDD/w/8ADAAwAAO/DvwzMMzDMw/MPzAAAAAMDDMwzMMzDMw/8P/AAAAAPwD8ADAAwAMA/8P/AAAAAP3D9wzMMzDMwz8M/AAAAAP/D/wzMMzDMwz8M/AAA4AOADAAwAMAD/w/8AAAAA/8P/DMwzMMzD/w/8AAAAA/MPzDMwzMMzD/w/8AAAAAYYGGAAAAAGHhh4AABwAcAPgDYB3AYwAAAAAZgGYBmAZgGYBmAAAAABjAdwDYA+AHABwAAA4AOADOwzsMwD8A/AAAAAA//P/zAM37N+zZs/7P+wAAAAP/D/wzAMwDMA/8P/AAAAAP/D/wzMMzDMw/8P/AAAAAP/D/wwMMDDAwwMMDAAAAAP/D/wwMMDDhw/8H+AAAAAP/D/wzMMzDMwzMMDAAAAAP/D/wzAMwDMAzAMAAAA/8P/DAwzMMzDPwz8AAAAA/8P/AMADAAwD/w/8AAAAA/8P/AAAwMMDDAwwMMDD/w/8AAAAA/8P/AcAPAPwDvwj8AAAAA/8P/AAwAMADAAwAAP/D/w/AB+AHwA8B+B+A/8P/AAA/8P/D/wfAB8AHw/8P/AAAAAP/D/wwMMDDAw/8P/AAAAAP/D/wzAMwDMA/APwAAA/8P/DAwwMMDD/8//AAwAA/8P/DOAzwM/D9w/EAAAAA/MPzDMwzMMzDPwz8AADAAwAMAD/w/8MADAAwAAAD/w/8ADAAwAMP/D/wAAPAD8AP4AfAHwP4PwDgAAAPgD/gH8AfB/w/AP4A/wA8D/D/A8AAADAw4cP/A/APwH+DzwwMAAAAA/APwAPwD8A/D8A/AAAAAAz8M/DMwzMMzD8w/MAAAAA/////ADwA4ADwA/wB/ADwAAMAPAD////8A"
      ),
      32,
      atob(
        "BAQHCQkNCQQGBggIBAYEBgkHCQkJCQkICQkEBAcIBwkKCQkJCQkICQkECAkHDAkJCAkJCQgJCQ0JCQkFBgU="
      ),
      14 + (scale << 8) + (1 << 16)
    );
  };
};

exports.add12 = function (graphics) {
  graphics.prototype.setFontLECO1976Regular12 = function (scale) {
    // Actual height 12 (11 - 0)
    this.setFontCustom(
      atob(
        "AAAAAAAAAA/4/48A8A8A8A8AAAAA/4/4Ng/4/4/4AAAAP2P28383M+M+AAAA/AzY/4/wHAf4/4yYD4AAAA/4/4zYzYz4z4DAAA8A8AAADwf++fwDwD+ff+DwAAAAUAcA+AcAUAAAGAGAfAfAGAGAAAAAA8A8AAGAGAGAAAAwAwAAA4P4/g4AAAAA/4/4wYwY/4/4AAwYwY/4/4AYAYAA34342Y2Y+Y+YAAAAwYzYzYzY/4/4AAAA+A+AGAGA/4/4AAAA/Y/YzYzYz4z4AAAA/4/4zYzYz4z4AA4A4AwAwA/4/4AAAA/4/4zYzY/4/4AAAA/Y/YzYzY/4/4AAYwYwAAAAY8Y8GAPAPAfgZgAAAAbAbAbAbAbAAAAAZgfgPAPAGAAA4A4A3Y3Y+A+AAA/+/+wG3232/2/2AAAA/4/42A2A/4/4AAAA/4/4zYzY/4/4AAAA/4/4wYwYwYwYAAAA/4/4wYwY/4fwAAAA/4/4zYzYzYwYAAAA/4/42A2A2AwAAA/4/4zYzYz4z4AAAA/4/4GAGA/4/4AAAA/4/4wYwYwYwY/4/4AAAA/4/4OAeA/4n4AAAA/4/4AYAYAYAA/4/4PgB4B4Pw/4/4AAAA/4/4fAHw/4/4AAAA/4/4wYwY/4/4AAAA/4/42A2A+A+AAA/8/8wcwc/+/+AGAA/4/43g3w+4+YAAAA/Y/YzYzYz4z4AAwAwA/4/4wAwAAAAA/4/4AYAY/4/4AA8A/gH4B4Pw+AwAAA+A/4B4P4/A/gP4D4/4+AgAwY44fwPgfw44wYAAAA+A+AH4H4+A+AAAAAz4z4zYzY/Y/YAAAA////wDwD4A/gP4A4AAQBwD////AA"
      ),
      32,
      atob(
        "BAMGCAgLCAMFBQcHAwUDBQgGCAgICAgHCAgDAwYHBggICAgICAgHCAgDBwgGCggIBwgICAcICAsICAgFBQU="
      ),
      12 + (scale << 8) + (1 << 16)
    );
    return this;
  };
};

exports.add11 = function (graphics) {
  graphics.prototype.setFontLECO1976Regular11 = function (scale) {
    // Actual height 11 (10 - 0)
    this.setFontCustom(
      atob(
        "AAAAAAAP8fI4BwDgHAAAAA/x/hmH+P8AAAAfb+/tzfG+AAAD4EWP8HgPB/jRA+AAAA/x/jbG+N8DA4BwAAAAB8P+4PAHAf3z+AgAAoBwHwHAKAAAAAwDwHgGAEADwHgAAAGAMAYAAAAAYAQAwfj8HAAAAA/x/jDH+P8AAABhj/H+AMAIABvjfG2PsfYAAADbG2Nsf4/wAD4HwBgDA/x/gAAAPsfY2xvjfAAAAf4/xtjfG+AAcAwBgD/H+P8AAAB/j/G2P8f4AAAD7H2Nsf4/wAAADMEIMcY4AAwDwHgfgzAAAADYGwNgbA2AAGYPwPAeAYAAHANsb4+B8AAAAP/f+/9/7/3/gAAA/x/jYH+P8AAAB/j/G2P8f4AAAD/H+MMYYwwAAAH+P8YY/w/AAAAP8f42xtjTAAAAf4/xsDYGgAAAA/x/jbG+N8AA/x/gYAwP8f4AB/j/AAAAYYwxhj/H+AAf4/wcD4G+J8AA/x/gDAGAMAAAB/j/B8A8B4fB/j/H+P8PAHh/j/AAAAf4/xhj/H+AAAA/x/jYHwPgAAAB/z/mHP/f+AN/j/G4N8fY+QAAAH2PsbY3xvgAGAMAf4/xgDAH+P8AYAx/j/AAPAfwDwPj8HAAAfAfwHj/HwP8B4fx8CAECOcPwPA/DnECPgfAHwPj4HwAAAA3xvjbH2PsAA////AcAcAfgPwDgAGA////AA=="
      ),
      32,
      atob(
        "AwMFBwcKBwMFBQYGAwUDBQcGBwcHBwcHBwcDAwYGBgcIBwcHBwcHBwcDBwcGCQcHBwcHBwYHBwoHBwcEBQQ="
      ),
      11 + (scale << 8) + (1 << 16)
    );
    return this;
  };
};

exports.add8 = function (graphics) {
  graphics.prototype.setFontLECO1976Regular8 = function (scale) {
    // Actual height 8 (7 - 0)
    this.setFontCustom(
      atob(
        "AAAA9PzAwMDASPxI/EhyctNeXvD0/Dj8pDz8/KS8vMDACH/jwf8cYPDwYBA4OBAHBxAQEAQEDHzg/PyE/PyE/PwEnJyU9PSEpKT8/ODgIPz85OSkvLz8/KS8vMDAgPwA/Pyk/Pzk5KT8/CQkIycwMHhIKCgoKEh4MDDA1LTw8P//vb39APz8oPz8/Pyk/Nz8/ISEhPz8hPx4/PykpIT8/KCggPz8pLy8/Pwg/Pz8/ISEhPwA/Pxg/Lz8/AQE/Px8HHj8APz8cPz8/PyE/Pz8/KDg4P7+hv///Py4/OTk5KS8vID8/ID8/AT8/MD4HPjA4Px88Pw88IT8ePyE4OA84OC8vKTk5P//gcD4HIH//w=="
      ),
      32,
      atob(
        "AwIEBQUHBQIDAwQEAgMCAwUEBQUFBQUFBQUCAgQEBAUGBQUFBQUFBQUCBQUEBwUFBQUFBQQFBQcFBQUDAwM="
      ),
      8 + (scale << 8) + (1 << 16)
    );
    return this;
  };
};
