
//Initialize Bold Font
Graphics.prototype.setFontBold = function(scale) {
  // Actual height 69 (68 - 0)
  g.setFontCustom(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAfA/////D+D////8f8P////x/w/////H/D////8f4P////w/gYAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/gAAAAAP//wAAAA///AAAAD//8AAAAP//wAAAA///AAAAB//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//8AAAAP//wAAAA///AAAAD//8AAAAP//wAAAA///AAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAD4DwAAAAPgPAAAAA+A8AAAAD4Dx8AAAPj//wAAH////AAP////8AA/////wAD/////AAP///4AAA//wPAAABg+A8AAAAD4DwAAAAPgPAAAAA+A8AAAAD4H/8AAAP///wAD/////AAP////8AA/////wAD////wAAP//jwAAA/PgPAAAAA+A8AAAAD4DwAAAAPgPAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAMAAP/AAPwAB/+AA/gAP/8AB+AB//4AH4AH//wAfgAf//gA+AD8H+AD4APwP8AP/f+AfwA/9/4B/gD/3/gD+AP/f+AP8A/9/4Af4D4APgA/gfgA+AD/j+AD8AH//4APwAf//AAfgA//8AB+AB//gAHAAD/8AAAAAD/AAAAAABgAAAAAAAAAAAAAAAAAAEAAAAAAH/gAAAAB//AAAAAP/+AAAAB//8AAAAH//4AAAA/h/gAAAD4A+AAAAPAB8AAAB8AHwAAAHwAeAAAAPgD4AAAA/w/gAcAD//8AHwAH//wB/AAf/+A/8AA//wP/wAA/8H//AAAEB//gAAAAf/4AAAAP/8AAAAD//AAAAB//wAAAAf/4AAAAH/+AAAAD//A/gAAf/wf/gAB/8D//gAH+Af//AAfgB//8ABwAP//4AEAA/AfgAAAD4A+AAAAfAD4AAAB8APgAAAH4A+AAAAfwH4AAAA///AAAAD//8AAAAH//gAAAAP/8AAAAAf/gAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAAAAAP/AAAAAB/+AAA/AP/8AAP/h//4AB//v//gAP///j/AA///8D8AH///gHwAfh/8AfAB8B/4B8AHwB/4H4A+AH/wPgD8Af/g+AHwD//n4Afg/v/fgB//+P/8AH//wf/wAP/+A//AAf/wB/8AA/+AB/gAA/gAH+AAAABx/8AAAAH//wAAAAf//gAAAB//+AAAAH/z4AAAAf+PgAAAAAA+AAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///AAAAD//8AAAAP//wAAAA///AAAAD//8AAAAP//wAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAH///wAAD////wAA/////wAH/////wB//////gP/8AB//D/8AAA//f+AAAAf9/gAAAAf/8AAAAAffAAAAAA94AAAAABzAAAAAADAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAN4AAAAAB34AAAAAPfwAAAAB9/wAAAAfz/wAAAH/H/wAAD/8P/8AD//gf/////4Af/////AA/////wAA////8AAAf//+AAAAH//AAAAAAAAAAAAAAAAAAAAAAAAAAHA4AAAAB8HwAAAAH4fgAAAAfj+AAAAA/PwAAAAD9+AAAAAH/4AAAAAP/AAAABw/4AAAAH///4AAAf///gAAB///+AAAH///4AAAf///gAAAA/4AAAAAH/wAAAAAffgAAAAD9+AAAAAfz8AAAAB+P4AAAAPwfgAAAAPB8AAAAAIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAf///AAAB///8AAAH///wAAAf///AAAB///8AAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAB4B4AAAAPwPgAAAA//+AAAAH//4AAAAf//AAAAA//4AAAAB/+AAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAfwAAAAAD/gAAAAAP+AAAAAA/4AAAAAD/AAAAAAH8AAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAH4AAAAAH/gAAAAD/+AAAAD//4AAAB///gAAA///wAAA///4AAAf//4AAAf//8AAAP//8AAAP//+AAAH///AAAA///AAAAD//gAAAAP/gAAAAA/wAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAf//4AAAH///4AAA////wAAP////gAB/////AAH////+AA/8AB/8AD+AAB/wAfwAAB/AB+AAAD8AH4AAAP4AfgAAA/gD+AAAD+AH4AAAPwAfgAAA/AB/AAAH8AH/AAA/wAf/AAf+AA/////4AB/////AAH////4AAH///+AAAP///wAAAP//8AAAAD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAAAAD4AAAAAAPgAAAAAA+AAAAAAH4AAAAAAfAAAAAAD/////wAf/////AB/////8AH/////wAf/////AB/////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAPAAPgAAB8AB+AAAPwAH4AAA/AA/AAAH8AD8AAA/wAfgAAH/AB+AAA/8AHwAAH/wAfAAA//AB8AAP/8AH4AB/3wAfgAP+fAB/AD/x8AH+A/+HwAf///wfAA///+B8AD///wHwAH//8AfAAP//gB8AAf/4AHwAAP8AAfAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAHgAAAPAAfAAAA8AD8AAAD4APgAAAPgB+APAA+AH4A+AD4AfAD4APgB8AfgA+AHwB+AH4AfAP4AfAB8A/gB8AH4H+APwAfx/8A/AB///wH4AD/////gAP////8AAf/z//wAA/8P/+AAB/gf/wAAAAA/+AAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAP8AAAAAD/wAAAAA//AAAAAP/8AAAAH//wAAAB///AAAAf//8AAAP//PwAAD//w/AAA//8D8AAP//APwAA//wA/AAD/8AD8AAH+AAPwAAfgAA/AAA4B///8AAAH///wAAAf///AAAB///8AAAH///wAAAf///AAAAAD8AAAAAAPwAAAAAA/AAAAAAD8AAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/4AD4Af//wAPgB///AA+AH//4AD4Af//gAPgB//+AB+AH4D4AH4AfgPgAfAB+A+AD8AH4H4APwAfgfgB/AB+A+AH4AH4D8A/gAfgP4P8AB+A///wAH4B//+AAfgH//wAB+AP/+AAH4Af/wAAcAA/+AAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AAAAAP/+AAAAD//+AAAA///8AAAP///4AAB////wAAP////AAB/8AP+AAP/gAP4AB/3gAfgAH8fAA/AA/j8AB8AH8PgAHwAfg+AAfAD8D4AD8APwPwAPgB+A/AB+AH4D+Af4AfAP///AB8Af//8ADgB///gAAAD//8AAAAH//gAAAAP/4AAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAAAAAfgAAAAAB+AAAAAAH4AAAAAAfgAAABAB+AAAA8AH4AAAPwAfgAAD/AB+AAA/8AH4AAf/wAfgAH//AB+AD//8AH4A//+AAfgf//AAB+H//wAAH7//4AAAf//8AAAB///AAAAH//gAAAAf/wAAAAB/4AAAAAH+AAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAf8AAA/wH/4AAP/g//wAB//H//gAP/+f/+AA/////8AH///wPwAfg/+AfAB8B/wB8AHwD+AHwAfAP4APgD4AfwA+APwB/AD4AfAH+AfgB8A/4B+AH4P/wHwAf///g/AA/////8AD//n//gAH/8P/+AAP/g//wAAf4A/+AAAAAB/wAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+AAAAAP/+AAAAD//8ABAAf//4APAB///gA+AP///AD4A/wf8AfgH8AfwD8AfgA/gPwB8AB+B+AHwAH4P4AfAAfB/AD8AB8P4AHwAHx/gAfAA/f8AB+AA7/gAH+AB/8AAP/9//gAA////8AAB////gAAD///8AAAH///AAAAP//wAAAAH/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAPgAAB/AB/AAAH+AP+AAA/4A/4AAD/gD/gAAP+AP8AAAfwAfwAAA+AA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAOAMAH8AB4B4Af4AP4fwD/gB//+AP+AH//4A/4AP//AB/AA//wAD4AA/+AAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAB+AAAAAAH8AAAAAA/wAAAAAD/gAAAAAf+AAAAAB/8AAAAAP/wAAAAA/fgAAAAD9+AAAAAfj8AAAAB+PwAAAAPw/gAAAA/B+AAAAH4H8AAAAfgPwAAAD8A/AAAAPwB+AAAB/AH4AAAH4AfwAAA/gA/AAAD8AD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAP4AAA/gA/AAAB+AH8AAAH8AfgAAAPwB+AAAA/APwAAAB+A/AAAAH4H8AAAAPwfgAAAA/D+AAAAB+PwAAAAH4/AAAAAP34AAAAA/fgAAAAD/8AAAAAH/wAAAAAf+AAAAAA/4AAAAAD/AAAAAAH8AAAAAAfgAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAfAAAAAAD8AAAAAAPwAAAAAA+AAD8AAD4AAf8AwPwAD/4Pw/AAf/h/D8AD/+H+PwAf/4/4/gB/jj/j+AP4AH8H8B/AAfgf8f4AAIB///gAAAD//8AAAAH//gAAAAP/8AAAAAf/gAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/8AAAAP//+AAAD///+AAA////+AAH////8AA//AD/4AH/AAB/wA/wAAB/gH8AAAD+A/gAfgH8H8Af/gPwfgH//gfj8B///A+PgP//+D5+B///4PnwP+A/gfeA/gA+B/4H4AD4H/gfAAfgf+D8AD+B/wPgAfwH/A+AD+Af8D4A/wB/wPgP+AH/A/H/+Ae8D///+B74H///4Pvgf///g++B///+D74H/+D4fHwf4APgcfB4AB+AB+AAAPwAD8AAB/AAP4AAf4AAf8AP/AAA////4AAB////AAAD///4AAAD//+AAAAD//AAAAAAAAAAAAAAAADwAAAAAB/AAAAAAf8AAAAAP/wAAAAH//AAAAB//8AAAA///gAAAf//wAAAH//4AAAD///AAAB///8AAAf//nwAAH//wfAAAf/4B8AAB/8AHwAAH+AAfAAAf/AB8AAB//gHwAAH//wfAAAH//58AAAD///wAAAB///AAAAB///AAAAA///gAAAAf//wAAAAf//AAAAAP/8AAAAAH/wAAAAAH/AAAAAAD8AAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////+AHwA+AH4AfAD4AfgB8APgB+AHwA+AD4AfAD4APgB8APgA+AHwB+AH4AfAH4AfAB+AfgB8AH8H/AHwAf//8A/AA///4H8AD/////gAH////+AAP/z//4AAf8P//AAAeAP/4AAAAAf/AAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAP//wAAAD///wAAA////gAAH////AAA////+AAD/4D/8AAf8AB/4AD/AAB/gAP4AAD+AA/AAAH8AH4AAAPwAfgAAA/AB+AAAB8AHwAAAH4AfAAAAfgB8AAAB+AHwAAAH4AfAAAAfgB8AAAB8AH4AAAHwAfgAAA/AB+AAAD8AH8AAAPwAPwAAB+AAwAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////8AH/////wAf/////AB/////8AH/////wAf/////AB8AAAB+AHwAAAH4AfAAAAfgB8AAAB+AHwAAAH4AfAAAAfgB8AAAB+AHwAAAHwAfAAAAfAB+AAAD8AH4AAAPwAfwAAB/AA/gAAP4AD/AAD/gAH/gA/8AAf////gAA////+AAB////wAAD///8AAAH///gAAAH//wAAAAD/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////8AH/////wAf/////AB/////8AH/////wAf/////AB8AfgB8AHwB+AHwAfAH4AfAB8AfgB8AHwB+AHwAfAH4AfAB8AfgB8AHwB+AHwAfAH4AfAB8AfgB8AHwA+AHwAfAAAAfAB8AAAB8AHwAAAHwAfAAAAfAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////8AH/////wAf/////AB/////8AH/////wAf/////AB8APgAAAHwA+AAAAfAD4AAAB8APgAAAHwA+AAAAfAD4AAAB8APgAAAHwA+AAAAfAD4AAAB8APgAAAHwA+AAAAfAAAAAAB8AAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAB//wAAAAf//wAAAH///wAAA////gAAH////AAA////+AAH/4D/8AAf8AB/4AD/AAB/gAP4AAB/AB/AAAD8AH4AAAPwAfgAAAfAB8AAAB8AHwAAAH4AfAAAAfgB8AD4B+AHwAPgH4AfAA+AfgB8AD4B8AHwAPgHwAfgA+A/AB+AD//8AH4AP//wAPwA//+AA/AD//4AAAAP//gAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////AB/////8AH/////wAf/////AB/////8AH/////wAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAf/////AB/////8AH/////wAf/////AB/////8AH/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////8AAAAAAAAAAAAAAAHgAAAAAA/AAAAAAD4AAAAAAfgAAAAAH+AAAAAP/wf//////B//////4H//////Af/////4B//////AH/////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////8AAAA/4AAAAAH/AAAAAA/4AAAAAP/AAAAAB/8AAAAAP/8AAAAB//4AAAAf//4AAAD/3/4AAAf+P/wAAD/gP/wAA/8AP/wAH/gAf/gAf8AAf/AB/AAA/8AH4AAA/wAfAAAB/AB4AAAB8AGAAAADwAQAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////AB/////8AH/////wAf/////AB/////8AH/////wAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAB/wAAAB///AAA////8AH/////wAf/////AB/////8AH////wAAf//gAAAB/4AAAAAH/8AAAAAf//AAAAB///AAAAB///gAAAA///wAAAAf//4AAAAH//8AAAAD//+AAAAB//+AAAAAf/4AAAAB//gAAAB//+AAAA///wAAAf//4AAAf//4AAAP//8AAAP//+AAAB///AAAAH//gAAAAf/gAAAAB/4AAAAAH///AAAAf////4AB/////8AH/////wAH/////AAAH///8AAAAH//wAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////8AD/wAAAAAH/wAAAAAH/wAAAAAP/gAAAAAP/gAAAAAf/AAAAAAf/AAAAAA/+AAAAAA/+AAAAAB/+AAAAAB/8AAAAAB/8AAAAAD/4AAAAAD/4AAAAAH/wAAAAAH/wAf/////AB/////8AH/////wAf/////AB/////8AH/////wAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAf//wAAAD///wAAA////gAAH////AAA////+AAH/8D/8AAf8AB/4AD/AAB/gAP4AAD/AA/AAAD8AH4AAAPwAfgAAAfAB8AAAB+AHwAAAH4AfAAAAfgB8AAAB+AHwAAAH4AfAAAAfAB+AAAD8AH4AAAPwAfwAAB/AA/wAAP4AD/wAD/gAH/4B/8AAP////gAAf///8AAB////gAAB///8AAAD///AAAAB//wAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////8AH/////wAf/////AB/////8AH/////wAf/////AB8AB+AAAHwAD4AAAfAAPgAAB8AA+AAAHwAD4AAAfAAfgAAB8AB+AAAHwAHwAAAfgAfAAAB/AD8AAAH+A/wAAAP//+AAAA///4AAAB///AAAAH//4AAAAH//AAAAAP/4AAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+AAAAB///AAAAP///AAAD///+AAAf///8AAD////4AAf/wP/wAB/wAH/gAP8AAH+AA/gAAP8AD8AAAPwAfgAAA/AB+AAAB8AHwAAAH4AfAAAAfgB8AAAB/AHwAAAH+AfAAAAf8B8AAAB/4H4AAAP/wfgAAA//B/AAAH/+D/AAA/n4P/AAP+fgf/gH/x+A////+H4B////wfgH///+B+AH///wH4AP//8APAAH//AAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////8AHwAfAAAAfAB8AAAB8AHwAAAHwAfAAAAfAB8AAAB8AHwAAAHwAfgAAAfAB/AAAB8AP/AAAH4A//AAAfwP//gAA/////gAD/////gAH//z//AAf/+D/8AA//wD/wAA/+AD/AAA/AAD8AAAAAADwAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAD/AAB4AAf+AAfgAD/8AB/AAf/8AD8AD//wAPwAP//gAfAB/H/AB8AH4H8AH4Afgf4AfgB8A/gB+AHwB/AH4AfAH8AfgB8AP4B+AHwA/wHwAfAB/g/AB8AH/P8AH4AP//wAfgAf/+AA/AB//4AD4AD//AAAAAD/4AAAAAH+AAAAAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////8AHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///+AAAf////AAB/////AAH////+AAf////8AB/////4AD/////gAAAAAH/AAAAAAH8AAAAAAPwAAAAAAfAAAAAAB+AAAAAAH4AAAAAAfgAAAAAB+AAAAAAH4AAAAAAfgAAAAAD8AAAAAAfwAAAAAD/AAAAAH/4AH/////gAf////8AB/////gAH////8AAf////AAB////gAAAAAAAAAAcAAAAAAB+AAAAAAH/AAAAAAf/gAAAAB//gAAAAH//wAAAAf//4AAAAP//4AAAAH//8AAAAD//+AAAAB//+AAAAA///AAAAAf//AAAAAf/+AAAAAP/4AAAAAP/gAAAAH/+AAAAD//4AAAB//+AAAA///AAAAf//gAAAP//4AAAH//8AAAD//+AAAAf//AAAAB//wAAAAH/4AAAAAf8AAAAAB+AAAAAAHgAAAAAAAAAAAAABwAAAAAAH8AAAAAAf/AAAAAB//gAAAAH//4AAAAf//+AAAB////gAAAf///wAAAH///8AAAA///+AAAAP//4AAAAD//gAAAAB/+AAAAB//4AAAB///gAAA///4AAA///8AAAf//8AAAf//+AAAH//+AAAAf//AAAAB//AAAAAH//gAAAAf//wAAAA///8AAAAf//+AAAAH///gAAAD///wAAAA///4AAAAf//gAAAAH/+AAAAAD/4AAAAH//gAAAP//+AAAP///wAAf///4AAf///4AAH///4AAAf//4AAAB//4AAAAH/4AAAAAf8AAAAAB8AAAAAAAAAAAAAAAAAAAAABgAAAAMAHgAAADwAfAAAAfAB/AAAH8AH+AAB/wAf+AAP/AB/+AD/8AD/8A//AAD/8H/4AAH/5/+AAAH///gAAAH//4AAAAP//AAAAAP/wAAAAAf/AAAAAD//AAAAA///AAAAP//+AAAD/8/+AAAf/B/+AAH/4B/+AB/+AD/8AH/wAD/wAf8AAH/AB/AAAH8AH4AAAPwAeAAAAPABgAAAAMAAAAAAAQAAAAAAAABwAAAAAAHwAAAAAAfwAAAAAB/wAAAAAH/gAAAAAf/gAAAAA//gAAAAA//gAAAAB//gAAAAB//gAAAAB//gAAAAB////AAAB///8AAAB///wAAAH///AAAB///8AAAf///wAAH/+AAAAB//gAAAAf/4AAAAH/+AAAAB//gAAAAH/4AAAAAf+AAAAAB/gAAAAAH4AAAAAAfAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAHwAfAAAB/AB8AAAP8AHwAAD/wAfAAAf/AB8AAH/8AHwAA//wAfAAP//AB8AD/98AHwAf/nwAfAH/4fAB8A//B8AHwP/wHwAfB/+AfAB8f/gB8AHz/4AHwAf//AAfAB//wAB8AH/+AAHwAf/gAAfAB/8AAB8AH/AAAHwAfwAAAfAB+AAAB8AHgAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////h///////P//////8///////7///////v//////++AAAAAD74AAAAAPvgAAAAA8+AAAAADx4AAAAAPHgAAAAA8AAAAAAADgAAAAAAP4AAAAAA/8AAAAAD//AAAAAP//gAAAA///4AAAAf//8AAAAH///AAAAD///gAAAA///wAAAAf//8AAAAH//+AAAAD///gAAAA//+AAAAAf/4AAAAAP/gAAAAAD+AAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAA8eAAAAADz4AAAAAPPgAAAAA8+AAAAAD74AAAAAPv//////+///////7///////v//////8f//////w//////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAD4AAAAAA/gAAAAAf+AAAAAH/4AAAAD//gAAAA//+AAAAf//AAAAH//gAAAB//4AAAAH/8AAAAAf+AAAAAB/+AAAAAH//AAAAAP//gAAAAH//gAAAAH//wAAAAD//gAAAAD/+AAAAAB/4AAAAAB/gAAAAAA+AAAAAAA4AAAAAAAAAAAAAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAAAAAAAAAABgAAAAAAPgAAAAAB/AAAAAAP+AAAAAA/4AAAAAA/wAAAAAB/gAAAAAD/AAAAAAH8AAAAAAPwAAAAAAeAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAMAP+AAAB8B/8AAAHwP/4AAA/A//wAAD8H//AAAPgf/+AAA+B8H4AAH4PwfgAAfg+A+AAB+D4D4AAH4PgfAAAfg8B8AAB+DwHwAAH+PA+AAAP///8AAA////wAAD////AAAH///8AAAP///wAAAP///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////4A//////gD//////AP/////8A//////wD//////AAAHwAB+AAA/AAH4AAD4AAPgAAPgAA+AAB+AAD4AAH4AAfgAAfgAB8AAB+AAHwAAH8AA/AAAP4AP8AAA/+H/gAAD///8AAAH///wAAAP//+AAAAf//gAAAA//8AAAAA/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAH/4AAAAB//4AAAAf//4AAAD///wAAAP///gAAB///+AAAP+Af8AAA/gAfwAAD8AA/AAAPgAB8AAB+AAH4AAH4AAfgAAfgAB+AAB+AAHwAAH4AAfAAAfgAB8AAA+AAHwAAD8AA+AAAPwAD4AAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/gAAAAD//wAAAAf//gAAAH///AAAA///+AAAH///4AAAf///wAAD/AD/AAAPwAD8AAA+AAH4AAH4AAfgAAfAAB+AAB8AAH4AAHwAAfAAAfAAB8AAB+AAPwAAD4AA+AP/////8A//////wD//////AP/////8A//////wD//////AAAAAAAAAAAAAAAAAAAAAAAAAAAP/AAAAAH//AAAAA///AAAAH///AAAA///8AAAH///4AAA////wAAD+Ph/AAAPw+D8AAB+D4P4AAHwPgfgAAfA+B+AAB8D4H4AAH4PgfgAAfg+B+AAA/j4HwAAD//gfAAAH/+B8AAAf/4PwAAA//g+AAAA/+B4AAAB/4AAAAAAAAAAAAAAAAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAA/////4AP/////gB/////+AP/////4A//////gH/////+AfwfAAAAB8B8AAAAPwHwAAAA/AfAAAAD8B8AAAAPwHwAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAH4AAP+Ag/wAB/8P3/wAP/7///AB/////+AP/////4A////8/gD8H//A/APgPx8B8B8AeHwHwHwB8fAfAfAHx8B8B8AfHwHwHwB4fAfAfgPh8B8A/B+H4HgD//4fg+AP//B/H4A//8H//gD//gP/8AP/8A//wA//AD/+AH4AAH/wAfgAAH+AB+AAADAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////AP/////8A//////wD//////AP/////8A//////wAAB+AAAAAAHwAAAAAA/AAAAAAD4AAAAAAPgAAAAAB+AAAAAAH4AAAAAAfgAAAAAB+AAAAAAH+AAAAAAf///8AAA////wAAD////AAAH///8AAAP///wAAAP///AAAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAH8P///8Afw////wD/D////AP8P///8A/w////wB+D////ADwAAAAAAAAAAAAAAAAAAAAAQAAAAAABAAAAAAAM+AAAAAH38P/////fw///////D//////8P//////w/////9+D////+DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////AP/////8A//////wD//////AP/////8A//////wAAAAf4AAAAAD/AAAAAAf4AAAAAD/wAAAAAf/wAAAAD//gAAAA///gAAAH/f/AAAA/4/+AAAD/A/+AAAP4B/8AAA/AB/wAAD4AD/AAAOAAD8AAAwAAHwAACAAAHAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////8A//////wD//////AP/////8A//////wD//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////AAAP///8AAA////wAAD////AAAP///8AAA////wAAB+AAAAAAHwAAAAAA/AAAAAAD4AAAAAAPgAAAAAA+AAAAAAH4AAAAAAfgAAAAAB/AAAAAAH/AAAAAAf///8AAA////wAAD////AAAH///8AAAP///wAAA////AAAH4AAAAAAfAAAAAAD8AAAAAAPgAAAAAB+AAAAAAH4AAAAAAfgAAAAAB+AAAAAAH8AAAAAAf///8AAB////wAAD////AAAP///8AAAf///wAAA////AAAAf//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////AAAP///8AAA////wAAD////AAAP///8AAA////wAAB+AAAAAAHwAAAAAA/AAAAAAD4AAAAAAPgAAAAAA+AAAAAAH4AAAAAAfgAAAAAB+AAAAAAH+AAAAAAf///8AAA////wAAD////AAAH///8AAAP///wAAAf///AAAAAAAAAAAAAAAAAAAA/4AAAAAP/8AAAAD//8AAAAf//4AAAD///wAAAf///gAAB////AAAP8AP8AAA/AAPwAAH4AAfAAAfgAB+AAB8AAD4AAHwAAPgAAfAAB+AAB+AAHwAAD8AA/AAAP4AH8AAA/8B/wAAB///+AAAH///wAAAP///AAAAf//4AAAAf/+AAAAAf/gAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////AP/////8A//////wD//////AP/////8A//////wB8AAfAAAPwAB8AAA+AAH4AAD4AAPgAAfgAA+AAB+AAH4AAH4AAfAAAfgAB8AAB/AAPwAAD+AD/AAAP/B/4AAA////gAAB///8AAAD///gAAAH//8AAAAP//AAAAAP/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/gAAAAD//wAAAAf//gAAAH///AAAA///+AAAH///4AAAf///wAAD/AD/AAAPwAD8AAA+AAH4AAH4AAfgAAfAAB+AAB8AAH4AAHwAAfAAAfAAB8AAB+AAPwAAD4AA+AAAP/////8A//////wD//////AP/////8A//////wD//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///8AAA////wAAD////AAAP///8AAA////wAAB////AAAH4AAAAAA/AAAAAAD8AAAAAAPgAAAAAB+AAAAAAH4AAAAAAfgAAAAAB+AAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AD4AAAP+APwAAB/8A/AAAH/4B8AAA//wHwAAD//AfAAAPj+B+AAA+H8H4AAH4fwfgAAfA/B+AAB8D+H4AAHwH8fAAAfgf/8AAA+A//wAAD4D/+AAAPwH/4AAA+AP/AAAAAAf4AAAAAAAAAAAAAAAAAAD4AAAAAAPgAAAAAA+AAAAAAP///4AAH////4AA/////wAD/////AAP////8AA/////4AAH4AB/gAAPgAB+AAA+AAH4AAD4AAfAAAPgAB8AAA+AAHwAAD4AA+AAAPAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAf/4AAAAD///wAAAP///wAAA////gAAD////AAAP///8AAA////wAAAAAB/gAAAAAB+AAAAAAH4AAAAAAfgAAAAAB8AAAAAAHwAAAAAAfAAAAAAD4AAAAAAPgAAD///+AAAP///8AAA////4AAD////gAAP///+AAA////4AAAAAAAAAAOAAAAAAA+AAAAAAD/AAAAAAP/gAAAAA//gAAAAD//wAAAAP//wAAAAH//4AAAAD//4AAAAB//8AAAAA//4AAAAAf/gAAAAAP+AAAAAH/4AAAAD//gAAAB//8AAAA///AAAAf//gAAAP//wAAAA//8AAAAD/+AAAAAP/AAAAAA/wAAAAAD4AAAAAAMAAAAAAAAAAAAAADgAAAAAAP4AAAAAA/8AAAAAD/+AAAAAP//gAAAA///wAAAB///4AAAAf//8AAAAH//4AAAAD//gAAAAA/+AAAAAf/4AAAAP//gAAAP//8AAAP//+AAAD///AAAAP//AAAAA//AAAAAD/gAAAAAP/4AAAAA//+AAAAD///AAAAB///wAAAA///4AAAAP//gAAAAD/+AAAAAD/4AAAAD//gAAAD//+AAAD///gAAB///wAAAP//4AAAA//8AAAAD/8AAAAAP+AAAAAA/AAAAAADAAAAAAAAAAAAAAAwAAAwAADgAAPAAAPgAB8AAA/AAPwAAD/AD/AAAP+Af8AAA/8H/wAAB/8/+AAAB///gAAAD//4AAAAD//AAAAAH/wAAAAAf/gAAAAD//AAAAA///AAAAH//+AAAB/4/+AAAP/B/8AAA/4B/wAAD+AD/AAAPwAD8AAA+AAHwAADgAAPAAAMAAAMAAAAAAAQAAAAAAAAAAAAAAAAADAAAAAAAPgAAAAAA/wAAAPgD/4AAA/AP/8AAD8A//8AAPwD//+AA/AD///AH4AB///g/gAAf//H+AAAP///wAAAH//+AAAAD//wAAAA//+AAAAf//gAAAf//4AAAP//+AAAP///AAAD///AAAAP//gAAAA//wAAAAD/4AAAAAP8AAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAA8AAA+AAHwAAD4AB/AAAPgAP8AAA+AD/wAAD4Af/AAAPgH/8AAA+A//wAAD4P//AAAPh/98AAA+f/nwAAD7/4fAAAP//B8AAA//wHwAAD/+AfAAAP/gB8AAA/8AHwAAD/AAfAAAP4AB8AAA+AAHwAADwAAPAAAAAAAAAAAAAAAAAAAAPAAAAAAA+AAAAAAD4AAAAAAfgAAAAAB/AAAAAAP+AAAP//////B///////P///f//8///5///7///j///v//8H//++AAAAAD74AAAAAPvgAAAAA++AAAAADz4AAAAAPHgAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////v/////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAA8+AAAAADz4AAAAAPPgAAAAA++AAAAAD74AAAAAPv//8H//+///4///7///n///v///f//8f//////w//////+AAAP+AAAAAAfwAAAAAB+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAA8AAAAAAH4AAAAAA/gAAAAAD8AAAAAAfgAAAAAB+AAAAAAH4AAAAAAfgAAAAAB/AAAAAAD8AAAAAAP4AAAAAAfwAAAAAA/AAAAAAD8AAAAAAPwAAAAAAfAAAAAAD8AAAAAAPwAAAAAB/AAAAAAP4AAAAAAfAAAAAAA4AAAAAABAAAAAAAAAAAAA"), 32, atob("CAwZIBwtIg0RERocDBkMFB4PGxkeGh0bHB0MDRsbHBYtIB4dIRsZHyALDR8ZKSAjHSMfGR0fHywfHR0RExAcJw4XGxcaGRMdGwwMGwsqGhsbGhMVExkaJhoaFxQNFh0="), 46|65536);
};

{ // must be inside our own scope here so that when we are unloaded everything disappears
  // we also define functions using 'let fn = function() {..}' for the same reason. function decls are global
let drawTimeout;

//ROUNDED RECT FUNCTION
let bRoundedRectangle= function(x1,y1,x2,y2,r) {
    var f = 1 - r;
    var ddF_x = 0;
    var ddF_y = -2 * r;
    var x = 0;
    var y = r;
    g.drawLine(x1+r,y1,x2-r,y1);
    g.drawLine(x1+r,y2,x2-r,y2);
    g.drawLine(x1,y1+r,x1,y2-r);
    g.drawLine(x2,y1+r,x2,y2-r);
    var cx1=x1+r;
    var cx2=x2-r;
    var cy1=y1+r;
    var cy2=y2-r;
    while(x < y)
    {
      if(f >= 0)
      {
        y--;
        ddF_y += 2;
        f += ddF_y;
      }
      x++;
      ddF_x += 2;
      f += ddF_x + 1;
      g.setPixel(cx2 + x, cy2 + y);
      g.setPixel(cx1 - x, cy2 + y);
      g.setPixel(cx2 + x, cy1 - y);
      g.setPixel(cx1 - x, cy1 - y);
      g.setPixel(cx2 + y, cy2 + x);
      g.setPixel(cx1 - y, cy2 + x);
      g.setPixel(cx2 + y, cy1 - x);
      g.setPixel(cx1 - y, cy1 - x);
    }
  };
  
  
  
//CLOCK INFO
let clockInfoItems = require("clock_info").load();

  

//CLOCK INFO 1 DIMENSIONS: 13,103,w:66,h:65  

let clockInfoMenuLeft = require("clock_info").addInteractive(clockInfoItems, {
    // Add the dimensions we're rendering to here - these are used to detect taps on the clock info area
    x : 13, y: 103, w: 66, h:65,
  // You can add other information here you want to be passed into 'options' in 'draw'
  // This function draws the info
  draw : (itm, info, options) => {
    // itm: the item containing name/hasRange/etc
    // info: data returned from itm.get() containing text/img/etc
    // options: options passed into addInteractive
    // Clear the background
    g.reset().clearRect(options.x-5, options.y-5, options.x+options.w+5, options.y+options.h+5);
    // indicate focus - we're using a border, but you could change color?
    if (options.focus){
      // show if focused
      g.setColor(0,15,255);
      bRoundedRectangle(10,100,82,170,8); 
    }else{
      g.setColor(g.theme.fg);
      bRoundedRectangle(10,100,82,170,8); 
    }
    // we're drawing center-aligned here
    var midx = options.x+options.w/2;
    var midy=options.y+options.h/2;
    if (info.img){
      g.drawImage(info.img, midx-12,midy-21);
    }// draw the image
    g.setFont("6x8:2").setFontAlign(0,1).drawString(info.text, midx,midy+21); // draw the text
  }
});



//CLOCK INFO RIGHT DIMENSIONS: 97,113, w:66, h: 55
let clockInfoMenuRight = require("clock_info").addInteractive(clockInfoItems, {
  // Add the dimensions we're rendering to here - these are used to detect taps on the clock info area
  x : 97, y: 103, w: 66, h:65,
  // You can add other information here you want to be passed into 'options' in 'draw'
  // This function draws the info
  draw : (itm, info, options) => {
    // itm: the item containing name/hasRange/etc
    // info: data returned from itm.get() containing text/img/etc
    // options: options passed into addInteractive
    // Clear the background
    g.reset().clearRect(options.x-5, options.y-5, options.x+options.w+5, options.y+options.h+5);
    // indicate focus - we're using a border, but you could change color?
    if (options.focus){
      // show if focused
      g.setColor(0,15,255);
      bRoundedRectangle(94,100,166,170,8);  
    }else{
      g.setColor(g.theme.fg);
      bRoundedRectangle(94,100,166,170,8);     
    }
    // we're drawing center-aligned here
    var midx = options.x+options.w/2;
    var midy=options.y+options.h/2;
    if (info.img){
      g.drawImage(info.img, midx-12,midy-21);
    }// draw the image
    g.setFont("6x8:2").setFontAlign(0,1).drawString(info.text, midx,midy+21); // draw the text
  }
});


  
  
  
  

// DRAW FACE
let draw = function() {
  require("FontTeletext10x18Mode7").add(Graphics);
  var X = g.getWidth() / 2;
  var Y = (g.getHeight() / 2)-15;
  g.reset();
  var d = new Date();
  var clock = require("locale").time(d, 1 /*omit seconds*/);
  var meridian = require("locale").meridian(d);
  // draw the current time (4x size 7 segment)

   // align bottom right

  g.setFontBold();
  g.setFontAlign(0,1);
  g.drawString(" "+clock+" ", X-10, Y, true /*clear background*/);
  // draw the meridian(am/pm) and seconds (2x size 7 segment)
  
  g.setFont("Vector",20);

  g.setFontAlign(-1,1); // align bottom left
  g.drawString(meridian, X+50, Y-10, true /*clear background*/);
  // draw the date, in a normal font

  g.setFontAlign(0,1); // align center bottom
  // pad the date - this clears the background if the date were to change length
  var dateStr = require("locale").dow(new Date(), 1)+", "+ require("locale").month(new Date(), true)+" "+new Date().getDate();
  g.drawString(" "+dateStr+" ", g.getWidth()/2, Y+15, true /*clear background*/);
  
  
  
  // queue next draw
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = setTimeout(function() {
    drawTimeout = undefined;
    draw();
  }, 60000 - (Date.now() % 60000));
};

  

  
// Show launcher when middle button pressed
Bangle.setUI({
  mode : "clock",
  remove : function() {
    // Called to unload all of the clock app
    if (drawTimeout) clearTimeout(drawTimeout);
    drawTimeout = undefined;
    delete Graphics.prototype.setFontBold;
    delete Graphics.prototype.setFontTeletext10x18Mode7;
    clockInfoMenuRight.remove();
    clockInfoMenuLeft.remove();
    
  }});
  
g.clear();
// Load widgets
Bangle.loadWidgets();
draw();
drawClockInfos();
setTimeout(Bangle.drawWidgets,0);
}

//Function for rounded rectangle
function bRoundedRectangle (x1,y1,x2,y2,r) {
    var f = 1 - r;
    var ddF_x = 0;
    var ddF_y = -2 * r;
    var x = 0;
    var y = r;
    g.drawLine(x1+r,y1,x2-r,y1);
    g.drawLine(x1+r,y2,x2-r,y2);
    g.drawLine(x1,y1+r,x1,y2-r);
    g.drawLine(x2,y1+r,x2,y2-r);
    var cx1=x1+r;
    var cx2=x2-r;
    var cy1=y1+r;
    var cy2=y2-r;
    while(x < y)
    {
      if(f >= 0)
      {
        y--;
        ddF_y += 2;
        f += ddF_y;
      }
      x++;
      ddF_x += 2;
      f += ddF_x + 1;
      g.setPixel(cx2 + x, cy2 + y);
      g.setPixel(cx1 - x, cy2 + y);
      g.setPixel(cx2 + x, cy1 - y);
      g.setPixel(cx1 - x, cy1 - y);
      g.setPixel(cx2 + y, cy2 + x);
      g.setPixel(cx1 - y, cy2 + x);
      g.setPixel(cx2 + y, cy1 - x);
      g.setPixel(cx1 - y, cy1 - x);
    }
  }
// Load fonts
require("FontTeletext10x18Mode7").add(Graphics);
Graphics.prototype.setFontBold = function() {
  // Actual height 55 (55 - 1)
  // 1 BPP
  return this.setFontCustom(
    atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAHAAAAf///8fwAAAf///8/4AAAf///8/8AAAf///9/8AAAf///9/8AAAf///9/8AAAf///9/8AAAf///9/8AAAf///8/4AAAf///8/4AAAf/wAAPwAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAPw8AAAAAAAf58AAAAAAA//8AAAAAAA//8AAAAAAA//8AAAAAAA//4AAAAAAA//wAAAAAAA//wAAAAAAA//AAAAAAAAf+AAAAAAAAP8AAAAAAAABAIAAAAAAAPw8AAAAAAAf58AAAAAAA//8AAAAAAA//8AAAAAAA//8AAAAAAA//4AAAAAAA//wAAAAAAA//wAAAAAAA//AAAAAAAAf+AAAAAAAAP8AAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/AAAAAAB/3/AAAAAAB/3/P4AAAAB/3//4AAAAB////4AAAAB////4AAAD/////4AAAP/////4AAAP/////4AAAP/////4AAAP/////4AAAP////8AAAAP/////4AAAP//z//4AAAP/////4AAAGf////4AAAP/////4AAAP/////4AAAP/////4AAAP/////4AAAP/////wAAAP////AAAAAP////AAAAAP//3/AAAAAPx/3/AAAAAAB/3/AAAAAAB/wAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAAAAAB//wD/wAAAD//4D/4AAAH//8D/4AAAP//+B/4AAAP//+B/4AAAf///B/4AAAf///B/8AAf////g//wAf////w//wAf////w//wAf////4//wAf/+f////wAf/+P////wAf/+H////wAf/+H////wAf/+D////wAAf+D///4AAAf/B///4AAAf/B///wAAAf/A///gAAAf/Af//AAAAf+AH/+AAAAIAAD/4AAAAAAAAAAAAAAAAAAAAAAAAAf/8AAAAAAD///AAAAAAH///wAAAAAP///4AAAAAf///4AAAAAf///8AAAAA////8AAAAA////8AAAAA/wAH8AAAAA/wAH8AAAAA/wAH8AAAAA////8AAAAAf///8AAAAAf///8AIAAAf///4B8AAAP///4f8AAAH///3/8AAAD/////8AAAAf////8AAAAAB///8AAAAAf///8AAAAD////8AAAA/////AAAAP////4AAAA////+AAAAA////wAAAAA///8YAAAAA/////8AAAA//////gAAA/+P///wAAA/wf///wAAA8Af///4AAAAA////4AAAAA////8AAAAA////8AAAAA/wAP8AAAAA/gAH8AAAAA/wAf8AAAAA////8AAAAA////8AAAAA////4AAAAAf///4AAAAAP///wAAAAAH///gAAAAAD//+AAAAAAAP/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/4AAAAAAAH/+AAAAAAAP//AAAAA/gf//gAAAD/8///wAAAP/////wAAAP/////4AAAf/////4AAAf/////4AAA//////8AAA////7/8AAA////w/8AAA////4f8AAA////8f8AAB/8f/+f8AAB/8f///8AAA//////8AAA//////4AAA//////4AAA//////4AAA///3//wAAAf//j//wAAAf//h//4AAAP//A//4AAAH/+///4AAAB/w///8AAAAAA///8AAAAAA///8AAAAAA///8AAAAAA///8AAAAAA//f8AAAAAA/+f8AAAAAAfwf8AAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAPw8AAAAAAAf58AAAAAAA//8AAAAAAA//8AAAAAAA//8AAAAAAA//4AAAAAAA//wAAAAAAA//wAAAAAAA//AAAAAAAAf+AAAAAAAAP8AAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//wAAAAAA///+AAAAAH////gAAAAf////4AAAA/////+AAAD//////AAAH//////wAAP//////4AAf//////8AB///////+AB///////+AA///////+AA///AD//+AA//gAAH/8AAf+AAAA/8AAfwAAAAH8AAPAAAAAB4AAOAAAAAA4AAAAAAAAAAAAMAAAAAAYAAPAAAAAB4AAfwAAAAH8AAf+AAAA/8AA//gAAH/8AA///AB//+AA///////+AB///////+AB///////+AA///////8AAP//////4AAH//////wAAD//////gAAA/////+AAAAf////4AAAAH////wAAAAA///+AAAAAAH//wAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAB/gAAAAAAAB/w4AAAAAAA/z4AAAAAAA/38AAAAAAA//+AAAAAAA//+AAAAAAB///AAAAAAf///AAAAAAf//8AAAAAAf//4AAAAAAf//wAAAAAAf//wAAAAAAf//4AAAAAAf//8AAAAAAf//+AAAAAAAf//AAAAAAA//+AAAAAAA//+AAAAAAA/z8AAAAAAA/x4AAAAAAA/g4AAAAAAAfgAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAH///8AAAAAP///8AAAAAP///8AAAAAP///8AAAAAP///8AAAAAP///8AAAAAP///8AAAAAP///8AAAAAH///4AAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgYAAAAAAA/x4AAAAAAA/78AAAAAAB//8AAAAAAB//8AAAAAAB//4AAAAAAB//wAAAAAAB//wAAAAAAA//gAAAAAAA/+AAAAAAAAf8AAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAfwAAAAAAAA/4AAAAAAAA/8AAAAAAAB/8AAAAAAAB/8AAAAAAAB/8AAAAAAAB/8AAAAAAAB/8AAAAAAAA/4AAAAAAAA/4AAAAAAAAPwAAAAAAAAAAAAAAAAAAAH/AAAAAAAA//AAAAAAAP//AAAAAAD///AAAAAAf///AAAAAH////AAAAA/////AAAAP/////AAAB//////AAAf//////AAH//////wAAf/////+AAAf/////gAAAf////4AAAAf////AAAAAf///wAAAAAf//+AAAAAAf//gAAAAAAf/8AAAAAAAf/AAAAAAAAf4AAAAAAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAP///wAAAAB////+AAAAD/////AAAAH/////gAAAP/////wAAAP/////4AAAf/////4AAAf/////4AAAf/////8AAA//////8AAA//gAD/8AAA/+AAA/8AAA/8AAA/8AAA/+AAA/8AAA//AAB/8AAA//////8AAAf/////8AAAf/////4AAAf/////4AAAP/////4AAAP/////wAAAH/////gAAAD/////AAAAB////+AAAAAf///4AAAAAB//+AAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAAH/AAAAAAAAH/AAAAAAAAP/AAAAAAAAP/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAAAAAAAAH4AAAAAAAAH/gAAf4AAAP/wAA/4AAAP/gAB/4AAAf/gAD/4AAAf/gAH/4AAAf/AAP/4AAAf/AAf/4AAAf/AB//4AAA//AD//4AAA//AP//4AAA//Af//4AAA//j///4AAA//////4AAAf/////4AAAf/////4AAAf/////4AAAf///9/4AAAP///5/4AAAP///x/4AAAH///B/4AAAD//+B/4AAAB//4B/4AAAAf/AB/4AAAAAAAAAAAAACAAAAAAAAAHwAAAAgAAAH+AAAPwAAAP/gAD/wAAAP/AAD/4AAAf/AAD/4AAAf/H/D/4AAAf+H/B/4AAAf+H/B/8AAAf+H/B/8AAA/+H/h/8AAA/+H/h/8AAA////h/8AAA//////8AAA//////8AAA//////8AAAf/////4AAAf/////4AAAf/////4AAAf/////wAAAP/////wAAAH//P//gAAAD/+P//AAAAB/8D/+AAAAAHgB/4AAAAAAAAAAAAAAAAAB4AAAAAAAAD/wAAAAAAAP/wAAAAAAA//wAAAAAAD//wAAAAAAP//wAAAAAA///wAAAAAD///wAAAAAH///wAAAAAf///wAAAAB////wAAAAH////wAAAAf//5/wAAAAf//h/wAAAAf/+B/wAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///D/wAAAf///D/4AAAf///D/4AAAf///j/4AAAf///j/4AAAf///h/8AAAf///h/8AAAf///h/8AAAf///h/8AAAf///B/8AAAf+H/B/8AAAf+P/3/8AAAf+P///8AAAf+P///8AAAf+P///4AAAf+H///4AAAf+H///4AAAf+H///wAAAf+D///gAAAf+D///gAAAf+B//+AAAAAAAP/4AAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAH//AAAAAAA///4AAAAAH///+AAAAAP////AAAAAf////gAAAB/////wAAAB/////wAAAD/////4AAAH/////4AAAH/////4AAAP/////8AAAP///D/8AAAP/3/A/8AAAf/H/A/8AAAf/H/A/8AAAf+P/h/8AAAf+P///8AAAf+H///8AAA/8H///4AAA/8H///4AAA/8H///4AAA/8D///wAAA/8D///gAAAQAB///AAAAAAA//+AAAAAAAP/4AAAAAAAAIAAAAAAAAAAAAAAAf/AAAAAAAAf/AAAAAAAAf/AAAA4AAAf/AAAH4AAAf/AAA/4AAAf/AAH/4AAAf/AAf/4AAAf/AD//4AAAf/Af//4AAAf/D///4AAAf/P///4AAAf/////4AAAf/////4AAAf/////4AAAf/////wAAAf////+AAAAf////wAAAAf///+AAAAAf///gAAAAAf//8AAAAAAf//gAAAAAAf/8AAAAAAAf/gAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAGAAAAAAf4B/8AAAAB/+D//AAAAD//n//gAAAH/////gAAAP/////wAAAP/////wAAAf/////4AAAf/////4AAAf/////4AAAf/////8AAA//////8AAA/8P/w/8AAA/8H/gf8AAA/8H/wf8AAA/8P/4/8AAA//////8AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAP/////wAAAH/////wAAAH//v//gAAAB/+H//AAAAA/8D/8AAAAAAAAfgAAAAAAAAAAAAAAAf/gAAAAAAB//4AAAAAAD//+AB4AAAH//+A/8AAAP///A/8AAAP///g/8AAAf///g/8AAAf///g/8AAAf///g/8AAAf///h/4AAA/+H/h/4AAA/8B/j/4AAA/8B/j/4AAA/8B/v/4AAA//B///wAAA//////wAAAf/////gAAAf/////gAAAf/////AAAAP////+AAAAP////+AAAAH////4AAAAD////wAAAAB////AAAAAAf//8AAAAAAD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAfwAAAAAf4A/4AAAAA/8A/4AAAAA/8B/8AAAAA/8B/8AAAAA/8B/8AAAAA/8B/8AAAAA/8B/8AAAAA/8A/8AAAAAf4A/4AAAAAPwAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAPwAfw4AAAAf4A/58AAAA/8A//8AAAA/8B//8AAAA/8B//8AAAA/8B//4AAAA/8B//wAAAA/8B//gAAAA/8A//AAAAAf4A/+AAAAAPwAf8AAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAf4AAAAAAAA/4AAAAAAAB/8AAAAAAAD/+AAAAAAAH//AAAAAAAP//gAAAAAAf//wAAAAAA///4AAAAAB///8AAAAAB///+AAAAAD////AAAAAH/9//gAAAAP/4//wAAAAf/wf/4AAAA//gP/4AAAAf/AH/wAAAAP+AD/gAAAAH8AB/AAAAAB8AA8AAAAAA4AAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8f8AAAAAAAAAAAAAAAAAAAAAAAAAA4AAYAAAAAB4AA8AAAAAD8AB+AAAAAP+AD/gAAAAf/AH/wAAAA//gP/4AAAAf/wf/4AAAAP/4//wAAAAH/9//gAAAAD////AAAAAD///+AAAAAB///8AAAAAA///4AAAAAAf//wAAAAAAP//gAAAAAAH//AAAAAAAD/+AAAAAAAB/+AAAAAAAA/8AAAAAAAAf4AAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+AAAAAAAA/+AAAAAAAA/+AAAfwAAA/8B/4/4AAA/8D/4/8AAA/8D/4/8AAA/8H/4/8AAA/8P/5/8AAB/8P/4/8AAB////4/8AAA////4/8AAA////4f4AAA///+APwAAA///8AAAAAA///8AAAAAAf//4AAAAAAP//wAAAAAAH//AAAAAAAB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/gAAAAAAD//+AAAAAAf///gAAAAB////4AAAAH////+AAAAP/////AAAAf/////gAAA//////wAAB//////4AAD//////8AAH//gAf/8AAP/8AAD/+AAP/wAAA//AAf/gAAAf/AAf/AAP+P/AA//+Af/n/gA///4//3/gA/7/x//7/gB/7/x//7/wB/z/z//9/wB/3/z//9/wB/3/j//9/wB/n/n//8/wD/n/n//8/wD/n/n+f4/wD/n/n8f4/wD/n//8f4/wD/n////w/wD/n////g/wD/n////w/wD/n////5/wB/3////5/wB/3////5/wB/z////9/wB/7////9/gB/5////9/gA/8f///9/gA/+AAAf8AAA//AAAf8AAAf/gAA/8AAAf/4AB/4AAAP//AP/4AAAP/////4AAAH/////wAAAD/////wAAAB/////gAAAA/////AAAAAf///+AAAAAH///8AAAAAB///wAAAAAAP//AAAAAAAAPAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAH/4AAAAAAH//4AAAAAD///4AAAAD////4AAAB/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////gAAAf////4AAAAf////4AAAAf//4f4AAAAf/+Af4AAAAf//+f4AAAAf////4AAAAf////+AAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAB/////4AAAAB////4AAAAAD///4AAAAAAD//4AAAAAAAH/4AAAAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf8B/Af4AAAf8B/Af4AAAf+B/Af4AAAf/v/gf4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAP/////4AAAP/////wAAAH/////wAAAH//f//gAAAD/+P//AAAAA/8H/+AAAAADAB/4AAAAAAAAAAAAAAAAAAAAAAAAAB//+AAAAAAP///wAAAAA////8AAAAB/////AAAAD/////gAAAH/////wAAAP/////wAAAP/////4AAAf/////4AAAf/////4AAAf/////8AAA//+A//8AAA//gAD/8AAA//AAB/8AAA/+AAB/8AAA/+AAA/8AAA/+AAB/8AAA//AAB/8AAAf/AAB/8AAAf/AAB/4AAAf/AAB/4AAAf/gAD/4AAAP/AAB/4AAAPgAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+AAB/4AAAf+AAB/4AAAf+AAB/4AAAf/AAB/4AAAf/gAD/4AAAf/4AP/4AAAf/////4AAAf/////wAAAP/////wAAAP/////wAAAH/////gAAAH/////gAAAD/////AAAAB////+AAAAA////4AAAAAP///wAAAAAD//+AAAAAAAH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+AAA/4AAAfAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+AAAAAAAAf+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//+AAAAAAP///wAAAAA////8AAAAB/////AAAAD/////gAAAH/////wAAAP/////wAAAP/////4AAAf/////4AAAf/////8AAAf/////8AAA///j//8AAA//gAD/8AAA//AAB/8AAA//AAB/8AAA//A/h/8AAA//B/x/4AAA//B/x/4AAA//B///wAAAf/B///wAAAf/B///4AAAf/h///4AAAf/h///4AAAf/h///4AAAP/h///4AAAPgB///4AAAAAB///4AAAAAA///4AAAAAAAAAAAAAAAAAAAAAAAP/////wAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAH/gAAAAAAAH/gAAAAAAAH/gAAAAAAAH/gAAAAAAAH/gAAAAAAAH/gAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAAAAAAAAAAAAAYAAAAAAAAAf8AAAAAAAA/8AAAAAAAA/8AAAf/////8AAAf/////8AAAf/////8AAAf/////8AAAf/////8AAAf/////8AAAf/////4AAAf/////4AAAf/////wAAAf/////gAAAf/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAf/+AAAAAAD///wAAAAAP///+AAAAB/////wAAAP/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf//j//4AAAf/8Af/4AAAf/wAD/4AAAf+AAA/4AAAfwAAAH4AAAfAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf///gAAAAAf////gAAAAf/////gAAAf/////4AAAf/////4AAAf/////4AAAA/////4AAAAA////4AAAAAA///4AAAAAf///4AAAAf////4AAAf/////4AAAf/////4AAAf/////4AAAf////+AAAAf////AAAAAf///gAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAf///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf///AAAAAAP///4AAAAAD///+AAAAAAf///gAAAAAH///4AAAAAA///+AAAAAAP///wAAAAAD///4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAAAAAAAAAAAAAAAAAAAB//+AAAAAAP///wAAAAA////8AAAAD/////AAAAH/////gAAAH/////gAAAP/////wAAAP/////4AAAf/////4AAAf/////4AAAf/////8AAA//4AP/8AAA//AAB/8AAA/+AAA/8AAA/+AAA/8AAA/+AAA/8AAA/+AAA/8AAA//AAB/8AAA//+Af/8AAAf/////4AAAf/////4AAAf/////4AAAP/////wAAAP/////wAAAH/////gAAAD/////AAAAB////+AAAAA////4AAAAAP///gAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+Af4AAAAAf+Af4AAAAAf+A/4AAAAAf///4AAAAAf///4AAAAAf///4AAAAAf///4AAAAAP///wAAAAAP///wAAAAAH///wAAAAAH///gAAAAAD///AAAAAAB//+AAAAAAAf/8AAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAB//+AAAAAAP///wAAAAA////8AAAAD////+AAAAH/////AAAAH/////gAAAP/////wAAAP/////4AAAf/////4AAAf/////4AAAf/////8AAA//4AP/8AAA//AAB/8AAA/+AAA/8AAA/+AAA/8AAA/+AAA/+AAA/+AAA/+AAA//AAB//AAA//+Af//AAAf//////gAAf//////wAAf//////wAAP//////wAAP//////4AAH//////4AAD////+/4AAB////8/4AAA////w/8AAAP///A/8AAAB//4Af8AAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+A/4AAAAAf+A//AAAAAf/A//8AAAAf/////gAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAP/////4AAAP/////4AAAP/////4AAAH/////4AAAD//8P/4AAAB//4B/4AAAAf/gAH4AAAAAgAAA4AAAAAAAAAAAAAAB4AAAAAAAAf/AABwAAAB//wD/wAAAD//4D/4AAAH//8D/4AAAP//+B/4AAAf//+B/4AAAf///B/8AAAf///h/8AAA////g/8AAA////w/8AAA////w/8AAA//f/5/8AAA/+P///8AAA/+P///8AAA/+H///8AAA/+H///4AAA/+D///4AAA/+D///4AAAf/B///wAAAf/A///wAAAf/A///gAAAf/Af//AAAAf4AH/8AAAAAAAB/4AAAAAAAAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////4AAAAf////+AAAAf/////AAAAf/////gAAAf/////wAAAf/////wAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////8AAAf/////8AAAAAAAB/8AAAAAAAB/8AAAAAAAB/8AAAAAAAB/8AAAAAAAD/8AAAf/////8AAAf/////8AAAf/////4AAAf/////4AAAf/////4AAAf/////wAAAf/////wAAAf/////gAAAf/////AAAAf////+AAAAf////wAAAAAAAAAAAAAAIAAAAAAAAAfwAAAAAAAAf/wAAAAAAAf//gAAAAAAf///gAAAAAf////AAAAAf/////AAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAB/////4AAAAAf///4AAAAAAP//4AAAAAAP//4AAAAD////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////gAAAf////gAAAAf///gAAAAAf//gAAAAAAf/gAAAAAAAfgAAAAAAAAAAAAAAAAAAMAAAAAAAAAf/gAAAAAAAf//+AAAAAAf////wAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAP/////4AAAAAH///4AAAAA////4AAAD/////4AAAf/////4AAAf/////4AAAf/////4AAAf////+AAAAf///+AAAAAf///wAAAAAf////gAAAAf/////AAAAf/////4AAAf/////4AAAf/////4AAAD/////4AAAAB////4AAAAAD///4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf////AAAAAf//gAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAYAAAeAAAAH4AAAf4AAA/4AAAf/AAH/4AAAf/4B//4AAAf//v//4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////wAAAf////8AAAAB////AAAAAAD///4AAAAB/////gAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf//v//4AAAf/4B//4AAAf/AAH/4AAAfwAAA/4AAAcAAAAD4AAAAAAAAAAAAAfAAAAAAAAAf4AAAAAAAAf/AAAAAAAAf/4AAAAAAAf//AAAAAAAf//4AAAAAAf//+AAAAAAf///wAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAB/////4AAAAH////4AAAAH////4AAAD/////4AAAf/////4AAAf/////4AAAf/////4AAAf///4AAAAAf///AAAAAAf//4AAAAAAf//AAAAAAAf/4AAAAAAAf/gAAAAAAAf8AAAAAAAAfgAAAAAAAAcAAAAAAAAAAAAAAAAAAAfAAAAAAAAAf+AAAHAAAAf+AAAf4AAAf+AAB/4AAAf+AAH/4AAAf+AA//4AAAf+AD//4AAAf+AP//4AAAf+A///4AAAf+D///4AAAf+P///4AAAf+////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf///x/4AAAf///B/4AAAf//8B/4AAAf//wB/4AAAf//AB/4AAAf/8AB/4AAAf/gAB/4AAAf+AAB/4AAAf4AAB/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////+AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AAAAAAAAAAAAfgAAAAAAAAf+AAAAAAAAf/wAAAAAAAf//AAAAAAAf//4AAAAAAf///gAAAAAf///8AAAAAf////wAAAAf/////AAAAf/////4AAAP//////gAAA//////8AAAH//////AAAAf/////AAAAD/////AAAAAP////AAAAAB////AAAAAAH///AAAAAAAf//AAAAAAAD//AAAAAAAAP/AAAAAAAAB/AAAAAAAAAAAAAAAAAAAAAA/wAAAAH+AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAABwAAAAAAAAHwAAAAAAAAfwAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/gAAAAAAAB/AAAAAAAAB/gAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAAfwAAAAAAAAHwAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAADwAAAAAAAAD4AAAAAAAAD+AAAAAAAAD/AAAAAAAAD/gAAAAAAAD/wAAAAAAAD/wAAAAAAAD/wAAAAAAAD/wAAAAAAAB/wAAAAAAAAfwAAAAAAAADwAAAAAAAAAwAAAAAAAAAAAAAAAAAAABAAP+AAAAAD/Af/gAAAAD/4//wAAAAD/x//4AAAAD/x//4AAAAD/z//8AAAAH/z//8AAAAH/j//8AAAAH/n//8AAAAH/n//8AAAAH/n+f4AAAAH/n8f4AAAAH/38f4AAAAH////wAAAAH////gAAAAH////wAAAAH////4AAAAH////4AAAAH////8AAAAH////8AAAAD////8AAAAB////8AAAAA////8AAAAAD8A/8AAAAAAAAf8AAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////wAAA//////4AAAAD/gA/4AAAAH/gAf8AAAAH/gAf8AAAAH/+H/8AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH////4AAAAH////4AAAAD////wAAAAB////wAAAAA////AAAAAAf//8AAAAAAB//AAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAAAD//4AAAAAAP///AAAAAA////gAAAAB////wAAAAD////wAAAAD////4AAAAH////4AAAAH////8AAAAH////8AAAAH////8AAAAH/4B/8AAAAH/gA/8AAAAH/gA/8AAAAH/gA/8AAAAH/gA/8AAAAH/gA/4AAAAH/wA/4AAAAD/wA/4AAAAD/AABwAAAAAAAAAAAAAAAAAAAAAAAAAD//4AAAAAAP//+AAAAAA////gAAAAB////wAAAAD////4AAAAH////4AAAAH////4AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH/gA/8AAAAH/gAf4AAAAH/gA/4AAA//////4AAA//////wAAA//////wAAA//////4AAA//////4AAA//////8AAA//////8AAA//////8AAA//////8AAA//////8AAA//////8AAAAAAAA/8AAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAB//gAAAAAAH//4AAAAAAf//+AAAAAA////AAAAAB////gAAAAD////wAAAAD////wAAAAH////4AAAAH////4AAAAH////8AAAAH////8AAAAH/n9/8AAAAH/n8/8AAAAH/n8f8AAAAH/38f8AAAAH//8f8AAAAH//8f8AAAAH//8f8AAAAH//8/8AAAAD//8/4AAAAD//8/4AAAAB//8/4AAAAA//8/4AAAAAP/8BwAAAAAD/8AAAAAAAAAAAAAAAAD/AAAAAAAAD/gAAAAAAAD/gAAAAAAD/////4AAAP/////4AAAf/////4AAA//////4AAA//////4AAA//////4AAB//////4AAB//////4AAB//////4AAB//////4AAB//////4AAB/7/gAAAAAB/7/gAAAAAB/7/gAAAAAB///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/A/jwAAAAf/x/34AAAA//5//8AAAB/////+AAAD/////+AAAD/////+AAAH//////AAAH//////AAAH//////AAAH////9/AAAH///v9/AAAH/B/v9/AAAH/B/v9/AAAH/h/v9/AAAH///v9/AAAH///v9/AAAH///P//AAAH///P//AAAH///P/+AAAH//+P/+AAAH//+P/+AAAH//8P/8AAAH//4P/8AAAH//gH/4AAAH+AAD/gAAAH+AAAYAAAAAAAAAAAAAAAAAAAAAAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAAAB/wAAAAAAAD/gAAAAAAAH/gAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAD////4AAAAA////4AAAAAAAAAAAAAGAAAAAAAAAfz////4AAA/7////4AAA/7////4AAB//////4AAB//////4AAB//////4AAB//////4AAB//////4AAA/7////4AAA/7////4AAAfz////4AAACAAAAAAAAAAAAAAAAAAAAAAAAAH/AAHAAAAAP/AAfz//////AA/7//////AA/7//////AB////////AB////////AB////////AB////////AB///////+AA/7/////+AA/7/////8AAfz/////wAAAAAAAAAAAAAAAAAAAAAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAAAAB//4AAAAAAH///AAAAAA////4AAAAD////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH//f/4AAAAH/4H/4AAAAH/gA/4AAAAH+AAP4AAAAHwAAB4AAAAHAAAAYAAAAAAAAAAAAAAAAAAAAAAA//////AAAA//////gAAA//////wAAA//////4AAA//////4AAA//////8AAA//////8AAA//////8AAA//////8AAA//////8AAA//////8AAAAAAAA/8AAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAB////4AAAAB/wAAAAAAAD/gAAAAAAAH/gAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAD////4AAAAB////4AAAAB/wAAAAAAAD/gAAAAAAAH/gAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAB////4AAAAAH///4AAAAAAAAAAAAAAAAAAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAB////4AAAAD/wAAAAAAAD/gAAAAAAAH/gAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAD////4AAAAA////4AAAAAAAAAAAAAAAABQAAAAAAAD//wAAAAAAP//+AAAAAA////AAAAAB////gAAAAB////wAAAAD////wAAAAD////4AAAAH////4AAAAH////8AAAAH////8AAAAH////8AAAAH/gAf8AAAAH/AAf8AAAAH/AAf8AAAAH////8AAAAH////8AAAAH////8AAAAH////4AAAAD////4AAAAD////4AAAAB////wAAAAB////gAAAAA////AAAAAAP//+AAAAAAD//wAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAD//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAD//////AAAD//////AAAH/gA/4AAAAH/gAf8AAAAH/gAf8AAAAH/+H/8AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH////4AAAAH////4AAAAD////wAAAAB////wAAAAA////AAAAAAP//8AAAAAAA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAAAAAH//8AAAAAAf///AAAAAB////gAAAAD////wAAAAD////4AAAAH////4AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH/8H/8AAAAH/gA/8AAAAH/gAf4AAAAD/gA/4AAAAD//////AAAD//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH/////+AAAAAAAAAAAAAAAAAAAAAAAD////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAD/4AAAAAAAH/wAAAAAAAH/wAAAAAAAH/wAAAAAAAH/gAAAAAAAH/gAAAAAAAH/gAAAAAAAAAAAAAAAAAAf/AAAAAAAA//h/4AAAAB//x/4AAAAD//4/4AAAAD//8/4AAAAH//8/8AAAAH//+/8AAAAH//+f8AAAAH///f8AAAAH///f8AAAAH/f//8AAAAH/f//8AAAAH/P//8AAAAH/v//8AAAAH/n//4AAAAH/n//4AAAAH/j//wAAAAH/h//wAAAAD/g//gAAAADwAP+AAAAAAAAAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAH////AAAAD/////gAAAD/////wAAAD/////4AAAD/////8AAAD/////8AAAD/////8AAAD/////8AAAD/////8AAAD/////8AAAD/////8AAAAD/AA/8AAAAD/AA/8AAAAD/AA/8AAAAD/AA/8AAAAD/AA/4AAAAAAAAAAAAAAAAAAAAAAAAH////AAAAAH////wAAAAH////wAAAAH////4AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH////4AAAAAAAA/4AAAAAAAA/4AAAAAAAB/wAAAAD////wAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAAAAAAAAAAAH8AAAAAAAAH/wAAAAAAAH//gAAAAAAH///AAAAAAH///8AAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAA////4AAAAAAf//4AAAAAAAP/4AAAAAAP//4AAAAAf///4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////gAAAAH///wAAAAAH//4AAAAAAH/8AAAAAAAH/AAAAAAAAAAAAAAAAAAH/4AAAAAAAH//+AAAAAAH////gAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAAAf//4AAAAAP///4AAAAH////4AAAAH////4AAAAH////4AAAAH////AAAAAH///AAAAAAH///4AAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAAH///4AAAAAAf//4AAAAD////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH///8AAAAAH//wAAAAAAH/AAAAAAAAAAAAAAAAAAHgAAB4AAAAH8AAH4AAAAH/gA/4AAAAH/+H/4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////gAAAAAP//4AAAAAAP///AAAAAD////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH//f/4AAAAH/4D/4AAAAH/AAf4AAAAHwAAD4AAAAGAAAAYAAAAAAAAAAAAAAH+AAAAAAAAH/wAAH/AAAH//AAH/AAAH//8AH/AAAH///wH/AAAH////H/AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAAP/////AAAAAH////AAAAAB///+AAAAB////+AAAB/////8AAAH/////8AAAH/////wAAAH/////AAAAH////4AAAAH///+AAAAAH///wAAAAAH//8AAAAAAH//AAAAAAAH/wAAAAAAAH8AAAAAAAADAAAAAAAAAAAAAAAAAAAH/gAP4AAAAH/gA/4AAAAH/gD/4AAAAH/gH/4AAAAH/gf/4AAAAH/h//4AAAAH/j//4AAAAH/v//4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH//8/4AAAAH//4/4AAAAH//g/4AAAAH/+A/4AAAAH/4A/4AAAAH/wA/4AAAAH/AA/4AAAAB8AA/4AAAAAAAAAAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAD//////gAAP//////4AAf//////8AA///////+AA///////+AA///////+AA////////AA////////AA////////AA///+////AA///4f///AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////AAf///////AAf///////AAf///////AAf///////AAf///////AAf///////AAf///////AAf///////AAf///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AA///4f///AA///+////AA////////AA////////AA///////+AA///////+AA///////+AA///////+AAf//////8AAP//////4AAD//////gAAAAA/8AAAAAAAAf8AAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAf4AAAAAAAA/4AAAAAAAB/4AAAAAAAB/4AAAAAAAB/4AAAAAAAB/4AAAAAAAB/wAAAAAAAB/gAAAAAAAA/gAAAAAAAA/wAAAAAAAA/wAAAAAAAD/wAAAAAAAD/wAAAAAAAD/wAAAAAAAD/wAAAAAAAD/gAAAAAAAD/AAAAAAAAB+AAAAAAAAAAAAAAAAAAA="),
    32,
    atob("DREbHhswJQ8UExobERYQFx0RGRofGh0ZHBsQERcaFxc2Hh4aIBkYHh8PEB4XKB8gHSEeGhofHykeHRwSFxEYGRYbHBYdGxMcGw4OHA8qGxwcHBQVFBsbIxscGBMQFRo="),
    60|65536
  );
};
// X/Y are the position of the bottom risdvght of the HH:MM text - make it central!
const X = (g.getWidth()/2),
      Y = (g.getHeight()/2);

function draw() {
  
  
  // work out how to displasvy the current time
  var d = new Date();
  var clock = require("locale").time(d, 1 /*omit sesvconds*/);
  var meridian = require("locale").meridian(d);
  // Reset the state of the graphics library
  g.clearRect(0,50,g.getWidth(),100);
  g.reset();
  // draw the current time (4x size 7 segment)
  

  g.setFontAlign(0,1); // align bottom right
  
  
  g.setFontBold();
  g.drawString(" "+clock+" ", X-10, Y, true /*clear background*/);
  // draw the meridian(am/pm) and seconds (2x size 7 segment)
  g.setFont("Teletext10x18Mode7:1");

  g.setFontAlign(-1,1); // align bottom left
  g.drawString(meridian, X+50, Y-10, true /*clear background*/);
  // draw the date, in a normal font
  
  g.setFontAlign(0,1); // align center bottom
  // pad the date - this clears the background if the date were to change length
  var dateStr = require("locale").dow(new Date(), 1)+", "+ require("locale").month(new Date(), true)+" "+new Date().getDate();
  g.drawString(dateStr, g.getWidth()/2, Y+15, true /*clear background*/);
  

  
  
  //WIDGETS
  Bangle.loadWidgets();
  //Draw Bar for widgets
  const top = Bangle.appRect.y; // Usually ~24
  if (top > 0) {
    g.setColor(g.theme.fg);
    g.fillRect(0, 0, g.getWidth(), top);
  }
  Bangle.drawWidgets();
  
  
}

// Clear the screen once, at startup
g.clear();

// draw immediately at first
draw();

// Load the clock infos
let clockInfoItems = require("clock_info").load();

//CLOCK INFO 1 DIMENSIONS: 13,113,w:66,h:55  

let clockInfoMenuLeft = require("clock_info").addInteractive(clockInfoItems, {
  // Add the dimensions we're rendering to here - these are used to detect taps on the clock info area
  x : 13, y: 113, w: 66, h:55,
  // You can add other information here you want to be passed into 'options' in 'draw'
  // This function draws the info
  draw : (itm, info, options) => {
    // itm: the item containing name/hasRange/etc
    // info: data returned from itm.get() containing text/img/etc
    // options: options passed into addInteractive
    // Clear the background
    g.reset().clearRect(options.x-5, options.y-5, options.x+options.w+5, options.y+options.h+5);
    // indicate focus - we're using a border, but you could change color?
    if (options.focus){
      // show if focused
      g.setColor(0,15,255);
      bRoundedRectangle(10,110,82,170,8); 
    }else{
      g.setColor(g.theme.fg);
      bRoundedRectangle(10,110,82,170,8); 
    }
    // we're drawing center-aligned here
    var midx = options.x+options.w/2;
    if (info.img) g.drawImage(info.img, midx-12,options.y+4); // draw the image
    g.setFont("6x8:2").setFontAlign(0,1).drawString(info.text, midx,options.y+44); // draw the text
  }
});


bRoundedRectangle(94,110,166,170,8);  
//CLOCK INFO RIGHT DIMENSIONS: 97,113, w:66, h: 55
let clockInfoMenuRight = require("clock_info").addInteractive(clockInfoItems, {
  // Add the dimensions we're rendering to here - these are used to detect taps on the clock info area
  x : 97, y: 113, w: 66, h:55,
  // You can add other information here you want to be passed into 'options' in 'draw'
  // This function draws the info
  draw : (itm, info, options) => {
    // itm: the item containing name/hasRange/etc
    // info: data returned from itm.get() containing text/img/etc
    // options: options passed into addInteractive
    // Clear the background
    g.reset().clearRect(options.x-5, options.y-5, options.x+options.w+5, options.y+options.h+5);
    // indicate focus - we're using a border, but you could change color?
    if (options.focus){
      // show if focused
      g.setColor(0,15,255);
      bRoundedRectangle(94,110,166,170,8);     
    }else{
      g.setColor(g.theme.fg);
      bRoundedRectangle(94,110,166,170,8);   
    }
    // we're drawing center-aligned here
    var midx = options.x+options.w/2;
    if (info.img) g.drawImage(info.img, midx-12,options.y+4); // draw the image
    g.setFont("6x8:2").setFontAlign(0,1).drawString(info.text, midx,options.y+44); // draw thesv text
  }
});

    
// now drawsv every minute
var secondInterval = setInterval(draw, 60000);
Bangle.setUI("clock");
