
//Initialize Bold Font
Graphics.prototype.setFontBold = function(scale) {
  // Actual height 69 (68 - 0)
  g.setFontCustom(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAfA/////D+D////8f8P////x/w/////H/D////8f4P////w/gYAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/gAAAAAP//wAAAA///AAAAD//8AAAAP//wAAAA///AAAAB//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//8AAAAP//wAAAA///AAAAD//8AAAAP//wAAAA///AAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAD4DwAAAAPgPAAAAA+A8AAAAD4Dx8AAAPj//wAAH////AAP////8AA/////wAD/////AAP///4AAA//wPAAABg+A8AAAAD4DwAAAAPgPAAAAA+A8AAAAD4H/8AAAP///wAD/////AAP////8AA/////wAD////wAAP//jwAAA/PgPAAAAA+A8AAAAD4DwAAAAPgPAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAMAAP/AAPwAB/+AA/gAP/8AB+AB//4AH4AH//wAfgAf//gA+AD8H+AD4APwP8AP/f+AfwA/9/4B/gD/3/gD+AP/f+AP8A/9/4Af4D4APgA/gfgA+AD/j+AD8AH//4APwAf//AAfgA//8AB+AB//gAHAAD/8AAAAAD/AAAAAABgAAAAAAAAAAAAAAAAAAEAAAAAAH/gAAAAB//AAAAAP/+AAAAB//8AAAAH//4AAAA/h/gAAAD4A+AAAAPAB8AAAB8AHwAAAHwAeAAAAPgD4AAAA/w/gAcAD//8AHwAH//wB/AAf/+A/8AA//wP/wAA/8H//AAAEB//gAAAAf/4AAAAP/8AAAAD//AAAAB//wAAAAf/4AAAAH/+AAAAD//A/gAAf/wf/gAB/8D//gAH+Af//AAfgB//8ABwAP//4AEAA/AfgAAAD4A+AAAAfAD4AAAB8APgAAAH4A+AAAAfwH4AAAA///AAAAD//8AAAAH//gAAAAP/8AAAAAf/gAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAAAAAP/AAAAAB/+AAA/AP/8AAP/h//4AB//v//gAP///j/AA///8D8AH///gHwAfh/8AfAB8B/4B8AHwB/4H4A+AH/wPgD8Af/g+AHwD//n4Afg/v/fgB//+P/8AH//wf/wAP/+A//AAf/wB/8AA/+AB/gAA/gAH+AAAABx/8AAAAH//wAAAAf//gAAAB//+AAAAH/z4AAAAf+PgAAAAAA+AAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///AAAAD//8AAAAP//wAAAA///AAAAD//8AAAAP//wAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAH///wAAD////wAA/////wAH/////wB//////gP/8AB//D/8AAA//f+AAAAf9/gAAAAf/8AAAAAffAAAAAA94AAAAABzAAAAAADAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAN4AAAAAB34AAAAAPfwAAAAB9/wAAAAfz/wAAAH/H/wAAD/8P/8AD//gf/////4Af/////AA/////wAA////8AAAf//+AAAAH//AAAAAAAAAAAAAAAAAAAAAAAAAAHA4AAAAB8HwAAAAH4fgAAAAfj+AAAAA/PwAAAAD9+AAAAAH/4AAAAAP/AAAABw/4AAAAH///4AAAf///gAAB///+AAAH///4AAAf///gAAAA/4AAAAAH/wAAAAAffgAAAAD9+AAAAAfz8AAAAB+P4AAAAPwfgAAAAPB8AAAAAIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAf///AAAB///8AAAH///wAAAf///AAAB///8AAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAB4B4AAAAPwPgAAAA//+AAAAH//4AAAAf//AAAAA//4AAAAB/+AAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAfwAAAAAD/gAAAAAP+AAAAAA/4AAAAAD/AAAAAAH8AAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAH4AAAAAH/gAAAAD/+AAAAD//4AAAB///gAAA///wAAA///4AAAf//4AAAf//8AAAP//8AAAP//+AAAH///AAAA///AAAAD//gAAAAP/gAAAAA/wAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAf//4AAAH///4AAA////wAAP////gAB/////AAH////+AA/8AB/8AD+AAB/wAfwAAB/AB+AAAD8AH4AAAP4AfgAAA/gD+AAAD+AH4AAAPwAfgAAA/AB/AAAH8AH/AAA/wAf/AAf+AA/////4AB/////AAH////4AAH///+AAAP///wAAAP//8AAAAD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAAAAD4AAAAAAPgAAAAAA+AAAAAAH4AAAAAAfAAAAAAD/////wAf/////AB/////8AH/////wAf/////AB/////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAPAAPgAAB8AB+AAAPwAH4AAA/AA/AAAH8AD8AAA/wAfgAAH/AB+AAA/8AHwAAH/wAfAAA//AB8AAP/8AH4AB/3wAfgAP+fAB/AD/x8AH+A/+HwAf///wfAA///+B8AD///wHwAH//8AfAAP//gB8AAf/4AHwAAP8AAfAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAHgAAAPAAfAAAA8AD8AAAD4APgAAAPgB+APAA+AH4A+AD4AfAD4APgB8AfgA+AHwB+AH4AfAP4AfAB8A/gB8AH4H+APwAfx/8A/AB///wH4AD/////gAP////8AAf/z//wAA/8P/+AAB/gf/wAAAAA/+AAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAP8AAAAAD/wAAAAA//AAAAAP/8AAAAH//wAAAB///AAAAf//8AAAP//PwAAD//w/AAA//8D8AAP//APwAA//wA/AAD/8AD8AAH+AAPwAAfgAA/AAA4B///8AAAH///wAAAf///AAAB///8AAAH///wAAAf///AAAAAD8AAAAAAPwAAAAAA/AAAAAAD8AAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/4AD4Af//wAPgB///AA+AH//4AD4Af//gAPgB//+AB+AH4D4AH4AfgPgAfAB+A+AD8AH4H4APwAfgfgB/AB+A+AH4AH4D8A/gAfgP4P8AB+A///wAH4B//+AAfgH//wAB+AP/+AAH4Af/wAAcAA/+AAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AAAAAP/+AAAAD//+AAAA///8AAAP///4AAB////wAAP////AAB/8AP+AAP/gAP4AB/3gAfgAH8fAA/AA/j8AB8AH8PgAHwAfg+AAfAD8D4AD8APwPwAPgB+A/AB+AH4D+Af4AfAP///AB8Af//8ADgB///gAAAD//8AAAAH//gAAAAP/4AAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAAAAAfgAAAAAB+AAAAAAH4AAAAAAfgAAABAB+AAAA8AH4AAAPwAfgAAD/AB+AAA/8AH4AAf/wAfgAH//AB+AD//8AH4A//+AAfgf//AAB+H//wAAH7//4AAAf//8AAAB///AAAAH//gAAAAf/wAAAAB/4AAAAAH+AAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAf8AAA/wH/4AAP/g//wAB//H//gAP/+f/+AA/////8AH///wPwAfg/+AfAB8B/wB8AHwD+AHwAfAP4APgD4AfwA+APwB/AD4AfAH+AfgB8A/4B+AH4P/wHwAf///g/AA/////8AD//n//gAH/8P/+AAP/g//wAAf4A/+AAAAAB/wAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+AAAAAP/+AAAAD//8ABAAf//4APAB///gA+AP///AD4A/wf8AfgH8AfwD8AfgA/gPwB8AB+B+AHwAH4P4AfAAfB/AD8AB8P4AHwAHx/gAfAA/f8AB+AA7/gAH+AB/8AAP/9//gAA////8AAB////gAAD///8AAAH///AAAAP//wAAAAH/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAPgAAB/AB/AAAH+AP+AAA/4A/4AAD/gD/gAAP+AP8AAAfwAfwAAA+AA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAOAMAH8AB4B4Af4AP4fwD/gB//+AP+AH//4A/4AP//AB/AA//wAD4AA/+AAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAB+AAAAAAH8AAAAAA/wAAAAAD/gAAAAAf+AAAAAB/8AAAAAP/wAAAAA/fgAAAAD9+AAAAAfj8AAAAB+PwAAAAPw/gAAAA/B+AAAAH4H8AAAAfgPwAAAD8A/AAAAPwB+AAAB/AH4AAAH4AfwAAA/gA/AAAD8AD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAA+A+AAAAD4D4AAAAPgPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAP4AAA/gA/AAAB+AH8AAAH8AfgAAAPwB+AAAA/APwAAAB+A/AAAAH4H8AAAAPwfgAAAA/D+AAAAB+PwAAAAH4/AAAAAP34AAAAA/fgAAAAD/8AAAAAH/wAAAAAf+AAAAAA/4AAAAAD/AAAAAAH8AAAAAAfgAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAfAAAAAAD8AAAAAAPwAAAAAA+AAD8AAD4AAf8AwPwAD/4Pw/AAf/h/D8AD/+H+PwAf/4/4/gB/jj/j+AP4AH8H8B/AAfgf8f4AAIB///gAAAD//8AAAAH//gAAAAP/8AAAAAf/gAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/8AAAAP//+AAAD///+AAA////+AAH////8AA//AD/4AH/AAB/wA/wAAB/gH8AAAD+A/gAfgH8H8Af/gPwfgH//gfj8B///A+PgP//+D5+B///4PnwP+A/gfeA/gA+B/4H4AD4H/gfAAfgf+D8AD+B/wPgAfwH/A+AD+Af8D4A/wB/wPgP+AH/A/H/+Ae8D///+B74H///4Pvgf///g++B///+D74H/+D4fHwf4APgcfB4AB+AB+AAAPwAD8AAB/AAP4AAf4AAf8AP/AAA////4AAB////AAAD///4AAAD//+AAAAD//AAAAAAAAAAAAAAAADwAAAAAB/AAAAAAf8AAAAAP/wAAAAH//AAAAB//8AAAA///gAAAf//wAAAH//4AAAD///AAAB///8AAAf//nwAAH//wfAAAf/4B8AAB/8AHwAAH+AAfAAAf/AB8AAB//gHwAAH//wfAAAH//58AAAD///wAAAB///AAAAB///AAAAA///gAAAAf//wAAAAf//AAAAAP/8AAAAAH/wAAAAAH/AAAAAAD8AAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////+AHwA+AH4AfAD4AfgB8APgB+AHwA+AD4AfAD4APgB8APgA+AHwB+AH4AfAH4AfAB+AfgB8AH8H/AHwAf//8A/AA///4H8AD/////gAH////+AAP/z//4AAf8P//AAAeAP/4AAAAAf/AAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAP//wAAAD///wAAA////gAAH////AAA////+AAD/4D/8AAf8AB/4AD/AAB/gAP4AAD+AA/AAAH8AH4AAAPwAfgAAA/AB+AAAB8AHwAAAH4AfAAAAfgB8AAAB+AHwAAAH4AfAAAAfgB8AAAB8AH4AAAHwAfgAAA/AB+AAAD8AH8AAAPwAPwAAB+AAwAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////8AH/////wAf/////AB/////8AH/////wAf/////AB8AAAB+AHwAAAH4AfAAAAfgB8AAAB+AHwAAAH4AfAAAAfgB8AAAB+AHwAAAHwAfAAAAfAB+AAAD8AH4AAAPwAfwAAB/AA/gAAP4AD/AAD/gAH/gA/8AAf////gAA////+AAB////wAAD///8AAAH///gAAAH//wAAAAD/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////8AH/////wAf/////AB/////8AH/////wAf/////AB8AfgB8AHwB+AHwAfAH4AfAB8AfgB8AHwB+AHwAfAH4AfAB8AfgB8AHwB+AHwAfAH4AfAB8AfgB8AHwA+AHwAfAAAAfAB8AAAB8AHwAAAHwAfAAAAfAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////8AH/////wAf/////AB/////8AH/////wAf/////AB8APgAAAHwA+AAAAfAD4AAAB8APgAAAHwA+AAAAfAD4AAAB8APgAAAHwA+AAAAfAD4AAAB8APgAAAHwA+AAAAfAAAAAAB8AAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAB//wAAAAf//wAAAH///wAAA////gAAH////AAA////+AAH/4D/8AAf8AB/4AD/AAB/gAP4AAB/AB/AAAD8AH4AAAPwAfgAAAfAB8AAAB8AHwAAAH4AfAAAAfgB8AD4B+AHwAPgH4AfAA+AfgB8AD4B8AHwAPgHwAfgA+A/AB+AD//8AH4AP//wAPwA//+AA/AD//4AAAAP//gAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////AB/////8AH/////wAf/////AB/////8AH/////wAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAD4AAAAAAPgAAAAAA+AAAAf/////AB/////8AH/////wAf/////AB/////8AH/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////8AAAAAAAAAAAAAAAHgAAAAAA/AAAAAAD4AAAAAAfgAAAAAH+AAAAAP/wf//////B//////4H//////Af/////4B//////AH/////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////8AAAA/4AAAAAH/AAAAAA/4AAAAAP/AAAAAB/8AAAAAP/8AAAAB//4AAAAf//4AAAD/3/4AAAf+P/wAAD/gP/wAA/8AP/wAH/gAf/gAf8AAf/AB/AAA/8AH4AAA/wAfAAAB/AB4AAAB8AGAAAADwAQAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////AB/////8AH/////wAf/////AB/////8AH/////wAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAB/wAAAB///AAA////8AH/////wAf/////AB/////8AH////wAAf//gAAAB/4AAAAAH/8AAAAAf//AAAAB///AAAAB///gAAAA///wAAAAf//4AAAAH//8AAAAD//+AAAAB//+AAAAAf/4AAAAB//gAAAB//+AAAA///wAAAf//4AAAf//4AAAP//8AAAP//+AAAB///AAAAH//gAAAAf/gAAAAB/4AAAAAH///AAAAf////4AB/////8AH/////wAH/////AAAH///8AAAAH//wAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////8AD/wAAAAAH/wAAAAAH/wAAAAAP/gAAAAAP/gAAAAAf/AAAAAAf/AAAAAA/+AAAAAA/+AAAAAB/+AAAAAB/8AAAAAB/8AAAAAD/4AAAAAD/4AAAAAH/wAAAAAH/wAf/////AB/////8AH/////wAf/////AB/////8AH/////wAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAf//wAAAD///wAAA////gAAH////AAA////+AAH/8D/8AAf8AB/4AD/AAB/gAP4AAD/AA/AAAD8AH4AAAPwAfgAAAfAB8AAAB+AHwAAAH4AfAAAAfgB8AAAB+AHwAAAH4AfAAAAfAB+AAAD8AH4AAAPwAfwAAB/AA/wAAP4AD/wAD/gAH/4B/8AAP////gAAf///8AAB////gAAB///8AAAD///AAAAB//wAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////8AH/////wAf/////AB/////8AH/////wAf/////AB8AB+AAAHwAD4AAAfAAPgAAB8AA+AAAHwAD4AAAfAAfgAAB8AB+AAAHwAHwAAAfgAfAAAB/AD8AAAH+A/wAAAP//+AAAA///4AAAB///AAAAH//4AAAAH//AAAAAP/4AAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+AAAAB///AAAAP///AAAD///+AAAf///8AAD////4AAf/wP/wAB/wAH/gAP8AAH+AA/gAAP8AD8AAAPwAfgAAA/AB+AAAB8AHwAAAH4AfAAAAfgB8AAAB/AHwAAAH+AfAAAAf8B8AAAB/4H4AAAP/wfgAAA//B/AAAH/+D/AAA/n4P/AAP+fgf/gH/x+A////+H4B////wfgH///+B+AH///wH4AP//8APAAH//AAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////8AHwAfAAAAfAB8AAAB8AHwAAAHwAfAAAAfAB8AAAB8AHwAAAHwAfgAAAfAB/AAAB8AP/AAAH4A//AAAfwP//gAA/////gAD/////gAH//z//AAf/+D/8AA//wD/wAA/+AD/AAA/AAD8AAAAAADwAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAD/AAB4AAf+AAfgAD/8AB/AAf/8AD8AD//wAPwAP//gAfAB/H/AB8AH4H8AH4Afgf4AfgB8A/gB+AHwB/AH4AfAH8AfgB8AP4B+AHwA/wHwAfAB/g/AB8AH/P8AH4AP//wAfgAf/+AA/AB//4AD4AD//AAAAAD/4AAAAAH+AAAAAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAH/////wAf/////AB/////8AH/////wAf/////AB/////8AHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///+AAAf////AAB/////AAH////+AAf////8AB/////4AD/////gAAAAAH/AAAAAAH8AAAAAAPwAAAAAAfAAAAAAB+AAAAAAH4AAAAAAfgAAAAAB+AAAAAAH4AAAAAAfgAAAAAD8AAAAAAfwAAAAAD/AAAAAH/4AH/////gAf////8AB/////gAH////8AAf////AAB////gAAAAAAAAAAcAAAAAAB+AAAAAAH/AAAAAAf/gAAAAB//gAAAAH//wAAAAf//4AAAAP//4AAAAH//8AAAAD//+AAAAB//+AAAAA///AAAAAf//AAAAAf/+AAAAAP/4AAAAAP/gAAAAH/+AAAAD//4AAAB//+AAAA///AAAAf//gAAAP//4AAAH//8AAAD//+AAAAf//AAAAB//wAAAAH/4AAAAAf8AAAAAB+AAAAAAHgAAAAAAAAAAAAABwAAAAAAH8AAAAAAf/AAAAAB//gAAAAH//4AAAAf//+AAAB////gAAAf///wAAAH///8AAAA///+AAAAP//4AAAAD//gAAAAB/+AAAAB//4AAAB///gAAA///4AAA///8AAAf//8AAAf//+AAAH//+AAAAf//AAAAB//AAAAAH//gAAAAf//wAAAA///8AAAAf//+AAAAH///gAAAD///wAAAA///4AAAAf//gAAAAH/+AAAAAD/4AAAAH//gAAAP//+AAAP///wAAf///4AAf///4AAH///4AAAf//4AAAB//4AAAAH/4AAAAAf8AAAAAB8AAAAAAAAAAAAAAAAAAAAABgAAAAMAHgAAADwAfAAAAfAB/AAAH8AH+AAB/wAf+AAP/AB/+AD/8AD/8A//AAD/8H/4AAH/5/+AAAH///gAAAH//4AAAAP//AAAAAP/wAAAAAf/AAAAAD//AAAAA///AAAAP//+AAAD/8/+AAAf/B/+AAH/4B/+AB/+AD/8AH/wAD/wAf8AAH/AB/AAAH8AH4AAAPwAeAAAAPABgAAAAMAAAAAAAQAAAAAAAABwAAAAAAHwAAAAAAfwAAAAAB/wAAAAAH/gAAAAAf/gAAAAA//gAAAAA//gAAAAB//gAAAAB//gAAAAB//gAAAAB////AAAB///8AAAB///wAAAH///AAAB///8AAAf///wAAH/+AAAAB//gAAAAf/4AAAAH/+AAAAB//gAAAAH/4AAAAAf+AAAAAB/gAAAAAH4AAAAAAfAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAHwAfAAAB/AB8AAAP8AHwAAD/wAfAAAf/AB8AAH/8AHwAA//wAfAAP//AB8AD/98AHwAf/nwAfAH/4fAB8A//B8AHwP/wHwAfB/+AfAB8f/gB8AHz/4AHwAf//AAfAB//wAB8AH/+AAHwAf/gAAfAB/8AAB8AH/AAAHwAfwAAAfAB+AAAB8AHgAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////h///////P//////8///////7///////v//////++AAAAAD74AAAAAPvgAAAAA8+AAAAADx4AAAAAPHgAAAAA8AAAAAAADgAAAAAAP4AAAAAA/8AAAAAD//AAAAAP//gAAAA///4AAAAf//8AAAAH///AAAAD///gAAAA///wAAAAf//8AAAAH//+AAAAD///gAAAA//+AAAAAf/4AAAAAP/gAAAAAD+AAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAA8eAAAAADz4AAAAAPPgAAAAA8+AAAAAD74AAAAAPv//////+///////7///////v//////8f//////w//////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAD4AAAAAA/gAAAAAf+AAAAAH/4AAAAD//gAAAA//+AAAAf//AAAAH//gAAAB//4AAAAH/8AAAAAf+AAAAAB/+AAAAAH//AAAAAP//gAAAAH//gAAAAH//wAAAAD//gAAAAD/+AAAAAB/4AAAAAB/gAAAAAA+AAAAAAA4AAAAAAAAAAAAAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAAAfAAAAAAAAAAAAAAABgAAAAAAPgAAAAAB/AAAAAAP+AAAAAA/4AAAAAA/wAAAAAB/gAAAAAD/AAAAAAH8AAAAAAPwAAAAAAeAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAMAP+AAAB8B/8AAAHwP/4AAA/A//wAAD8H//AAAPgf/+AAA+B8H4AAH4PwfgAAfg+A+AAB+D4D4AAH4PgfAAAfg8B8AAB+DwHwAAH+PA+AAAP///8AAA////wAAD////AAAH///8AAAP///wAAAP///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////4A//////gD//////AP/////8A//////wD//////AAAHwAB+AAA/AAH4AAD4AAPgAAPgAA+AAB+AAD4AAH4AAfgAAfgAB8AAB+AAHwAAH8AA/AAAP4AP8AAA/+H/gAAD///8AAAH///wAAAP//+AAAAf//gAAAA//8AAAAA/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAH/4AAAAB//4AAAAf//4AAAD///wAAAP///gAAB///+AAAP+Af8AAA/gAfwAAD8AA/AAAPgAB8AAB+AAH4AAH4AAfgAAfgAB+AAB+AAHwAAH4AAfAAAfgAB8AAA+AAHwAAD8AA+AAAPwAD4AAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/gAAAAD//wAAAAf//gAAAH///AAAA///+AAAH///4AAAf///wAAD/AD/AAAPwAD8AAA+AAH4AAH4AAfgAAfAAB+AAB8AAH4AAHwAAfAAAfAAB8AAB+AAPwAAD4AA+AP/////8A//////wD//////AP/////8A//////wD//////AAAAAAAAAAAAAAAAAAAAAAAAAAAP/AAAAAH//AAAAA///AAAAH///AAAA///8AAAH///4AAA////wAAD+Ph/AAAPw+D8AAB+D4P4AAHwPgfgAAfA+B+AAB8D4H4AAH4PgfgAAfg+B+AAA/j4HwAAD//gfAAAH/+B8AAAf/4PwAAA//g+AAAA/+B4AAAB/4AAAAAAAAAAAAAAAAAAAAHwAAAAAAfAAAAAAB8AAAAAAHwAAAAA/////4AP/////gB/////+AP/////4A//////gH/////+AfwfAAAAB8B8AAAAPwHwAAAA/AfAAAAD8B8AAAAPwHwAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAH4AAP+Ag/wAB/8P3/wAP/7///AB/////+AP/////4A////8/gD8H//A/APgPx8B8B8AeHwHwHwB8fAfAfAHx8B8B8AfHwHwHwB4fAfAfgPh8B8A/B+H4HgD//4fg+AP//B/H4A//8H//gD//gP/8AP/8A//wA//AD/+AH4AAH/wAfgAAH+AB+AAADAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////AP/////8A//////wD//////AP/////8A//////wAAB+AAAAAAHwAAAAAA/AAAAAAD4AAAAAAPgAAAAAB+AAAAAAH4AAAAAAfgAAAAAB+AAAAAAH+AAAAAAf///8AAA////wAAD////AAAH///8AAAP///wAAAP///AAAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAH8P///8Afw////wD/D////AP8P///8A/w////wB+D////ADwAAAAAAAAAAAAAAAAAAAAAQAAAAAABAAAAAAAM+AAAAAH38P/////fw///////D//////8P//////w/////9+D////+DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////AP/////8A//////wD//////AP/////8A//////wAAAAf4AAAAAD/AAAAAAf4AAAAAD/wAAAAAf/wAAAAD//gAAAA///gAAAH/f/AAAA/4/+AAAD/A/+AAAP4B/8AAA/AB/wAAD4AD/AAAOAAD8AAAwAAHwAACAAAHAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////8A//////wD//////AP/////8A//////wD//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////AAAP///8AAA////wAAD////AAAP///8AAA////wAAB+AAAAAAHwAAAAAA/AAAAAAD4AAAAAAPgAAAAAA+AAAAAAH4AAAAAAfgAAAAAB/AAAAAAH/AAAAAAf///8AAA////wAAD////AAAH///8AAAP///wAAA////AAAH4AAAAAAfAAAAAAD8AAAAAAPgAAAAAB+AAAAAAH4AAAAAAfgAAAAAB+AAAAAAH8AAAAAAf///8AAB////wAAD////AAAP///8AAAf///wAAA////AAAAf//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////AAAP///8AAA////wAAD////AAAP///8AAA////wAAB+AAAAAAHwAAAAAA/AAAAAAD4AAAAAAPgAAAAAA+AAAAAAH4AAAAAAfgAAAAAB+AAAAAAH+AAAAAAf///8AAA////wAAD////AAAH///8AAAP///wAAAf///AAAAAAAAAAAAAAAAAAAA/4AAAAAP/8AAAAD//8AAAAf//4AAAD///wAAAf///gAAB////AAAP8AP8AAA/AAPwAAH4AAfAAAfgAB+AAB8AAD4AAHwAAPgAAfAAB+AAB+AAHwAAD8AA/AAAP4AH8AAA/8B/wAAB///+AAAH///wAAAP///AAAAf//4AAAAf/+AAAAAf/gAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////AP/////8A//////wD//////AP/////8A//////wB8AAfAAAPwAB8AAA+AAH4AAD4AAPgAAfgAA+AAB+AAH4AAH4AAfAAAfgAB8AAB/AAPwAAD+AD/AAAP/B/4AAA////gAAB///8AAAD///gAAAH//8AAAAP//AAAAAP/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/gAAAAD//wAAAAf//gAAAH///AAAA///+AAAH///4AAAf///wAAD/AD/AAAPwAD8AAA+AAH4AAH4AAfgAAfAAB+AAB8AAH4AAHwAAfAAAfAAB8AAB+AAPwAAD4AA+AAAP/////8A//////wD//////AP/////8A//////wD//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///8AAA////wAAD////AAAP///8AAA////wAAB////AAAH4AAAAAA/AAAAAAD8AAAAAAPgAAAAAB+AAAAAAH4AAAAAAfgAAAAAB+AAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AD4AAAP+APwAAB/8A/AAAH/4B8AAA//wHwAAD//AfAAAPj+B+AAA+H8H4AAH4fwfgAAfA/B+AAB8D+H4AAHwH8fAAAfgf/8AAA+A//wAAD4D/+AAAPwH/4AAA+AP/AAAAAAf4AAAAAAAAAAAAAAAAAAD4AAAAAAPgAAAAAA+AAAAAAP///4AAH////4AA/////wAD/////AAP////8AA/////4AAH4AB/gAAPgAB+AAA+AAH4AAD4AAfAAAPgAB8AAA+AAHwAAD4AA+AAAPAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAf/4AAAAD///wAAAP///wAAA////gAAD////AAAP///8AAA////wAAAAAB/gAAAAAB+AAAAAAH4AAAAAAfgAAAAAB8AAAAAAHwAAAAAAfAAAAAAD4AAAAAAPgAAD///+AAAP///8AAA////4AAD////gAAP///+AAA////4AAAAAAAAAAOAAAAAAA+AAAAAAD/AAAAAAP/gAAAAA//gAAAAD//wAAAAP//wAAAAH//4AAAAD//4AAAAB//8AAAAA//4AAAAAf/gAAAAAP+AAAAAH/4AAAAD//gAAAB//8AAAA///AAAAf//gAAAP//wAAAA//8AAAAD/+AAAAAP/AAAAAA/wAAAAAD4AAAAAAMAAAAAAAAAAAAAADgAAAAAAP4AAAAAA/8AAAAAD/+AAAAAP//gAAAA///wAAAB///4AAAAf//8AAAAH//4AAAAD//gAAAAA/+AAAAAf/4AAAAP//gAAAP//8AAAP//+AAAD///AAAAP//AAAAA//AAAAAD/gAAAAAP/4AAAAA//+AAAAD///AAAAB///wAAAA///4AAAAP//gAAAAD/+AAAAAD/4AAAAD//gAAAD//+AAAD///gAAB///wAAAP//4AAAA//8AAAAD/8AAAAAP+AAAAAA/AAAAAADAAAAAAAAAAAAAAAwAAAwAADgAAPAAAPgAB8AAA/AAPwAAD/AD/AAAP+Af8AAA/8H/wAAB/8/+AAAB///gAAAD//4AAAAD//AAAAAH/wAAAAAf/gAAAAD//AAAAA///AAAAH//+AAAB/4/+AAAP/B/8AAA/4B/wAAD+AD/AAAPwAD8AAA+AAHwAADgAAPAAAMAAAMAAAAAAAQAAAAAAAAAAAAAAAAADAAAAAAAPgAAAAAA/wAAAPgD/4AAA/AP/8AAD8A//8AAPwD//+AA/AD///AH4AB///g/gAAf//H+AAAP///wAAAH//+AAAAD//wAAAA//+AAAAf//gAAAf//4AAAP//+AAAP///AAAD///AAAAP//gAAAA//wAAAAD/4AAAAAP8AAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAA8AAA+AAHwAAD4AB/AAAPgAP8AAA+AD/wAAD4Af/AAAPgH/8AAA+A//wAAD4P//AAAPh/98AAA+f/nwAAD7/4fAAAP//B8AAA//wHwAAD/+AfAAAP/gB8AAA/8AHwAAD/AAfAAAP4AB8AAA+AAHwAADwAAPAAAAAAAAAAAAAAAAAAAAPAAAAAAA+AAAAAAD4AAAAAAfgAAAAAB/AAAAAAP+AAAP//////B///////P///f//8///5///7///j///v//8H//++AAAAAD74AAAAAPvgAAAAA++AAAAADz4AAAAAPHgAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////v/////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAA8+AAAAADz4AAAAAPPgAAAAA++AAAAAD74AAAAAPv//8H//+///4///7///n///v///f//8f//////w//////+AAAP+AAAAAAfwAAAAAB+AAAAAAD4AAAAAAPgAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAA8AAAAAAH4AAAAAA/gAAAAAD8AAAAAAfgAAAAAB+AAAAAAH4AAAAAAfgAAAAAB/AAAAAAD8AAAAAAP4AAAAAAfwAAAAAA/AAAAAAD8AAAAAAPwAAAAAAfAAAAAAD8AAAAAAPwAAAAAB/AAAAAAP4AAAAAAfAAAAAAA4AAAAAABAAAAAAAAAAAAA"), 32, atob("CAwZIBwtIg0RERocDBkMFB4PGxkeGh0bHB0MDRsbHBYtIB4dIRsZHyALDR8ZKSAjHSMfGR0fHywfHR0RExAcJw4XGxcaGRMdGwwMGwsqGhsbGhMVExkaJhoaFxQNFh0="), 46|65536);
};

{ // must be inside our own scope here so that when we are unloaded everything disappears
  // we also define functions using 'let fn = function() {..}' for the same reason. function decls are global
let drawTimeout;

//ROUNDED RECT FUNCTION
let bRoundedRectangle= function(x1,y1,x2,y2,r) {
    var f = 1 - r;
    var ddF_x = 0;
    var ddF_y = -2 * r;
    var x = 0;
    var y = r;
    g.drawLine(x1+r,y1,x2-r,y1);
    g.drawLine(x1+r,y2,x2-r,y2);
    g.drawLine(x1,y1+r,x1,y2-r);
    g.drawLine(x2,y1+r,x2,y2-r);
    var cx1=x1+r;
    var cx2=x2-r;
    var cy1=y1+r;
    var cy2=y2-r;
    while(x < y)
    {
      if(f >= 0)
      {
        y--;
        ddF_y += 2;
        f += ddF_y;
      }
      x++;
      ddF_x += 2;
      f += ddF_x + 1;
      g.setPixel(cx2 + x, cy2 + y);
      g.setPixel(cx1 - x, cy2 + y);
      g.setPixel(cx2 + x, cy1 - y);
      g.setPixel(cx1 - x, cy1 - y);
      g.setPixel(cx2 + y, cy2 + x);
      g.setPixel(cx1 - y, cy2 + x);
      g.setPixel(cx2 + y, cy1 - x);
      g.setPixel(cx1 - y, cy1 - x);
    }
  };
  
  
  
//CLOCK INFO
let clockInfoItems = require("clock_info").load();

  

//CLOCK INFO 1 DIMENSIONS: 13,103,w:66,h:65  

let clockInfoMenuLeft = require("clock_info").addInteractive(clockInfoItems, {
    // Add the dimensions we're rendering to here - these are used to detect taps on the clock info area
    x : 13, y: 103, w: 66, h:65,
  // You can add other information here you want to be passed into 'options' in 'draw'
  // This function draws the info
  draw : (itm, info, options) => {
    // itm: the item containing name/hasRange/etc
    // info: data returned from itm.get() containing text/img/etc
    // options: options passed into addInteractive
    // Clear the background
    g.reset().clearRect(options.x-5, options.y-5, options.x+options.w+5, options.y+options.h+5);
    // indicate focus - we're using a border, but you could change color?
    if (options.focus){
      // show if focused
      g.setColor(0,15,255);
      bRoundedRectangle(10,100,82,170,8); 
    }else{
      g.setColor(g.theme.fg);
      bRoundedRectangle(10,100,82,170,8); 
    }
    // we're drawing center-aligned here
    var midx = options.x+options.w/2;
    var midy=options.y+options.h/2;
    if (info.img){
      g.drawImage(info.img, midx-12,midy-21);
    }// draw the image
    g.setFont("6x8:2").setFontAlign(0,1).drawString(info.text, midx,midy+21); // draw the text
  }
});



//CLOCK INFO RIGHT DIMENSIONS: 97,113, w:66, h: 55
let clockInfoMenuRight = require("clock_info").addInteractive(clockInfoItems, {
  // Add the dimensions we're rendering to here - these are used to detect taps on the clock info area
  x : 97, y: 103, w: 66, h:65,
  // You can add other information here you want to be passed into 'options' in 'draw'
  // This function draws the info
  draw : (itm, info, options) => {
    // itm: the item containing name/hasRange/etc
    // info: data returned from itm.get() containing text/img/etc
    // options: options passed into addInteractive
    // Clear the background
    g.reset().clearRect(options.x-5, options.y-5, options.x+options.w+5, options.y+options.h+5);
    // indicate focus - we're using a border, but you could change color?
    if (options.focus){
      // show if focused
      g.setColor(0,15,255);
      bRoundedRectangle(94,100,166,170,8);  
    }else{
      g.setColor(g.theme.fg);
      bRoundedRectangle(94,100,166,170,8);     
    }
    // we're drawing center-aligned here
    var midx = options.x+options.w/2;
    var midy=options.y+options.h/2;
    if (info.img){
      g.drawImage(info.img, midx-12,midy-21);
    }// draw the image
    g.setFont("6x8:2").setFontAlign(0,1).drawString(info.text, midx,midy+21); // draw the text
  }
});


  
  
  
  

// DRAW FACE
let draw = function() {
  var X = g.getWidth() / 2;
  var Y = (g.getHeight() / 2)-15;
  g.reset();
  var d = new Date();
  var clock = require("locale").time(d, 1 /*omit seconds*/);
  var meridian = require("locale").meridian(d);
  // draw the current time (4x size 7 segment)

   // align bottom right

  g.setFontBold();
  g.setFontAlign(0,1);
  g.drawString(" "+clock+" ", X-10, Y+1, true /*clear background*/);
  // draw the meridian(am/pm) and seconds (2x size 7 segment)
  
  g.setFont("Vector",20);

  g.setFontAlign(-1,1); // align bottom left
  g.drawString(meridian, X+50, Y-10, true /*clear background*/);
  // draw the date, in a normal font

  g.setFontAlign(0,1); // align center bottom
  // pad the date - this clears the background if the date were to change length
  var dateStr = require("locale").dow(new Date(), 1)+", "+ require("locale").month(new Date(), true)+" "+new Date().getDate();
  g.drawString(" "+dateStr+" ", g.getWidth()/2, Y+16, true /*clear background*/);
  
  
  
  // queue next draw
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = setTimeout(function() {
    drawTimeout = undefined;
    draw();
  }, 60000 - (Date.now() % 60000));
};

  

  
// Show launcher when middle button pressed
Bangle.setUI({
  mode : "clock",
  remove : function() {
    // Called to unload all of the clock app
    if (drawTimeout) clearTimeout(drawTimeout);
    drawTimeout = undefined;
    delete Graphics.prototype.setFontBold;
    delete Graphics.prototype.setFontTeletext10x18Mode7;
    clockInfoMenuRight.remove();
    clockInfoMenuLeft.remove();
    
  }});
  
g.clear();
// Load widgets
Bangle.loadWidgets();
draw();
setTimeout(Bangle.drawWidgets,0);
}
