

//Function for rounded rectangle
function bRoundedRectangle (x1,y1,x2,y2,r) {
    var f = 1 - r;
    var ddF_x = 0;
    var ddF_y = -2 * r;
    var x = 0;
    var y = r;
    g.drawLine(x1+r,y1,x2-r,y1);
    g.drawLine(x1+r,y2,x2-r,y2);
    g.drawLine(x1,y1+r,x1,y2-r);
    g.drawLine(x2,y1+r,x2,y2-r);
    var cx1=x1+r;
    var cx2=x2-r;
    var cy1=y1+r;
    var cy2=y2-r;
    while(x < y)
    {
      if(f >= 0)
      {
        y--;
        ddF_y += 2;
        f += ddF_y;
      }
      x++;
      ddF_x += 2;
      f += ddF_x + 1;
      g.setPixel(cx2 + x, cy2 + y);
      g.setPixel(cx1 - x, cy2 + y);
      g.setPixel(cx2 + x, cy1 - y);
      g.setPixel(cx1 - x, cy1 - y);
      g.setPixel(cx2 + y, cy2 + x);
      g.setPixel(cx1 - y, cy2 + x);
      g.setPixel(cx2 + y, cy1 - x);
      g.setPixel(cx1 - y, cy1 - x);
    }
  }
// Load fonts
require("FontTeletext10x18Mode7").add(Graphics);
Graphics.prototype.setFontBold = function() {
  // Actual height 55 (55 - 1)
  // 1 BPP
  return this.setFontCustom(
    atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAHAAAAf///8fwAAAf///8/4AAAf///8/8AAAf///9/8AAAf///9/8AAAf///9/8AAAf///9/8AAAf///9/8AAAf///8/4AAAf///8/4AAAf/wAAPwAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAPw8AAAAAAAf58AAAAAAA//8AAAAAAA//8AAAAAAA//8AAAAAAA//4AAAAAAA//wAAAAAAA//wAAAAAAA//AAAAAAAAf+AAAAAAAAP8AAAAAAAABAIAAAAAAAPw8AAAAAAAf58AAAAAAA//8AAAAAAA//8AAAAAAA//8AAAAAAA//4AAAAAAA//wAAAAAAA//wAAAAAAA//AAAAAAAAf+AAAAAAAAP8AAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/AAAAAAB/3/AAAAAAB/3/P4AAAAB/3//4AAAAB////4AAAAB////4AAAD/////4AAAP/////4AAAP/////4AAAP/////4AAAP/////4AAAP////8AAAAP/////4AAAP//z//4AAAP/////4AAAGf////4AAAP/////4AAAP/////4AAAP/////4AAAP/////4AAAP/////wAAAP////AAAAAP////AAAAAP//3/AAAAAPx/3/AAAAAAB/3/AAAAAAB/wAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAAAAAB//wD/wAAAD//4D/4AAAH//8D/4AAAP//+B/4AAAP//+B/4AAAf///B/4AAAf///B/8AAf////g//wAf////w//wAf////w//wAf////4//wAf/+f////wAf/+P////wAf/+H////wAf/+H////wAf/+D////wAAf+D///4AAAf/B///4AAAf/B///wAAAf/A///gAAAf/Af//AAAAf+AH/+AAAAIAAD/4AAAAAAAAAAAAAAAAAAAAAAAAAf/8AAAAAAD///AAAAAAH///wAAAAAP///4AAAAAf///4AAAAAf///8AAAAA////8AAAAA////8AAAAA/wAH8AAAAA/wAH8AAAAA/wAH8AAAAA////8AAAAAf///8AAAAAf///8AIAAAf///4B8AAAP///4f8AAAH///3/8AAAD/////8AAAAf////8AAAAAB///8AAAAAf///8AAAAD////8AAAA/////AAAAP////4AAAA////+AAAAA////wAAAAA///8YAAAAA/////8AAAA//////gAAA/+P///wAAA/wf///wAAA8Af///4AAAAA////4AAAAA////8AAAAA////8AAAAA/wAP8AAAAA/gAH8AAAAA/wAf8AAAAA////8AAAAA////8AAAAA////4AAAAAf///4AAAAAP///wAAAAAH///gAAAAAD//+AAAAAAAP/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/4AAAAAAAH/+AAAAAAAP//AAAAA/gf//gAAAD/8///wAAAP/////wAAAP/////4AAAf/////4AAAf/////4AAA//////8AAA////7/8AAA////w/8AAA////4f8AAA////8f8AAB/8f/+f8AAB/8f///8AAA//////8AAA//////4AAA//////4AAA//////4AAA///3//wAAAf//j//wAAAf//h//4AAAP//A//4AAAH/+///4AAAB/w///8AAAAAA///8AAAAAA///8AAAAAA///8AAAAAA///8AAAAAA//f8AAAAAA/+f8AAAAAAfwf8AAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAPw8AAAAAAAf58AAAAAAA//8AAAAAAA//8AAAAAAA//8AAAAAAA//4AAAAAAA//wAAAAAAA//wAAAAAAA//AAAAAAAAf+AAAAAAAAP8AAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//wAAAAAA///+AAAAAH////gAAAAf////4AAAA/////+AAAD//////AAAH//////wAAP//////4AAf//////8AB///////+AB///////+AA///////+AA///AD//+AA//gAAH/8AAf+AAAA/8AAfwAAAAH8AAPAAAAAB4AAOAAAAAA4AAAAAAAAAAAAMAAAAAAYAAPAAAAAB4AAfwAAAAH8AAf+AAAA/8AA//gAAH/8AA///AB//+AA///////+AB///////+AB///////+AA///////8AAP//////4AAH//////wAAD//////gAAA/////+AAAAf////4AAAAH////wAAAAA///+AAAAAAH//wAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAB/gAAAAAAAB/w4AAAAAAA/z4AAAAAAA/38AAAAAAA//+AAAAAAA//+AAAAAAB///AAAAAAf///AAAAAAf//8AAAAAAf//4AAAAAAf//wAAAAAAf//wAAAAAAf//4AAAAAAf//8AAAAAAf//+AAAAAAAf//AAAAAAA//+AAAAAAA//+AAAAAAA/z8AAAAAAA/x4AAAAAAA/g4AAAAAAAfgAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAH///8AAAAAP///8AAAAAP///8AAAAAP///8AAAAAP///8AAAAAP///8AAAAAP///8AAAAAP///8AAAAAH///4AAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgYAAAAAAA/x4AAAAAAA/78AAAAAAB//8AAAAAAB//8AAAAAAB//4AAAAAAB//wAAAAAAB//wAAAAAAA//gAAAAAAA/+AAAAAAAAf8AAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAfwAAAAAAAA/4AAAAAAAA/8AAAAAAAB/8AAAAAAAB/8AAAAAAAB/8AAAAAAAB/8AAAAAAAB/8AAAAAAAA/4AAAAAAAA/4AAAAAAAAPwAAAAAAAAAAAAAAAAAAAH/AAAAAAAA//AAAAAAAP//AAAAAAD///AAAAAAf///AAAAAH////AAAAA/////AAAAP/////AAAB//////AAAf//////AAH//////wAAf/////+AAAf/////gAAAf////4AAAAf////AAAAAf///wAAAAAf//+AAAAAAf//gAAAAAAf/8AAAAAAAf/AAAAAAAAf4AAAAAAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAP///wAAAAB////+AAAAD/////AAAAH/////gAAAP/////wAAAP/////4AAAf/////4AAAf/////4AAAf/////8AAA//////8AAA//gAD/8AAA/+AAA/8AAA/8AAA/8AAA/+AAA/8AAA//AAB/8AAA//////8AAAf/////8AAAf/////4AAAf/////4AAAP/////4AAAP/////wAAAH/////gAAAD/////AAAAB////+AAAAAf///4AAAAAB//+AAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAAH/AAAAAAAAH/AAAAAAAAP/AAAAAAAAP/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAAAAAAAAH4AAAAAAAAH/gAAf4AAAP/wAA/4AAAP/gAB/4AAAf/gAD/4AAAf/gAH/4AAAf/AAP/4AAAf/AAf/4AAAf/AB//4AAA//AD//4AAA//AP//4AAA//Af//4AAA//j///4AAA//////4AAAf/////4AAAf/////4AAAf/////4AAAf///9/4AAAP///5/4AAAP///x/4AAAH///B/4AAAD//+B/4AAAB//4B/4AAAAf/AB/4AAAAAAAAAAAAACAAAAAAAAAHwAAAAgAAAH+AAAPwAAAP/gAD/wAAAP/AAD/4AAAf/AAD/4AAAf/H/D/4AAAf+H/B/4AAAf+H/B/8AAAf+H/B/8AAA/+H/h/8AAA/+H/h/8AAA////h/8AAA//////8AAA//////8AAA//////8AAAf/////4AAAf/////4AAAf/////4AAAf/////wAAAP/////wAAAH//P//gAAAD/+P//AAAAB/8D/+AAAAAHgB/4AAAAAAAAAAAAAAAAAB4AAAAAAAAD/wAAAAAAAP/wAAAAAAA//wAAAAAAD//wAAAAAAP//wAAAAAA///wAAAAAD///wAAAAAH///wAAAAAf///wAAAAB////wAAAAH////wAAAAf//5/wAAAAf//h/wAAAAf/+B/wAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///D/wAAAf///D/4AAAf///D/4AAAf///j/4AAAf///j/4AAAf///h/8AAAf///h/8AAAf///h/8AAAf///h/8AAAf///B/8AAAf+H/B/8AAAf+P/3/8AAAf+P///8AAAf+P///8AAAf+P///4AAAf+H///4AAAf+H///4AAAf+H///wAAAf+D///gAAAf+D///gAAAf+B//+AAAAAAAP/4AAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAH//AAAAAAA///4AAAAAH///+AAAAAP////AAAAAf////gAAAB/////wAAAB/////wAAAD/////4AAAH/////4AAAH/////4AAAP/////8AAAP///D/8AAAP/3/A/8AAAf/H/A/8AAAf/H/A/8AAAf+P/h/8AAAf+P///8AAAf+H///8AAA/8H///4AAA/8H///4AAA/8H///4AAA/8D///wAAA/8D///gAAAQAB///AAAAAAA//+AAAAAAAP/4AAAAAAAAIAAAAAAAAAAAAAAAf/AAAAAAAAf/AAAAAAAAf/AAAA4AAAf/AAAH4AAAf/AAA/4AAAf/AAH/4AAAf/AAf/4AAAf/AD//4AAAf/Af//4AAAf/D///4AAAf/P///4AAAf/////4AAAf/////4AAAf/////4AAAf/////wAAAf////+AAAAf////wAAAAf///+AAAAAf///gAAAAAf//8AAAAAAf//gAAAAAAf/8AAAAAAAf/gAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAGAAAAAAf4B/8AAAAB/+D//AAAAD//n//gAAAH/////gAAAP/////wAAAP/////wAAAf/////4AAAf/////4AAAf/////4AAAf/////8AAA//////8AAA/8P/w/8AAA/8H/gf8AAA/8H/wf8AAA/8P/4/8AAA//////8AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAP/////wAAAH/////wAAAH//v//gAAAB/+H//AAAAA/8D/8AAAAAAAAfgAAAAAAAAAAAAAAAf/gAAAAAAB//4AAAAAAD//+AB4AAAH//+A/8AAAP///A/8AAAP///g/8AAAf///g/8AAAf///g/8AAAf///g/8AAAf///h/4AAA/+H/h/4AAA/8B/j/4AAA/8B/j/4AAA/8B/v/4AAA//B///wAAA//////wAAAf/////gAAAf/////gAAAf/////AAAAP////+AAAAP////+AAAAH////4AAAAD////wAAAAB////AAAAAAf//8AAAAAAD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAfwAAAAAf4A/4AAAAA/8A/4AAAAA/8B/8AAAAA/8B/8AAAAA/8B/8AAAAA/8B/8AAAAA/8B/8AAAAA/8A/8AAAAAf4A/4AAAAAPwAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAPwAfw4AAAAf4A/58AAAA/8A//8AAAA/8B//8AAAA/8B//8AAAA/8B//4AAAA/8B//wAAAA/8B//gAAAA/8A//AAAAAf4A/+AAAAAPwAf8AAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAf4AAAAAAAA/4AAAAAAAB/8AAAAAAAD/+AAAAAAAH//AAAAAAAP//gAAAAAAf//wAAAAAA///4AAAAAB///8AAAAAB///+AAAAAD////AAAAAH/9//gAAAAP/4//wAAAAf/wf/4AAAA//gP/4AAAAf/AH/wAAAAP+AD/gAAAAH8AB/AAAAAB8AA8AAAAAA4AAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8/8AAAAAA/8f8AAAAAAAAAAAAAAAAAAAAAAAAAA4AAYAAAAAB4AA8AAAAAD8AB+AAAAAP+AD/gAAAAf/AH/wAAAA//gP/4AAAAf/wf/4AAAAP/4//wAAAAH/9//gAAAAD////AAAAAD///+AAAAAB///8AAAAAA///4AAAAAAf//wAAAAAAP//gAAAAAAH//AAAAAAAD/+AAAAAAAB/+AAAAAAAA/8AAAAAAAAf4AAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+AAAAAAAA/+AAAAAAAA/+AAAfwAAA/8B/4/4AAA/8D/4/8AAA/8D/4/8AAA/8H/4/8AAA/8P/5/8AAB/8P/4/8AAB////4/8AAA////4/8AAA////4f4AAA///+APwAAA///8AAAAAA///8AAAAAAf//4AAAAAAP//wAAAAAAH//AAAAAAAB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/gAAAAAAD//+AAAAAAf///gAAAAB////4AAAAH////+AAAAP/////AAAAf/////gAAA//////wAAB//////4AAD//////8AAH//gAf/8AAP/8AAD/+AAP/wAAA//AAf/gAAAf/AAf/AAP+P/AA//+Af/n/gA///4//3/gA/7/x//7/gB/7/x//7/wB/z/z//9/wB/3/z//9/wB/3/j//9/wB/n/n//8/wD/n/n//8/wD/n/n+f4/wD/n/n8f4/wD/n//8f4/wD/n////w/wD/n////g/wD/n////w/wD/n////5/wB/3////5/wB/3////5/wB/z////9/wB/7////9/gB/5////9/gA/8f///9/gA/+AAAf8AAA//AAAf8AAAf/gAA/8AAAf/4AB/4AAAP//AP/4AAAP/////4AAAH/////wAAAD/////wAAAB/////gAAAA/////AAAAAf///+AAAAAH///8AAAAAB///wAAAAAAP//AAAAAAAAPAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAH/4AAAAAAH//4AAAAAD///4AAAAD////4AAAB/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////gAAAf////4AAAAf////4AAAAf//4f4AAAAf/+Af4AAAAf//+f4AAAAf////4AAAAf////+AAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAB/////4AAAAB////4AAAAAD///4AAAAAAD//4AAAAAAAH/4AAAAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf8B/Af4AAAf8B/Af4AAAf+B/Af4AAAf/v/gf4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAP/////4AAAP/////wAAAH/////wAAAH//f//gAAAD/+P//AAAAA/8H/+AAAAADAB/4AAAAAAAAAAAAAAAAAAAAAAAAAB//+AAAAAAP///wAAAAA////8AAAAB/////AAAAD/////gAAAH/////wAAAP/////wAAAP/////4AAAf/////4AAAf/////4AAAf/////8AAA//+A//8AAA//gAD/8AAA//AAB/8AAA/+AAB/8AAA/+AAA/8AAA/+AAB/8AAA//AAB/8AAAf/AAB/8AAAf/AAB/4AAAf/AAB/4AAAf/gAD/4AAAP/AAB/4AAAPgAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+AAB/4AAAf+AAB/4AAAf+AAB/4AAAf/AAB/4AAAf/gAD/4AAAf/4AP/4AAAf/////4AAAf/////wAAAP/////wAAAP/////wAAAH/////gAAAH/////gAAAD/////AAAAB////+AAAAA////4AAAAAP///wAAAAAD//+AAAAAAAH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+D/g/4AAAf+AAA/4AAAfAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+D/gAAAAAf+AAAAAAAAf+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//+AAAAAAP///wAAAAA////8AAAAB/////AAAAD/////gAAAH/////wAAAP/////wAAAP/////4AAAf/////4AAAf/////8AAAf/////8AAA///j//8AAA//gAD/8AAA//AAB/8AAA//AAB/8AAA//A/h/8AAA//B/x/4AAA//B/x/4AAA//B///wAAAf/B///wAAAf/B///4AAAf/h///4AAAf/h///4AAAf/h///4AAAP/h///4AAAPgB///4AAAAAB///4AAAAAA///4AAAAAAAAAAAAAAAAAAAAAAAP/////wAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAH/gAAAAAAAH/gAAAAAAAH/gAAAAAAAH/gAAAAAAAH/gAAAAAAAH/gAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAAAAAAAAAAAAAYAAAAAAAAAf8AAAAAAAA/8AAAAAAAA/8AAAf/////8AAAf/////8AAAf/////8AAAf/////8AAAf/////8AAAf/////8AAAf/////4AAAf/////4AAAf/////wAAAf/////gAAAf/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAf/+AAAAAAD///wAAAAAP///+AAAAB/////wAAAP/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf//j//4AAAf/8Af/4AAAf/wAD/4AAAf+AAA/4AAAfwAAAH4AAAfAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAA/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf///gAAAAAf////gAAAAf/////gAAAf/////4AAAf/////4AAAf/////4AAAA/////4AAAAA////4AAAAAA///4AAAAAf///4AAAAf////4AAAf/////4AAAf/////4AAAf/////4AAAf////+AAAAf////AAAAAf///gAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAf///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf///AAAAAAP///4AAAAAD///+AAAAAAf///gAAAAAH///4AAAAAA///+AAAAAAP///wAAAAAD///4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAAAAAAAAAAAAAAAAAAAAAAB//+AAAAAAP///wAAAAA////8AAAAD/////AAAAH/////gAAAH/////gAAAP/////wAAAP/////4AAAf/////4AAAf/////4AAAf/////8AAA//4AP/8AAA//AAB/8AAA/+AAA/8AAA/+AAA/8AAA/+AAA/8AAA/+AAA/8AAA//AAB/8AAA//+Af/8AAAf/////4AAAf/////4AAAf/////4AAAP/////wAAAP/////wAAAH/////gAAAD/////AAAAB////+AAAAA////4AAAAAP///gAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+Af4AAAAAf+Af4AAAAAf+A/4AAAAAf///4AAAAAf///4AAAAAf///4AAAAAf///4AAAAAP///wAAAAAP///wAAAAAH///wAAAAAH///gAAAAAD///AAAAAAB//+AAAAAAAf/8AAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAB//+AAAAAAP///wAAAAA////8AAAAD////+AAAAH/////AAAAH/////gAAAP/////wAAAP/////4AAAf/////4AAAf/////4AAAf/////8AAA//4AP/8AAA//AAB/8AAA/+AAA/8AAA/+AAA/8AAA/+AAA/+AAA/+AAA/+AAA//AAB//AAA//+Af//AAAf//////gAAf//////wAAf//////wAAP//////wAAP//////4AAH//////4AAD////+/4AAB////8/4AAA////w/8AAAP///A/8AAAB//4Af8AAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+A/4AAAAAf+A//AAAAAf/A//8AAAAf/////gAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAP/////4AAAP/////4AAAP/////4AAAH/////4AAAD//8P/4AAAB//4B/4AAAAf/gAH4AAAAAgAAA4AAAAAAAAAAAAAAB4AAAAAAAAf/AABwAAAB//wD/wAAAD//4D/4AAAH//8D/4AAAP//+B/4AAAf//+B/4AAAf///B/8AAAf///h/8AAA////g/8AAA////w/8AAA////w/8AAA//f/5/8AAA/+P///8AAA/+P///8AAA/+H///8AAA/+H///4AAA/+D///4AAA/+D///4AAAf/B///wAAAf/A///wAAAf/A///gAAAf/Af//AAAAf4AH/8AAAAAAAB/4AAAAAAAAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAf+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////4AAAAf////+AAAAf/////AAAAf/////gAAAf/////wAAAf/////wAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////8AAAf/////8AAAAAAAB/8AAAAAAAB/8AAAAAAAB/8AAAAAAAB/8AAAAAAAD/8AAAf/////8AAAf/////8AAAf/////4AAAf/////4AAAf/////4AAAf/////wAAAf/////wAAAf/////gAAAf/////AAAAf////+AAAAf////wAAAAAAAAAAAAAAIAAAAAAAAAfwAAAAAAAAf/wAAAAAAAf//gAAAAAAf///gAAAAAf////AAAAAf/////AAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAB/////4AAAAAf///4AAAAAAP//4AAAAAAP//4AAAAD////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////gAAAf////gAAAAf///gAAAAAf//gAAAAAAf/gAAAAAAAfgAAAAAAAAAAAAAAAAAAMAAAAAAAAAf/gAAAAAAAf//+AAAAAAf////wAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAP/////4AAAAAH///4AAAAA////4AAAD/////4AAAf/////4AAAf/////4AAAf/////4AAAf////+AAAAf///+AAAAAf///wAAAAAf////gAAAAf/////AAAAf/////4AAAf/////4AAAf/////4AAAD/////4AAAAB////4AAAAAD///4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf////AAAAAf//gAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAYAAAeAAAAH4AAAf4AAA/4AAAf/AAH/4AAAf/4B//4AAAf//v//4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////wAAAf////8AAAAB////AAAAAAD///4AAAAB/////gAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf//v//4AAAf/4B//4AAAf/AAH/4AAAfwAAA/4AAAcAAAAD4AAAAAAAAAAAAAfAAAAAAAAAf4AAAAAAAAf/AAAAAAAAf/4AAAAAAAf//AAAAAAAf//4AAAAAAf//+AAAAAAf///wAAAAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAB/////4AAAAH////4AAAAH////4AAAD/////4AAAf/////4AAAf/////4AAAf/////4AAAf///4AAAAAf///AAAAAAf//4AAAAAAf//AAAAAAAf/4AAAAAAAf/gAAAAAAAf8AAAAAAAAfgAAAAAAAAcAAAAAAAAAAAAAAAAAAAfAAAAAAAAAf+AAAHAAAAf+AAAf4AAAf+AAB/4AAAf+AAH/4AAAf+AA//4AAAf+AD//4AAAf+AP//4AAAf+A///4AAAf+D///4AAAf+P///4AAAf+////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf/////4AAAf///x/4AAAf///B/4AAAf//8B/4AAAf//wB/4AAAf//AB/4AAAf/8AB/4AAAf/gAB/4AAAf+AAB/4AAAf4AAB/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////+AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AAAAAAAAAAAAfgAAAAAAAAf+AAAAAAAAf/wAAAAAAAf//AAAAAAAf//4AAAAAAf///gAAAAAf///8AAAAAf////wAAAAf/////AAAAf/////4AAAP//////gAAA//////8AAAH//////AAAAf/////AAAAD/////AAAAAP////AAAAAB////AAAAAAH///AAAAAAAf//AAAAAAAD//AAAAAAAAP/AAAAAAAAB/AAAAAAAAAAAAAAAAAAAAAA/wAAAAH+AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AA////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAABwAAAAAAAAHwAAAAAAAAfwAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/gAAAAAAAB/AAAAAAAAB/gAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAAfwAAAAAAAAHwAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAADwAAAAAAAAD4AAAAAAAAD+AAAAAAAAD/AAAAAAAAD/gAAAAAAAD/wAAAAAAAD/wAAAAAAAD/wAAAAAAAD/wAAAAAAAB/wAAAAAAAAfwAAAAAAAADwAAAAAAAAAwAAAAAAAAAAAAAAAAAAABAAP+AAAAAD/Af/gAAAAD/4//wAAAAD/x//4AAAAD/x//4AAAAD/z//8AAAAH/z//8AAAAH/j//8AAAAH/n//8AAAAH/n//8AAAAH/n+f4AAAAH/n8f4AAAAH/38f4AAAAH////wAAAAH////gAAAAH////wAAAAH////4AAAAH////4AAAAH////8AAAAH////8AAAAD////8AAAAB////8AAAAA////8AAAAAD8A/8AAAAAAAAf8AAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////wAAA//////4AAAAD/gA/4AAAAH/gAf8AAAAH/gAf8AAAAH/+H/8AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH////4AAAAH////4AAAAD////wAAAAB////wAAAAA////AAAAAAf//8AAAAAAB//AAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAAAD//4AAAAAAP///AAAAAA////gAAAAB////wAAAAD////wAAAAD////4AAAAH////4AAAAH////8AAAAH////8AAAAH////8AAAAH/4B/8AAAAH/gA/8AAAAH/gA/8AAAAH/gA/8AAAAH/gA/8AAAAH/gA/4AAAAH/wA/4AAAAD/wA/4AAAAD/AABwAAAAAAAAAAAAAAAAAAAAAAAAAD//4AAAAAAP//+AAAAAA////gAAAAB////wAAAAD////4AAAAH////4AAAAH////4AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH/gA/8AAAAH/gAf4AAAAH/gA/4AAA//////4AAA//////wAAA//////wAAA//////4AAA//////4AAA//////8AAA//////8AAA//////8AAA//////8AAA//////8AAA//////8AAAAAAAA/8AAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAB//gAAAAAAH//4AAAAAAf//+AAAAAA////AAAAAB////gAAAAD////wAAAAD////wAAAAH////4AAAAH////4AAAAH////8AAAAH////8AAAAH/n9/8AAAAH/n8/8AAAAH/n8f8AAAAH/38f8AAAAH//8f8AAAAH//8f8AAAAH//8f8AAAAH//8/8AAAAD//8/4AAAAD//8/4AAAAB//8/4AAAAA//8/4AAAAAP/8BwAAAAAD/8AAAAAAAAAAAAAAAAD/AAAAAAAAD/gAAAAAAAD/gAAAAAAD/////4AAAP/////4AAAf/////4AAA//////4AAA//////4AAA//////4AAB//////4AAB//////4AAB//////4AAB//////4AAB//////4AAB/7/gAAAAAB/7/gAAAAAB/7/gAAAAAB///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/A/jwAAAAf/x/34AAAA//5//8AAAB/////+AAAD/////+AAAD/////+AAAH//////AAAH//////AAAH//////AAAH////9/AAAH///v9/AAAH/B/v9/AAAH/B/v9/AAAH/h/v9/AAAH///v9/AAAH///v9/AAAH///P//AAAH///P//AAAH///P/+AAAH//+P/+AAAH//+P/+AAAH//8P/8AAAH//4P/8AAAH//gH/4AAAH+AAD/gAAAH+AAAYAAAAAAAAAAAAAAAAAAAAAAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAAAB/wAAAAAAAD/gAAAAAAAH/gAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAD////4AAAAA////4AAAAAAAAAAAAAGAAAAAAAAAfz////4AAA/7////4AAA/7////4AAB//////4AAB//////4AAB//////4AAB//////4AAB//////4AAA/7////4AAA/7////4AAAfz////4AAACAAAAAAAAAAAAAAAAAAAAAAAAAH/AAHAAAAAP/AAfz//////AA/7//////AA/7//////AB////////AB////////AB////////AB////////AB///////+AA/7/////+AA/7/////8AAfz/////wAAAAAAAAAAAAAAAAAAAAAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAA//////4AAAAAB//4AAAAAAH///AAAAAA////4AAAAD////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH//f/4AAAAH/4H/4AAAAH/gA/4AAAAH+AAP4AAAAHwAAB4AAAAHAAAAYAAAAAAAAAAAAAAAAAAAAAAA//////AAAA//////gAAA//////wAAA//////4AAA//////4AAA//////8AAA//////8AAA//////8AAA//////8AAA//////8AAA//////8AAAAAAAA/8AAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAB////4AAAAB/wAAAAAAAD/gAAAAAAAH/gAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAD////4AAAAB////4AAAAB/wAAAAAAAD/gAAAAAAAH/gAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAB////4AAAAAH///4AAAAAAAAAAAAAAAAAAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAB////4AAAAD/wAAAAAAAD/gAAAAAAAH/gAAAAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAD////4AAAAA////4AAAAAAAAAAAAAAAABQAAAAAAAD//wAAAAAAP//+AAAAAA////AAAAAB////gAAAAB////wAAAAD////wAAAAD////4AAAAH////4AAAAH////8AAAAH////8AAAAH////8AAAAH/gAf8AAAAH/AAf8AAAAH/AAf8AAAAH////8AAAAH////8AAAAH////8AAAAH////4AAAAD////4AAAAD////4AAAAB////wAAAAB////gAAAAA////AAAAAAP//+AAAAAAD//wAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAD//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAD//////AAAD//////AAAH/gA/4AAAAH/gAf8AAAAH/gAf8AAAAH/+H/8AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH////4AAAAH////4AAAAD////wAAAAB////wAAAAA////AAAAAAP//8AAAAAAA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAAAAAH//8AAAAAAf///AAAAAB////gAAAAD////wAAAAD////4AAAAH////4AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH/8H/8AAAAH/gA/8AAAAH/gAf4AAAAD/gA/4AAAAD//////AAAD//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAH/////+AAAAAAAAAAAAAAAAAAAAAAAD////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAD/4AAAAAAAH/wAAAAAAAH/wAAAAAAAH/wAAAAAAAH/gAAAAAAAH/gAAAAAAAH/gAAAAAAAAAAAAAAAAAAf/AAAAAAAA//h/4AAAAB//x/4AAAAD//4/4AAAAD//8/4AAAAH//8/8AAAAH//+/8AAAAH//+f8AAAAH///f8AAAAH///f8AAAAH/f//8AAAAH/f//8AAAAH/P//8AAAAH/v//8AAAAH/n//4AAAAH/n//4AAAAH/j//wAAAAH/h//wAAAAD/g//gAAAADwAP+AAAAAAAAAAAAAAAD/AAAAAAAAD/AAAAAAAAD/AAAAAAAAH////AAAAD/////gAAAD/////wAAAD/////4AAAD/////8AAAD/////8AAAD/////8AAAD/////8AAAD/////8AAAD/////8AAAD/////8AAAAD/AA/8AAAAD/AA/8AAAAD/AA/8AAAAD/AA/8AAAAD/AA/4AAAAAAAAAAAAAAAAAAAAAAAAH////AAAAAH////wAAAAH////wAAAAH////4AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH////8AAAAH////4AAAAAAAA/4AAAAAAAA/4AAAAAAAB/wAAAAD////wAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAAAAAAAAAAAH8AAAAAAAAH/wAAAAAAAH//gAAAAAAH///AAAAAAH///8AAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAA////4AAAAAAf//4AAAAAAAP/4AAAAAAP//4AAAAAf///4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////gAAAAH///wAAAAAH//4AAAAAAH/8AAAAAAAH/AAAAAAAAAAAAAAAAAAH/4AAAAAAAH//+AAAAAAH////gAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////4AAAAAAf//4AAAAAP///4AAAAH////4AAAAH////4AAAAH////4AAAAH////AAAAAH///AAAAAAH///4AAAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAAH///4AAAAAAf//4AAAAD////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH///8AAAAAH//wAAAAAAH/AAAAAAAAAAAAAAAAAAHgAAB4AAAAH8AAH4AAAAH/gA/4AAAAH/+H/4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAD////gAAAAAP//4AAAAAAP///AAAAAD////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH//f/4AAAAH/4D/4AAAAH/AAf4AAAAHwAAD4AAAAGAAAAYAAAAAAAAAAAAAAH+AAAAAAAAH/wAAH/AAAH//AAH/AAAH//8AH/AAAH///wH/AAAH////H/AAAH//////AAAH//////AAAH//////AAAH//////AAAH//////AAAAP/////AAAAAH////AAAAAB///+AAAAB////+AAAB/////8AAAH/////8AAAH/////wAAAH/////AAAAH////4AAAAH///+AAAAAH///wAAAAAH//8AAAAAAH//AAAAAAAH/wAAAAAAAH8AAAAAAAADAAAAAAAAAAAAAAAAAAAH/gAP4AAAAH/gA/4AAAAH/gD/4AAAAH/gH/4AAAAH/gf/4AAAAH/h//4AAAAH/j//4AAAAH/v//4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH////4AAAAH//8/4AAAAH//4/4AAAAH//g/4AAAAH/+A/4AAAAH/4A/4AAAAH/wA/4AAAAH/AA/4AAAAB8AA/4AAAAAAAAAAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAD//////gAAP//////4AAf//////8AA///////+AA///////+AA///////+AA////////AA////////AA////////AA///+////AA///4f///AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////AAf///////AAf///////AAf///////AAf///////AAf///////AAf///////AAf///////AAf///////AAf///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AA/4AAAAH/AA///4f///AA///+////AA////////AA////////AA///////+AA///////+AA///////+AA///////+AAf//////8AAP//////4AAD//////gAAAAA/8AAAAAAAAf8AAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAf4AAAAAAAA/4AAAAAAAB/4AAAAAAAB/4AAAAAAAB/4AAAAAAAB/4AAAAAAAB/wAAAAAAAB/gAAAAAAAA/gAAAAAAAA/wAAAAAAAA/wAAAAAAAD/wAAAAAAAD/wAAAAAAAD/wAAAAAAAD/wAAAAAAAD/gAAAAAAAD/AAAAAAAAB+AAAAAAAAAAAAAAAAAAA="),
    32,
    atob("DREbHhswJQ8UExobERYQFx0RGRofGh0ZHBsQERcaFxc2Hh4aIBkYHh8PEB4XKB8gHSEeGhofHykeHRwSFxEYGRYbHBYdGxMcGw4OHA8qGxwcHBQVFBsbIxscGBMQFRo="),
    60|65536
  );
};
// X/Y are the position of the bottom risdvght of the HH:MM text - make it central!
const X = (g.getWidth()/2),
      Y = (g.getHeight()/2);

function draw() {
  
  
  // work out how to displasvy the current time
  var d = new Date();
  var clock = require("locale").time(d, 1 /*omit sesvconds*/);
  var meridian = require("locale").meridian(d);
  // Reset the state of the graphics library
  g.clearRect(0,50,g.getWidth(),100);
  g.reset();
  // draw the current time (4x size 7 segment)
  

  g.setFontAlign(0,1); // align bottom right
  
  
  g.setFontBold();
  g.drawString(" "+clock+" ", X-10, Y, true /*clear background*/);
  // draw the meridian(am/pm) and seconds (2x size 7 segment)
  g.setFont("Teletext10x18Mode7:1");

  g.setFontAlign(-1,1); // align bottom left
  g.drawString(meridian, X+50, Y-10, true /*clear background*/);
  // draw the date, in a normal font
  
  g.setFontAlign(0,1); // align center bottom
  // pad the date - this clears the background if the date were to change length
  var dateStr = require("locale").dow(new Date(), 1)+", "+ require("locale").month(new Date(), true)+" "+new Date().getDate();
  g.drawString(dateStr, g.getWidth()/2, Y+15, true /*clear background*/);
  

  
  
  //WIDGETS
  Bangle.loadWidgets();
  //Draw Bar for widgets
  const top = Bangle.appRect.y; // Usually ~24
  if (top > 0) {
    g.setColor(g.theme.fg);
    g.fillRect(0, 0, g.getWidth(), top);
  }
  Bangle.drawWidgets();
  
  
}

// Clear the screen once, at startup
g.clear();

// draw immediately at first
draw();

// Load the clock infos
let clockInfoItems = require("clock_info").load();

//CLOCK INFO 1 DIMENSIONS: 13,113,w:66,h:55  

let clockInfoMenuLeft = require("clock_info").addInteractive(clockInfoItems, {
  // Add the dimensions we're rendering to here - these are used to detect taps on the clock info area
  x : 13, y: 113, w: 66, h:55,
  // You can add other information here you want to be passed into 'options' in 'draw'
  // This function draws the info
  draw : (itm, info, options) => {
    // itm: the item containing name/hasRange/etc
    // info: data returned from itm.get() containing text/img/etc
    // options: options passed into addInteractive
    // Clear the background
    g.reset().clearRect(options.x-5, options.y-5, options.x+options.w+5, options.y+options.h+5);
    // indicate focus - we're using a border, but you could change color?
    if (options.focus){
      // show if focused
      g.setColor(0,15,255);
      bRoundedRectangle(10,110,82,170,8); 
    }else{
      g.setColor(g.theme.fg);
      bRoundedRectangle(10,110,82,170,8); 
    }
    // we're drawing center-aligned here
    var midx = options.x+options.w/2;
    if (info.img) g.drawImage(info.img, midx-12,options.y+4); // draw the image
    g.setFont("6x8:2").setFontAlign(0,1).drawString(info.text, midx,options.y+44); // draw the text
  }
});


bRoundedRectangle(94,110,166,170,8);  
//CLOCK INFO RIGHT DIMENSIONS: 97,113, w:66, h: 55
let clockInfoMenuRight = require("clock_info").addInteractive(clockInfoItems, {
  // Add the dimensions we're rendering to here - these are used to detect taps on the clock info area
  x : 97, y: 113, w: 66, h:55,
  // You can add other information here you want to be passed into 'options' in 'draw'
  // This function draws the info
  draw : (itm, info, options) => {
    // itm: the item containing name/hasRange/etc
    // info: data returned from itm.get() containing text/img/etc
    // options: options passed into addInteractive
    // Clear the background
    g.reset().clearRect(options.x-5, options.y-5, options.x+options.w+5, options.y+options.h+5);
    // indicate focus - we're using a border, but you could change color?
    if (options.focus){
      // show if focused
      g.setColor(0,15,255);
      bRoundedRectangle(94,110,166,170,8);     
    }else{
      g.setColor(g.theme.fg);
      bRoundedRectangle(94,110,166,170,8);   
    }
    // we're drawing center-aligned here
    var midx = options.x+options.w/2;
    if (info.img) g.drawImage(info.img, midx-12,options.y+4); // draw the image
    g.setFont("6x8:2").setFontAlign(0,1).drawString(info.text, midx,options.y+44); // draw thesv text
  }
});

    
// now drawsv every minute
var secondInterval = setInterval(draw, 60000);
Bangle.setUI("clock");
