require("heatshrink").decompress(atob("ADMP+AFDv/+AgUB///wAFBgf4j/AAoMH4ED8AcCAQIeCjwCBvACBngCEnACBjgOECgVwAQMOAo4mCFgQyCg4FfFIo7LKYpfFBAQOCOIp9Fg+AgI4CgaPBSoQJBBoKoCU4KzDAoq5EJAJGCAps4JIQABn/8Aocf/DpJACoA=="))
}
