 {
  width : 40, height : 40, bpp : 4,
  transparent : 0,
  buffer : require("heatshrink").decompress(atob("ADkikQRRAAYRLgUikczAAUykUgEpQPBEwYFCCRMjEIIoCAgQCBHI4KCn//AAXzCgQ9GGYISD+YDDBQQmHl4kDFQfyFA0CDYI4DAAYWBFAITEkQmEJ4gIBFAI8DHQImI+Q+CEIIoCHQMjCY4cDmQ8DgQ6LMoYTCFgKbEHQwYBKAZ9BHRYABB4ITCMQ46EMgYTCMQ46EMgQTBRQITGeYIHGRgITCaogzBCYgLBCbI7HJ46gBMZCZBMY6LJBoJDFCYazIFAqzDbZIoBbY8CmS/FB4a5DkZiBCYMzMg4rFmYTDMhJiFCYRQCHhA6DJwQ8DFBUiHQY8DFAjhEEwI6EHgQoBB4QTD+YKCCQgoDdYoSBEw4oCCgUjmczAgQCBCQw9DGYIACAoQSIHoImDFAY5HFIoAECJYVFCJ4AMA="))
}
