name: Check formatting with Prettier
on: [push, pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Check formatting
        run: |
          shopt -s globstar
          npx prettier --check **/*.js