name: Check formatting with Prettier
on: [push, pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code formatting
        uses: actionsx/prettier@v2
        with:
          args: --check **/*.js