/* jshint esversion: 6 */
/* exported distanceUnits */
/* exported speedUnits */
/* exported codePages */
/* exported locales */
/**
 * THIS FILE IS AUTOGENERATED.
 * If you need to edit it, please do so in 'apps/locale/locales-meta.js' instead.
 */

const distanceUnits = {
  "m": 1,
  "ft": 0.3048,
  "yd": 0.9144,
  "mi": 1609.34,
  "km": 1000,
  "kmi": 1000,
  "nm": 1852
};
const speedUnits = {
  "kmh": 1,
  "kph": 1,
  "km/h": 1,
  "kmt": 1,
  "km/t": 1,
  "km/tim": 1,
  "mph": 1.60934,
  "kts": 1.852
};

const codePages = {
  "ISO8859-1": {
    "name": "ISO8859-1",
    "map": "€.‚ƒ„…†‡ˆ‰Š‹Œ.Ž..‘’“”•–—˜™š›œ.žŸ.¡¢£¤¥¦§¨©ª«¬.®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ"
  }
};

var locales = {
  "en_GB": {
    "lang": "en_GB",
    "icon": "🇬🇧",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "mph",
    "distance": {
      "0": "yd",
      "1": "mi"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%b %d %Y",
      "1": "%d/%m/%Y"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "en_US": {
    "lang": "en_US",
    "icon": "🇺🇸",
    "notes": "USA with MM/DD/YY date",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "mph",
    "distance": {
      "0": "ft",
      "1": "mi"
    },
    "temperature": "°F",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%b %-d, %Y",
      "1": "%-m/%-d/%y"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "en_US 2": {
    "lang": "en_US 2",
    "icon": "🇺🇸",
    "notes": "USA with YYYY-MM-DD date",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "mph",
    "distance": {
      "0": "ft",
      "1": "mi"
    },
    "temperature": "°F",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%b %d, %Y",
      "1": "%Y-%m-%d"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "en_IN": {
    "lang": "en_IN",
    "icon": "🇮🇳",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%d/%m/%y"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "en_IE": {
    "lang": "en_IE",
    "icon": "🇮🇪",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%d/%m/%Y"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "en_NAV": {
    "lang": "en_NAV",
    "icon": "⛵✈️",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "kts",
    "distance": {
      "0": "m",
      "1": "nm"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%b %d %Y",
      "1": "%d/%m/%Y"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "de_DE": {
    "lang": "de_DE",
    "icon": "🇩🇪",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%d. %b %Y",
      "1": "%d.%m.%Y"
    },
    "abmonth": "Jan,Feb,Mär,Apr,Mai,Jun,Jul,Aug,Sep,Okt,Nov,Dez",
    "month": "Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember",
    "abday": "So,Mo,Di,Mi,Do,Fr,Sa",
    "day": "Sonntag,Montag,Dienstag,Mittwoch,Donnerstag,Freitag,Samstag",
    "trans": {
      "yes": "ja",
      "Yes": "Ja",
      "no": "nein",
      "No": "Nein",
      "ok": "ok",
      "on": "an",
      "off": "aus",
      "< Back": "< Zurück",
      "Delete": "Löschen",
      "Mark Unread": "Als ungelesen markieren"
    }
  },
  "en_JP": {
    "lang": "en_JP",
    "icon": "🇯🇵",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%Y/%m/%d",
      "1": "%Y/%m/%d"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "nl_NL": {
    "lang": "nl_NL",
    "icon": "🇳🇱",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%d-%m-%Y"
    },
    "abmonth": "jan,feb,mrt,apr,mei,jun,jul,aug,sep,okt,nov,dec",
    "month": "januari,februari,maart,april,mei,juni,juli,augustus,september,oktober,november,december",
    "abday": "zo,ma,di,wo,do,vr,za",
    "day": "zondag,maandag,dinsdag,woensdag,donderdag,vrijdag,zaterdag",
    "trans": {
      "yes": "ja",
      "Yes": "Ja",
      "no": "nee",
      "No": "Nee",
      "ok": "ok",
      "on": "aan",
      "off": "uit",
      "< Back": "< Terug",
      "Delete": "Verwijderen",
      "Mark Unread": "Markeer als ongelezen"
    }
  },
  "en_NL": {
    "lang": "en_NL",
    "icon": "🇳🇱",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "km/h",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%b %d %Y",
      "1": "%d/%m/%Y"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "en_CA": {
    "lang": "en_CA",
    "icon": "🇨🇦",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "km/h",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%b %-d, %Y",
      "1": "%Y-%m-%d"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "fr_FR": {
    "lang": "fr_FR",
    "icon": "🇫🇷",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "km/h",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%d/%m/%Y"
    },
    "abmonth": "janv,févr,mars,avr,mai,juin,juil,août,sept,oct,nov,déc",
    "month": "janvier,février,mars,avril,mai,juin,juillet,août,septembre,octobre,novembre,décembre",
    "abday": "dim,lun,mar,mer,jeu,ven,sam",
    "day": "dimanche,lundi,mardi,mercredi,jeudi,vendredi,samedi",
    "trans": {
      "yes": "oui",
      "Yes": "Oui",
      "no": "non",
      "No": "Non",
      "ok": "ok",
      "on": "on",
      "off": "off"
    }
  },
  "sv_SE": {
    "lang": "sv_SE",
    "icon": "🇸🇪",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "km/tim",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "fm",
      "1": "em"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%b %d %Y",
      "1": "%Y-%m-%d"
    },
    "abmonth": "jan,feb,mars,apr,maj,juni,juli,aug,sep,okt,nov,dec",
    "month": "januari,februari,mars,april,maj,juni,juli,augusti,september,oktober,november,december",
    "abday": "sön,mån,tis,ons,tors,fre,lör",
    "day": "söndag,måndag,tisdag,onsdag,torsdag,fredag,lördag",
    "trans": {
      "yes": "ja",
      "Yes": "Ja",
      "no": "nej",
      "No": "Nej",
      "ok": "ok",
      "on": "on",
      "off": "off"
    }
  },
  "en_SE": {
    "lang": "en_SE",
    "icon": "🇸🇪",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "km/h",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%B %d %Y",
      "1": "%Y-%m-%d"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "da_DK": {
    "lang": "da_DK",
    "icon": "🇩🇰",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "km/t",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH.%MM.%SS",
      "1": "%HH.%MM"
    },
    "datePattern": {
      "0": "%-d. %b %Y",
      "1": "%d.%m.%Y"
    },
    "abmonth": "jan,feb,mar,apr,maj,jun,jul,aug,sep,okt,nov,dec",
    "month": "januar,februar,marts,april,maj,juni,juli,august,september,oktober,november,december",
    "abday": "søn,man,tir,ons,tor,fre,lør",
    "day": "søndag,mandag,tirsdag,onsdag,torsdag,fredag,lørdag",
    "trans": {
      "yes": "ja",
      "Yes": "Ja",
      "no": "nej",
      "No": "Nej",
      "ok": "ok"
    }
  },
  "en_DK": {
    "lang": "en_DK",
    "icon": "🇩🇰",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "km/h",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH.%MM.%SS",
      "1": "%HH.%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%d/%m/%Y"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "en_NZ": {
    "lang": "en_NZ",
    "icon": "🇳🇿",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "kph",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%d/%m/%Y"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "en_AU": {
    "lang": "en_AU",
    "icon": "🇦🇺",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%-d/%-m/%y"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "de_AT": {
    "lang": "de_AT",
    "icon": "🇦🇹",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%d.%m.%Y",
      "1": "%d.%m.%y"
    },
    "abmonth": "Jän,Feb,Mär,Apr,Mai,Jun,Jul,Aug,Sep,Okt,Nov,Dez",
    "month": "Jänner,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember",
    "abday": "So,Mo,Di,Mi,Do,Fr,Sa",
    "day": "Sonntag,Montag,Dienstag,Mittwoch,Donnerstag,Freitag,Samstag",
    "trans": {
      "yes": "ja",
      "Yes": "Ja",
      "no": "nein",
      "No": "Nein",
      "ok": "ok",
      "on": "an",
      "off": "aus",
      "< Back": "< Zurück",
      "Delete": "Löschen",
      "Mark Unread": "Als ungelesen markieren"
    }
  },
  "en_IL": {
    "lang": "en_IL",
    "icon": "🇮🇱",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": ",",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%d/%m/%Y"
    },
    "abmonth": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    "month": "January,February,March,April,May,June,July,August,September,October,November,December",
    "abday": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "day": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"
  },
  "es_ES": {
    "lang": "es_ES",
    "icon": "🇪🇸",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%-d/%-m/%y"
    },
    "abmonth": "ene,feb,mar,abr,may,jun,jul,ago,sept,oct,nov,dic",
    "month": "enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre",
    "abday": "dom,lun,mar,mié,jue,vie,sáb",
    "day": "domingo,lunes,martes,miércoles,jueves,viernes,sábado",
    "trans": {
      "yes": "sí",
      "Yes": "Sí",
      "no": "no",
      "No": "No",
      "ok": "ok",
      "on": "on",
      "off": "off",
      "< Back": "< Atrás",
      "Delete": "Borrar ",
      "Mark Unread": "Marcar como no leído"
    }
  },
  "fr_BE": {
    "lang": "fr_BE",
    "icon": "🇧🇪",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%-d/%m/%y"
    },
    "abmonth": "janv,févr,mars,avr,mai,juin,juil,août,sept,oct,nov,déc",
    "month": "janvier,février,mars,avril,mai,juin,juillet,août,septembre,octobre,novembre,décembre",
    "abday": "dim,lun,mar,mer,jeu,ven,sam",
    "day": "dimanche,lundi,mardi,mercredi,jeudi,vendredi,samedi",
    "trans": {
      "yes": "oui",
      "Yes": "Oui",
      "no": "non",
      "No": "Non",
      "ok": "ok",
      "on": "on",
      "off": "off"
    }
  },
  "fi_FI": {
    "lang": "fi_FI",
    "icon": "🇫🇮",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "ap",
      "1": "ip"
    },
    "timePattern": {
      "0": "%HH.%MM.%SS",
      "1": "%HH.%MM"
    },
    "datePattern": {
      "0": "%-d.%-m.%Y",
      "1": "%-d.%-m.%Y"
    },
    "abmonth": "tamm,helm,maal,huht,touk,kesä,hein,elo,syys,loka,marr,joul",
    "month": "tammikuu,helmikuu,maaliskuu,huhtikuu,toukokuu,kesäkuu,heinäkuu,elokuu,syyskuu,lokakuu,marraskuu,joulukuu",
    "abday": "su,ma,ti,ke,to,pe,la",
    "day": "sunnuntai,maanantai,tiistai,keskiviikko,torstai,perjantai,lauantai",
    "trans": {
      "yes": "oui",
      "Yes": "Oui",
      "no": "no",
      "No": "No",
      "ok": "ok",
      "on": "on",
      "off": "off"
    }
  },
  "de_CH": {
    "lang": "de_CH",
    "icon": "🇨🇭",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": "'",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "VM",
      "1": "NM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%d.%m.%Y",
      "1": "%d.%m.%y"
    },
    "abmonth": "Jan,Feb,Mär,Apr,Mai,Jun,Jul,Aug,Sep,Okt,Nov,Dez",
    "month": "Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember",
    "abday": "So,Mo,Di,Mi,Do,Fr,Sa",
    "day": "Sonntag,Montag,Dienstag,Mittwoch,Donnerstag,Freitag,Samstag",
    "trans": {
      "yes": "ja",
      "Yes": "Ja",
      "no": "nein",
      "No": "Nein",
      "ok": "ok",
      "on": "an",
      "off": "aus"
    }
  },
  "fr_CH": {
    "lang": "fr_CH",
    "icon": "🇨🇭",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%d.%m.%y"
    },
    "abmonth": "janv,févr,mars,avr,mai,juin,juil,août,sept,oct,nov,déc",
    "month": "janvier,février,mars,avril,mai,juin,juillet,août,septembre,octobre,novembre,décembre",
    "abday": "dim,lun,mar,mer,jeu,ven,sam",
    "day": "dimanche,lundi,mardi,mercredi,jeudi,vendredi,samedi",
    "trans": {
      "yes": "oui",
      "Yes": "Oui",
      "no": "non",
      "No": "Non",
      "ok": "ok",
      "on": "on",
      "off": "off"
    }
  },
  "it_CH": {
    "lang": "it_CH",
    "icon": "🇨🇭",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ".",
    "thousands_sep": "'",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%d.%m.%y"
    },
    "abmonth": "gen,feb,mar,apr,mag,giu,lug,ago,set,ott,nov,dic",
    "month": "gennaio,febbraio,marzo,aprile,maggio,giugno,luglio,agosto,settembre,ottobre,novembre,dicembre",
    "abday": "dom,lun,mar,mer,gio,ven,sab",
    "day": "domenica,lunedì,martedì,mercoledì,giovedì,venerdì,sabato",
    "trans": {
      "yes": "sì",
      "Yes": "Sì",
      "no": "no",
      "No": "No",
      "ok": "ok",
      "on": "on",
      "off": "off"
    }
  },
  "it_IT": {
    "lang": "it_IT",
    "icon": "🇮🇹",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%d/%m/%y"
    },
    "abmonth": "gen,feb,mar,apr,mag,giu,lug,ago,set,ott,nov,dic",
    "month": "gennaio,febbraio,marzo,aprile,maggio,giugno,luglio,agosto,settembre,ottobre,novembre,dicembre",
    "abday": "dom,lun,mar,mer,gio,ven,sab",
    "day": "domenica,lunedì,martedì,mercoledì,giovedì,venerdì,sabato",
    "trans": {
      "yes": "sì",
      "Yes": "Sì",
      "no": "no",
      "No": "No",
      "ok": "ok",
      "on": "on",
      "off": "off"
    }
  },
  "wae_CH": {
    "lang": "wae_CH",
    "icon": "🇨🇭",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": "'",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d. %b %Y",
      "1": "%Y-%m-%d"
    },
    "abmonth": "Jen,Hor,Mär,Abr,Mei,Brá,Hei,Öig,Her,Wím,Win,Chr",
    "month": "Jenner,Hornig,Märze,Abrille,Meije,Brácet,Heiwet,Öigšte,Herbštmánet,Wímánet,Wintermánet,Chrištmánet",
    "abday": "Sun,Män,Ziš,Mit,Fró,Fri,Sam",
    "day": "Sunntag,Mäntag,Zištag,Mittwuc,Fróntag,Fritag,Samštag",
    "trans": {
      "yes": "sì",
      "Yes": "Sì",
      "no": "no",
      "No": "No",
      "ok": "ok",
      "on": "on",
      "off": "off"
    }
  },
  "tr_TR": {
    "lang": "tr_TR",
    "icon": "🇹🇷",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "ÖÖ",
      "1": "ÖS"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%-d.%m.%Y"
    },
    "abmonth": "Oca,Sub,Mar,Nis,May,Haz,Tem,Agu,Eyl,Eki,Kas,Ara",
    "month": "Ocak,Subat,Mart,Nisan,Mayis,Haziran,Temmuz,Agustos,Eylül,Ekim,Kasim,Aralik",
    "abday": "Paz,Pzt,Sal,Çar,Per,Cum,Cmt",
    "day": "Pazar,Pazartesi,Sali,Çarsamba,Persembe,Cuma,Cumartesi",
    "trans": {
      "yes": "evet",
      "Yes": "Evet",
      "no": "hayir",
      "No": "Hayir",
      "ok": "tamam",
      "on": "acik",
      "off": "kapali"
    }
  },
  "hu_HU": {
    "lang": "hu_HU",
    "icon": "🇭🇺",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kph",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "de",
      "1": "du"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%Y. %b %-d.",
      "1": "%Y. %m. %d."
    },
    "abmonth": "jan,feb,már,ápr,máj,jún,júl,aug,szep,okt,nov,dec",
    "month": "január,február,március,április,május,június,július,augusztus,szeptember,október,november,december",
    "abday": "V,H,K,Sze,Cs,P,Szo",
    "day": "vasárnap,hétfö,kedd,szerda,csütörtök,péntek,szombat",
    "trans": {
      "yes": "igen",
      "Yes": "Igen",
      "no": "nem",
      "No": "Nem",
      "ok": "ok",
      "on": "be",
      "off": "ki"
    }
  },
  "oc_FR": {
    "lang": "oc_FR",
    "icon": "🇫🇷",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "km/h",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HHh%MM:%SS",
      "1": "%HHh%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%-d/%m/%y"
    },
    "abmonth": "gen,feb,març,abr,mai,junh,jul,ago,set,oct,nov,dec",
    "month": "genièr,febrièr,març,abril,mai,junh,julhet,agost,setembre,octòbre,novembre,decembre",
    "abday": "dg,dl,dm,dc,dj,dv,ds",
    "day": "dimenge,diluns,dimars,dimècres,dijòus,divendres,dissabte",
    "trans": {
      "yes": "òc",
      "Yes": "Òc",
      "no": "non",
      "No": "Non",
      "ok": "ok",
      "on": "on",
      "off": "off"
    }
  },
  "pt_BR": {
    "lang": "pt_BR",
    "icon": "🇧🇷",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d de %b de %Y",
      "1": "%d/%m/%Y"
    },
    "abmonth": "jan,fev,mar,abr,mai,jun,jul,ago,set,out,nov,dez",
    "month": "janeiro,fevereiro,março,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro",
    "abday": "dom,seg,ter,qua,qui,sex,sáb",
    "day": "domingo,segunda-feira,terça-feira,quarta-feira,quinta-feira,sexta-feira,sábado",
    "trans": {
      "yes": "sim",
      "Yes": "Sim",
      "no": "não",
      "No": "Não",
      "ok": "confirmar",
      "on": "ativado",
      "off": "desativado"
    }
  },
  "cs_CZ": {
    "lang": "cs_CZ",
    "icon": "🇨🇿",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "dop",
      "1": "odp"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d. %-m. %Y",
      "1": "%d.%m.%y"
    },
    "abmonth": "led,úno,bre,dub,kve,cvn,cvc,srp,zár,ríj,lis,pro",
    "month": "leden,únor,brezen,duben,kveten,cerven,cervenec,srpen,zárí,ríjen,listopad,prosinec",
    "abday": "ne,po,út,st,ct,pá,so",
    "day": "nedele,pondelí,úterý,streda,ctvrtek,pátek,sobota",
    "trans": {
      "yes": "ano",
      "Yes": "Ano",
      "no": "ne",
      "No": "Ne",
      "ok": "ok",
      "on": "zap",
      "off": "vyp"
    }
  },
  "hr_HR": {
    "lang": "hr_HR",
    "icon": "🇭🇷",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "km/h",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "dop",
      "1": "pop"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d. %b %Y.",
      "1": "%d. %m. %Y."
    },
    "abmonth": "sij,velj,ožu,tra,svi,lip,srp,kol,ruj,lis,stu,pro",
    "month": "sijecanj,veljaca,ožujak,travanj,svibanj,lipanj,srpanj,kolovoz,rujan,listopad,studeni,prosinac",
    "abday": "ned,pon,uto,sri,cet,pet,sub",
    "day": "nedjelja,ponedjeljak,utorak,srijeda,cetvrtak,petak,subota",
    "trans": {
      "yes": "da",
      "Yes": "Da",
      "no": "ne",
      "No": "Ne",
      "ok": "ok",
      "on": "Uklj.",
      "off": "Isklj.",
      "< Back": "< Natrag"
    }
  },
  "sl_SI": {
    "lang": "sl_SI",
    "icon": "🇸🇮",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "km/h",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "dop",
      "1": "pop"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d. %b %Y",
      "1": "%-d. %-m. %y"
    },
    "abmonth": "jan,feb,mar,apr,maj,jun,jul,avg,sep,okt,nov,dec",
    "month": "januar,februar,marec,april,maj,junij,julij,avgust,september,oktober,november,december",
    "abday": "ned,pon,tor,sre,cet,pet,sob",
    "day": "nedelja,ponedeljek,torek,sreda,cetrtek,petek,sobota",
    "trans": {
      "yes": "da",
      "Yes": "Da",
      "no": "ne",
      "No": "Ne",
      "ok": "ok",
      "on": "Vklj.",
      "off": "Izklj.",
      "< Back": "< Nazaj"
    }
  },
  "pt_PT": {
    "lang": "pt_PT",
    "icon": "🇵🇹",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "am",
      "1": "pm"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%d/%m/%Y",
      "1": "%d/%m/%y"
    },
    "abmonth": "jan,fev,mar,abr,mai,jun,jul,ago,set,out,nov,dez",
    "month": "janeiro,fevereiro,março,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro",
    "abday": "dom,seg,ter,qua,qui,sex,sáb",
    "day": "domingo,segunda-feira,terça-feira,quarta-feira,quinta-feira,sexta-feira,sábado",
    "trans": {
      "yes": "sim",
      "Yes": "Sim",
      "no": "não",
      "No": "Não",
      "ok": "ok",
      "on": "on",
      "off": "off"
    }
  },
  "pl_PL": {
    "lang": "pl_PL",
    "icon": "🇵🇱",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%-d.%m.%Y"
    },
    "abmonth": "sty,lut,mar,kwi,maj,cze,lip,sie,wrz,paź,lis,gru",
    "month": "styczeń,luty,marzec,kwiecień,maj,czerwiec,lipiec,sierpień,wrzesień,październik,listopad,grudzień",
    "abday": "ndz,pon,wt,sr,czw,pt,sob",
    "day": "niedziela,poniedziałek,wtorek,sroda,czwartek,piątek,sobota",
    "trans": {
      "yes": "tak",
      "Yes": "Tak",
      "no": "nie",
      "No": "Nie",
      "ok": "ok",
      "on": "on",
      "off": "off",
      "< Back": "< Wstecz"
    }
  },
  "lv_LV": {
    "lang": "lv_LV",
    "icon": "🇱🇻",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "pri",
      "1": "pēc"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%Y. gada %-d. %b",
      "1": "%d.%m.%y"
    },
    "abmonth": "jan,feb,mar,apr,mai,jūn,jūl,aug,sep,okt,nov,dec",
    "month": "janvāris,februāris,marts,aprīlis,maijs,jūnijs,jūlijs,augusts,septembris,oktobris,novembris,decembris",
    "abday": "sv,pr,ot,tr,ce,pk,se",
    "day": "Svētdiena,Pirmdiena,Otrdiena,Trešdiena,Ceturtdiena,Piektdiena,Sestdiena",
    "trans": {
      "yes": "jā",
      "Yes": "Jā",
      "no": "nē",
      "No": "Nē",
      "ok": "labi",
      "on": "Ieslēgt",
      "off": "Izslēgt",
      "< Back": "< Atpakaļ"
    }
  },
  "nn_NO": {
    "lang": "nn_NO",
    "icon": "🇳🇴",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kmt",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "FM",
      "1": "EM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d. %b %Y",
      "1": "%d.%m.%Y"
    },
    "abmonth": "jan,feb,mar,apr,mai,jun,jul,aug,sep,okt,nov,des",
    "month": "januar,februar,mars,april,mai,juni,juli,august,september,oktober,november,desember",
    "abday": "søn,mån,tys,ons,tor,fre,lau",
    "day": "søndag,måndag,tysdag,onsdag,torsdag,fredag,laurdag",
    "trans": {
      "yes": "ja",
      "Yes": "Ja",
      "no": "nei",
      "No": "Nei",
      "ok": "ok",
      "on": "på",
      "off": "av",
      "< Back": "< Tilbake",
      "Delete": "Slett",
      "Mark Unread": "Merk som ulesen"
    }
  },
  "nb_NO": {
    "lang": "nb_NO",
    "icon": "🇳🇴",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": " ",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d. %b %Y",
      "1": "%d.%m.%Y"
    },
    "abmonth": "jan,feb,mar,apr,mai,jun,jul,aug,sep,okt,nov,des",
    "month": "januar,februar,mars,april,mai,juni,juli,august,september,oktober,november,desember",
    "abday": "søn,man,tir,ons,tor,fre,lør",
    "day": "søndag,mandag,tirsdag,onsdag,torsdag,fredag,lørdag",
    "trans": {
      "yes": "ja",
      "Yes": "Ja",
      "no": "nei",
      "No": "Nei",
      "ok": "ok",
      "on": "på",
      "off": "av",
      "< Back": "< Tilbake",
      "Delete": "Slett",
      "Mark Unread": "Merk som ulest"
    }
  },
  "ca_ES": {
    "lang": "ca_ES",
    "icon": "🇪🇺",
    "calendar": "gregory",
    "numberingSystem": "latn",
    "decimal_point": ",",
    "thousands_sep": ".",
    "speed": "kmh",
    "distance": {
      "0": "m",
      "1": "km"
    },
    "temperature": "°C",
    "ampm": {
      "0": "AM",
      "1": "PM"
    },
    "timePattern": {
      "0": "%HH:%MM:%SS",
      "1": "%HH:%MM"
    },
    "datePattern": {
      "0": "%-d %b %Y",
      "1": "%-d/%-m/%y"
    },
    "abmonth": "gen,febr,març,abr,maig,juny,jul,ag,set,oct,nov,des",
    "month": "gener,febrer,març,abril,maig,juny,juliol,agost,setembre,octubre,novembre,desembre",
    "abday": "dg.,dl.,dt.,dc.,dj.,dv.,ds.",
    "day": "diumenge,dilluns,dimarts,dimecres,dijous,divendres,dissabte",
    "trans": {
      "yes": "sí",
      "Yes": "Sí",
      "no": "no",
      "No": "No",
      "ok": "d'acord",
      "on": "on",
      "off": "off",
      "< Back": "< Enrere",
      "Delete": "Esborra",
      "Mark Unread": "Marca com a no llegit"
    }
  }
};
